### ISSUE TITLE
Don't display "Test-Run" as root node in tree with only one assembly

### ISSUE THREAD

**Issue by CharliePoole** [TestCentric/testcentric-gui#100]
We should try to work as the V2 gui did: A root should be added only when there are multiple assemblies.

**Comment by CharliePoole** [comment]
__Hacktoberfest contributors...__

This is a relatively easy first contribution. The tree display for the GUI shows a toot node of `TestRun`. The sole function of this node is to give you something to select that includes all assemblies.

When there is only one assembly, we don't need this node. Examine the code and find where we add it. (I could tell you, but where's the fun in that?) Fix it so we only add it when there is more than one assembly being loaded together.

Your fix should work when loading a single assembly or multiple assemblies as well as when adding a second assembly after the first is loaded (Add test file menu item).

**Comment by zBrianW** [comment]
I can have a look at this :)

**Comment by CharliePoole** [comment]
Thanks! I'll be watching for it. (Once you submit the PR, we'll get notified, btw.)

**Comment by drSte** [comment]
Is the issue still open? May I take a look at it?

**Comment by CharliePoole** [comment]
@zBrianW Are you still working on this?

**Comment by zBrianW** [comment]
I didnt get a chance to look over the weekend. @drSte feel free to pick it up 👍

**Comment by CharliePoole** [comment]
Thanks for doing this!
