### ISSUE TITLE
TestCentric Gui Runner 2.0.0-beta3-1, get an error "System.IO.FileNotFoundException : Could not load file or assembly 'System.Data.OleDb, Version=0.0.0.0"

### ISSUE THREAD

**Issue by luciatran** [TestCentric/testcentric-gui#1019]
My tests are developed with VS 2022, NET 6.0. In my solution, I use "System.Data.OleDb" version 7.0.0 for query data in Excel. 

Using TestCentric Gui Runner 2.0.0-beta3-1, I am geting an error "System.IO.FileNotFoundException : Could not load file or assembly 'System.Data.OleDb, Version=0.0.0.0". 

Please be noted that, if I run the test in VS 2022 with Test Explorer, I have no issue. Please help. Thanks

**Comment by CharliePoole** [comment]
Has this worked before? That is, with earlier versions of the GUI?

Can you provide a minimal example reproducing the problem?

**Comment by luciatran** [comment]
Dear Charlie,

Before I had my tests were developed with VS 2017, .NET 4.8 and my tests were run with "testcentric-gui-1.6.4" without any issues.

Recently, I have migrated my tests with NET6.0 and started using "TestCentric Gui Runner 2.0.0-beta3-1" and are seeing the error. I just make an example to reproduce the issue. Please see the attachment. Thanks and appreciate.
[MyTest.zip](https://github.com/TestCentric/testcentric-gui/files/13250254/MyTest.zip)

**Comment by CharliePoole** [comment]
Confirmed under TestCentric 2.0.0-beta-4

**Comment by CharliePoole** [comment]
I revisited this issue to check if it was fixed in the latest build. It was not. However, this time I noticed that there is a warning message regarding LinkToExcel: "...This package may not be fully compatible with your project." I'm going to close this for now, but I'll re-open if you can eliminate that warning and repro it using the latest beta.
