### ISSUE TITLE
An error sometimes raised when executing single test

### ISSUE THREAD

**Issue by gps7** [TestCentric/testcentric-gui#1036]
**Describe the bug**
Sometimes at the end of the test execution the error is raised:  ArgumentOutOfRangeException: Value of '2' is not valid for 'Value'. 'Value' should be between 'minimum' and 'maximum'.

**To Reproduce**
1. Open GUI (preloaded last used test assembly)
2. Right click on any single test scenario
3. Choose run (runs almost 1 minute)
4. The error not always shown but happens maybe 2 times out of 10. So reproduction steps not always reproduce error.

**Expected behavior**
No error to be shown

**Screenshots**
![2024-02-08 Testcentric error](https://github.com/TestCentric/testcentric-gui/assets/21167960/368c0229-56a6-44b3-8bfc-cf2ba639e8cd)

![2024-02-08 Testcentric GUI view](https://github.com/TestCentric/testcentric-gui/assets/21167960/3ea3f15b-861f-412c-9dd2-a045cdfe6f6a)

**Environment (please complete the following information):**
 - TestCentric Version 2.0.0-beta4
 - OS: Windows 10
 - Target Runtime for your test assembly:  .NET Framework 4.8,
 - 

**Details of the dialog**
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentOutOfRangeException: Value of '2' is not valid for 'Value'. 'Value' should be between 'minimum' and 'maximum'.
Parameter name: Value
   at System.Windows.Forms.ProgressBar.set_Value(Int32 value)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9181.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
testcentric
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.0
    CodeBase: file:///C:/ProgramData/chocolatey/lib/testcentric-gui/tools/testcentric.exe
----------------------------------------
TestCentric.Gui.Runner
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.0
    CodeBase: file:///C:/ProgramData/chocolatey/lib/testcentric-gui/tools/TestCentric.Gui.Runner.DLL
----------------------------------------
TestCentric.Gui.Model
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.0
    CodeBase: file:///C:/ProgramData/chocolatey/lib/testcentric-gui/tools/TestCentric.Gui.Model.DLL
----------------------------------------
Mono.Options
    Assembly Version: 6.0.0.0
    Win32 Version: 6.12.0.0
    CodeBase: file:///C:/ProgramData/chocolatey/lib/testcentric-gui/tools/Mono.Options.DLL
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9181.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9172.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
TestCentric.InternalTrace
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/ProgramData/chocolatey/lib/testcentric-gui/tools/TestCentric.InternalTrace.DLL
----------------------------------------
TestCentric.Engine.Api
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.0
    CodeBase: file:///C:/ProgramData/chocolatey/lib/testcentric-gui/tools/TestCentric.Engine.Api.DLL
----------------------------------------
testcentric.extensibility.api
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.0
    CodeBase: file:///C:/ProgramData/chocolatey/lib/testcentric-gui/tools/testcentric.extensibility.api.DLL
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9181.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
testcentric.engine
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.0
    CodeBase: file:///C:/ProgramData/chocolatey/lib/testcentric-gui/tools/testcentric.engine.DLL
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
testcentric.extensibility
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.0
    CodeBase: file:///C:/ProgramData/chocolatey/lib/testcentric-gui/tools/testcentric.extensibility.DLL
----------------------------------------
testcentric.engine.core
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.0
    CodeBase: file:///C:/ProgramData/chocolatey/lib/testcentric-gui/tools/testcentric.engine.core.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
testcentric.engine.metadata
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.0
    CodeBase: file:///C:/ProgramData/chocolatey/lib/testcentric-gui/tools/testcentric.engine.metadata.DLL
----------------------------------------
net462-agent-launcher
    Assembly Version: 2.4.1.0
    Win32 Version: 2.4.1.0
    CodeBase: file:///C:/ProgramData/chocolatey/lib/testcentric-extension-net462-pluggable-agent/tools/net462-agent-launcher.dll
----------------------------------------
net60-agent-launcher
    Assembly Version: 2.4.0.0
    Win32 Version: 2.4.0.0
    CodeBase: file:///C:/ProgramData/chocolatey/lib/testcentric-extension-net60-pluggable-agent/tools/net60-agent-launcher.dll
----------------------------------------
net70-agent-launcher
    Assembly Version: 2.4.0.0
    Win32 Version: 2.4.0.0
    CodeBase: file:///C:/ProgramData/chocolatey/lib/testcentric-extension-net70-pluggable-agent/tools/net70-agent-launcher.dll
----------------------------------------
net80-agent-launcher
    Assembly Version: 0.0.0.0
    Win32 Version: 0.0.0.0
    CodeBase: file:///C:/ProgramData/chocolatey/lib/testcentric-extension-net80-pluggable-agent/tools/net80-agent-launcher.dll
----------------------------------------
System.Runtime.Remoting
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Remoting/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Remoting.dll
----------------------------------------
nunit.uiexception
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.0
    CodeBase: file:///C:/ProgramData/chocolatey/lib/testcentric-gui/tools/nunit.uiexception.DLL
----------------------------------------
System.Web
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9181.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by CharliePoole** [comment]
Are you able to provide a project on which you see this behavior?

**Comment by gps7** [comment]
I tried to create test project but this did not worked. I've also tried to run same test case where originally had an exception and this time I am unable to reproduce this problem anymore. 
The project setup is uncommon for standard setups since our assembly is having only two tests which one of the is ignored (used for debugging only) and another one is using TestCaseSource which is loading dynamically over 700 scenarios at startup:
		```
[Test]
		[TestCaseSource(nameof(TestData))]
		public void ExecuteScenario(TestCase test)
	{
           .................
	}

	[Test, Ignore("Activate this test to perform diagnostics on the loading of test scenarios.")]
	public void TestLoadingScenarios()
	{
	}
```

**Comment by CharliePoole** [comment]
OK... I'll try a test like that.

**Comment by CharliePoole** [comment]
I'll do some code inspection in the areas where the progress bar may be called. If nothing turns up I'll close it.
