### ISSUE TITLE
Issues with the [Tools > Extensions...] dialog

### ISSUE THREAD

**Issue by maettu-this** [TestCentric/testcentric-gui#1046]
**Describe the bug**
A) Title is [Engine Extensions] vs. menu is just [Extensions].
B) Horizontal resize doesn't seem to be as intended, only one box resizes.
C) Vertical resize moves the [OK] button.

**To Reproduce**
1. Go to [Tools > Extensions...].
2. Stretch the dialog horizontally and verically.

**Expected behavior**
A) I would expect the same term.
B) I would expect all elements being resized.
C) I would expect the [OK] button remaining at the bottom of the dialog.

**Screenshots**
B)
![grafik](https://github.com/TestCentric/testcentric-gui/assets/24897735/e4c24784-6d7e-4f8d-9c97-decfbd999602)
C)
![grafik](https://github.com/TestCentric/testcentric-gui/assets/24897735/4dd077e5-bf5b-43f7-a74e-1edba66fd356)

**Environment (please complete the following information):**
 - TestCentric Version 2.0.0-beta-4
 - OS: Win10
 - Target Runtime for your test assembly: n/a

**Comment by CharliePoole** [comment]
A) I think this is OK for now. In the beta so far, the only available extension points are for the engine but support is there internally for extension points in the GUI itself. By final release we'll know whether to change the menu or the title.

B) I agree with this

C) That may be desirable but distributing the extra space among various fields may be tricky. We'll see.

**Comment by CharliePoole** [comment]
Final Resolution: 
A) Keeping this in mind for the final release
B) Fixed
C) The dialog is no longer expandable vertically.
