### ISSUE TITLE
Unfortunate side effect of 'Native high-DPI monitor support'

### ISSUE THREAD

**Issue by mikkelbu** [TestCentric/testcentric-gui#107]
On my laptop the ['Native high-DPI monitor support' change](https://github.com/TestCentric/testcentric-gui/commit/3a5c1b8c2c7c4821f5aed96c2acb52f1260ce0f5) has an unfortunate side effect which makes the UI look strange in a lot of places. I'm not sure if the problem is how we are specifying fonts the UI.

Sorry for the large images below, but the combination of my screen resolution and how GitHub is presenting images makes it look like I need glasses :)

# Examples
## Settings - Text output
Without change (blurry, but reasonable since fonts)
![image](https://user-images.githubusercontent.com/1007631/45897182-bc9f2f00-bdd6-11e8-96d7-44facb55e871.png)

With change (sharp, but too large fonts)
![image](https://user-images.githubusercontent.com/1007631/45897202-c7f25a80-bdd6-11e8-856a-e3137804773f.png)

## About dialog
Without the change
![image](https://user-images.githubusercontent.com/1007631/45897295-04be5180-bdd7-11e8-851f-ad1c3e5ff0eb.png)

With the change
![image](https://user-images.githubusercontent.com/1007631/45897283-fbcd8000-bdd6-11e8-8046-21e0abc9dd9e.png)

**Comment by CharliePoole** [comment]
It's interesting how the About box example uses two different fonts. That may be a clue.

Probably this should wait till after merging issue-95g, since it includes changes to how the font is selected.

**Comment by CharliePoole** [comment]
@mikkelbu I marked this for re-confirmation (on current master) since the code has changed quite a bit.

**Comment by CharliePoole** [comment]
@mikkelbu Are you still seeing this?

**Comment by CharliePoole** [comment]
@mikkelbu I added this to the 1.0 beta milestone, but I can't replicate it on my system. No surprise since it's a Windows 7 VM running on my Linux laptop. Can you investigate further or tell me if there's a way to make this appear?

**Comment by CharliePoole** [comment]
@mikkelbu I took the liberty of assigning this to you, since it appears you're the only one with a shot at seeing and fixing it. If you can't get to it, we can switch it to the post-1.0 milestone.

**Comment by CharliePoole** [comment]
@mikkelbu Have you been able to look at this one again?

**Comment by mikkelbu** [comment]
@CharliePoole Sorry, I've been quite busy the last couple of months. I'm still seeing this as far as I can remember. I'll see if I have time to look more closely at this tonight or tomorrow night.

**Comment by CharliePoole** [comment]
I can move it to the post-1.0 milestone but it would be nice if you could at least re-confirm it. Thanks.

**Comment by mikkelbu** [comment]
I can confirm it. On the HEAD of master my screens looks like this.

<img src="https://user-images.githubusercontent.com/1007631/56163864-bde0b500-5fcf-11e9-91e3-d7e789074dff.png" width="40%"/>

<img src="https://user-images.githubusercontent.com/1007631/56163843-ac97a880-5fcf-11e9-92b6-f3bc70970153.png" width="80%"/>

If I add
```csharp
this.AutoScaleMode = AutoScaleMode.Font;
this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
```
to the beginning of `InitializeComponent` and remove `this.label4.Font = ....` - all changes in `/Dialogs/AboutBox.cs` - then it becomes a little better. But there will be much work to do by removing a lot of hardcoded fonts, locations, and sizes, and I don't think that I have time for it (at least not now).

<img src="https://user-images.githubusercontent.com/1007631/56167215-dead0880-5fd7-11e9-8216-65a92f40415b.png" width="40%"/>

**Comment by CharliePoole** [comment]
Thanks! At least we know it's still there. I moved it to the post-1.0 milestone, which is kind of a catch-all for stuff we want to do between 1.0 and 1.1.

**Comment by maettu-this** [comment]
Adding this to `testcentric.exe.config` could solve or at least improve the situation:
```
  <System.Windows.Forms.ApplicationConfigurationSection>
    <add key="DpiAwareness" value="PerMonitorV2" />
  </System.Windows.Forms.ApplicationConfigurationSection>
```
Had the same issue with my WinForms based project.

Reference:
https://learn.microsoft.com/en-us/dotnet/desktop/winforms/high-dpi-support-in-windows-forms?view=netframeworkdesktop-4.8

**Comment by CharliePoole** [comment]
Thanks! Looks like a great possibility. I'll try this and may ask you to check it out. Unfortunately, when @mikkelbu created it, I wasn't able to replicate it on my windows VM, so I have ignored it. My configuration has changed in the last few months, so I'll take another look. May ask you to verify the fix.

**Comment by CharliePoole** [comment]
OK, I've done a full review of this old bug, which I'd like to get rid of one way or another! I'd very much appreciate it if all those who have been involved with it take a second (or third or fourth...) look...

@jnm2 did the original commit for high-dpi support
@mikkelbu reported this issue
@maettu-this suggested a change to the config

Do you all still see this on beta4? If so at what resolution and scaling? I'm using a resolution of 2560 x 1440 on Linux with the Windows 10 VM set at 2484 x 1361. My normal scaling is 100% (I wear my reading glasses) but I have adjusted it to 200% for testing this issue. Unfortunately, I don't have a physical windows box any more.

My own thoughts...
* It looks to me as if @jnm2's creation of a manifest covered all the bases. Is he config change needed as well?
* In fact, the config has some old stuff, which no longer applies, so it needs an update in any case.
* I think the basic problem is that the application was __not__ dpi-aware at all, so telling windows that it was broke things. The oldest versions simply set a fixed size for each container and tried to fit things into it. That has changed bit by bit as I modified the old code inherited from the NUnitV2 GUI. Currently, I only see one small issue in the About box, which is easy enough to fix.

What do you see?

**Comment by maettu-this** [comment]
I don't see the reported issue anymore, but the about dialog does cut the too long version string:

![grafik](https://github.com/TestCentric/testcentric-gui/assets/24897735/69871168-63c5-41cf-af3e-a7982dc0ebfa)

![grafik](https://github.com/TestCentric/testcentric-gui/assets/24897735/15f6d8cd-f602-49f7-b461-db757b60f7ed)

**Comment by CharliePoole** [comment]
@maettu-this Thanks. I should just be displaying 2.0.0-beta4 anyway.
