### ISSUE TITLE
Toolbar: "Run selected tests" => System.DivideByZeroException

### ISSUE THREAD

**Issue by rowo360** [TestCentric/testcentric-gui#1087]
**Description:**
I observe an exception while starting a test run using the toolbar button 'Run selected tests'. The error message states that there's a DivideByZeroException.
I'm using **TestCentric-Gui 2.0.0-beta5** and the test assembly is targeting **.Net Framwork 4.8.**

This error shows up reliable if I execute this operation as the first test action after loading a project. It also shows up when running all tests first (successfully) and then start "Run selected tests" afterwards. Moreover it doesn't seems to make a difference if I select one test or the top node in the test tree view.

A close look to the screenshot and the error message might indicate that the ProgressBar fails in this scenario.
![grafik](https://github.com/user-attachments/assets/03a3f126-bd6b-410d-877a-da7210f7eb80)

**Steps to reproduce the behavior:**
1. Start TestCentric GUI
2. Create or load project containing some tests
3. Start 'Run selected tests' using the toolbar
=> error occurs

**Environment:**
- TestCentric Version 2.0.0-beta5
- OS: Windows 11
- Target Runtime for your test assembly: .NET Framework 4.8

**Comment by rowo360** [comment]
Quick update:
I notice now, that on my computer the settings -> Tree Display -> 'Display a checkbox next to each tree item' was checked somehow. If this case this exception always occurs, if starting 'Run selected tests'. 
If this settings is unchecked I noticed this exception only right away after starting TestCentric (which loads the last used test project) and pressing immediately 'Run selected tests'. Without changing the default selection in the test tree.

**Comment by CharliePoole** [comment]
@rowo360 Thanks for your work! Let me know if you would like to do any more fixes. :-)

**Comment by rowo360** [comment]
@CharliePoole :
This was my first commit ever to any open source project and a great experience! Thanks for the warm welcome and guidance.
Yes, I can well imagine working on further fixes - at the moment I have some time to help here. Of course, I am not an expert in this project, so it will certainly not be complex tasks.
What's the best option to start? Should I create a new issue and prepare a PR for anything I notice? Or do you prefer to set the direction?

**Comment by CharliePoole** [comment]
I'm glad it has been a good experience!

I checked and see that we have run out of issues labelled "Easy Fix" or I would suggest you start with those. I'll go through and label any that qualify if I find them. Welcome!

Meanwhile, yes, if you notice something wrong, file an issue. (A clearly written issue is a big contribution as well.) If you see a quick fix an immediate PR is OK but if it is going to take a lot of work, I suggest proposing your solution as a comment on the issue first.

Be sure to maintain a local copy of `main`, which you update (pull) before creating a new branch to work on from it. That avoids any later conflicts when merging.
