### ISSUE TITLE
Show checkboxes in tree functionality not 100% consistent

### ISSUE THREAD

**Issue by rowo360** [TestCentric/testcentric-gui#1090]
**Description:**
At least for me the 'Show checkboxes in tree' functionality is sometimes confusing or is not 100% consistent in all cases. Therefore I raise this issue as I've the impression that it doesn't work as intended. But please correct me, if I miss anything.
I'm using **TestCentric-Gui 2.0.0-beta5**.

**Steps to reproduce:**
Problem A:
1. Create a new project
2. Open settings and activate "Show checkboxes" (Tools -> Settings -> Tree Display)
    => No checkboxes are shown
4. Create another project => still no checkboxes are shown
5. Restart the application and create another project, the checkboxes are shown suddenly.
(Note: it's important to use really new test dlls here - which doesn't already have a VisualState file)

Problem B:
1. Create two projects 
2. Activate "Show checkboxes" via tree context menu in one project and keep it deactivated in the other one
3. Load both projects one after the other
4. Open context menu
   => The state of the context menu entry "Show checkboxes", doesn't match to the actual state of the tree.

<img width="221" alt="ContextMenuIsssue" src="https://github.com/user-attachments/assets/97205dba-02ce-448c-a4f9-ed102b64b5ec">

**Show checkbox functionality in general (my interpretation):**
There are two options for the customer to activate "Show checkboxes in tree". Although these options sounds similar their intention is slightly different: 
- In the settings: this option is about to set the default visibility of the checkboxes for newly created projects. It's stored in the application settings. Customers uses this option, if they want to show checkboxes in the tree in general.
- In the context menu of the tree: this option is about to set the visibilty of the checkboxes in the current project. It's stored individually in the VisualState file for each test dll. Customers uses this option, if they want to show checkboxes for individual projects only.

**Expected behavior:**
- If "Show checkboxes" is changed in the settings, it's applied to the test tree immediately.
- If a test is loaded, the checkboxes are shown according to the VisualState file (if present) or the default value from the setting is applied.
  (Moreover the state of the context menu entry 'Show checkboxes" is consistent to the tree)

**Environment:**
- TestCentric Version 2.0.0-beta5
- OS: Windows 11
- Target Runtime for your test assembly: .NET Framework 4.8

**Comment by CharliePoole** [comment]
FYI, VisualState was once an option but I changed it in version 2 so that it is always saved. A bit later, I decided to always load it. You may notice some inconsistencies because they are left over from that history.

So currently, if you change checkboxes in the tree it will be saved in the VisualState as soon as you do anything which causes the state to be saved e.g.: exiting the application or even running tests.
(We save it before running just in case an exception terminates the application.)

As you see, it works as you described it - even though it didn't always work that way. Your expected behavior is what we want.
