### ISSUE TITLE
Close project => Result summary view remains open.

### ISSUE THREAD

**Issue by rowo360** [TestCentric/testcentric-gui#1092]
**Description:**
When closing a project all test related views gets closed (for example TestPropertyView). But the ResultSummaryView remains open, still showing the results from the last test run. The user cannot hide the view himself because the button 'show/hide result' is disabled as no test is loaded.
This behavior is observed by using both view modes: **Full-GUI and Mini-GUI.**

![grafik](https://github.com/user-attachments/assets/c0abe453-b93a-42c9-b0f7-fd2dcce4bb4b)

The same behavior can also be observed when creating a new project or loading another project (instead of closing) - also in these cases the result summary view remains open showing the results from a different project.

**Reproduction:**
1. Load project and run tests
2. Show result summary view
3. Close project or load another project or new project
=> Result summary view remains open

**Expected behavior:**
I assume that the ResultSummary View should be hidden in these cases: close project, load project and create project.
Otherwise, I think it is confusing for the user when test results for previous tests are displayed.

**Environment:**
- TestCentric Version 2.0.0-beta5
- OS: Windows 11
- Target Runtime for your test assembly: .NET Framework 4.8

**Comment by CharliePoole** [comment]
Nice catch. Can you confirm it in the latest dev build?

**Comment by rowo360** [comment]
Yes, I can confirm that this issue is also present with latest dev build.
