### ISSUE TITLE
Change Tree Display Format not working yet

### ISSUE THREAD

**Issue by rowo360** [TestCentric/testcentric-gui#1101]
**Describe the bug**
Currently it's not possible to change the tree display format.
If I change the tree display format to **Fixture list** or **Test List** using the toolbar button, the tree display kept unchanged in NUnit format. Only the toolbar button itself states that the new format is active.
Reloading the project does not help either.

**To Reproduce**
1. Load test
2. Change tree display format to **Fixture list** or **Test List** using toolbar button
    => Tree display is not changed but kept unchanged instead

**Screenshots**
![grafik](https://github.com/user-attachments/assets/71afcf19-5d0e-4c5a-adc8-16d17c1f1b62)

**Environment:**
- TestCentric Version 2.0.0-beta5 and main developer branch
- OS: Windows 11
- Target Runtime for your test assembly: .NET Framework 4.8

**Comment by rowo360** [comment]
I'll analyze this issue further and try to prepare a PR for it.

**Comment by rowo360** [comment]
Here's a list of use cases / test cases considered:

- Change Tree Display format from toolbar (NUnit/Fixture or test list)
  Expectation: tree is updated accordingly to new format
- Close or save test project
  Expectation: current display format is stored in VisualState file
- Load test project and VisualState file exists
  Expectation: tree is displayed in format which is stored in VisualState file; And the selected menu item is updated accordingly
- Load test project and VisualState file doesn't exist
  Expectation: tree is displayed in last used display format; And the selected menu item is updated accordingly

**Comment by CharliePoole** [comment]
@rowo360 I like thinking in use cases. I numbered your items so I can comment on them.

1. All good with the understanding that the VisualState file does not immediately change.
2. OK
3. OK
4. So we use the last format set for _this_ project? or for _any _ project_. Does it depend on whether we changed settings or use the context menu? At one time I intended the context menu setting to be lost on exit. What would be best in your view? Think of somebody who works on many different projects.
5. We currently save the VS file when a run starts. We do this in case of an exception in the user code that crashes the GUI. I didn't want to lose the user's settings in that case. OTOH, maybe we should lose them. What do you think?
6. There are other times when we create an in-memory VisualState but don't (or shouldn't) save it. Probably that can be left out here and addressed if we find a problem later.

**Comment by rowo360** [comment]
No 1: Right, I also thought that the VisualState file would not be saved here.
No 4: I thought that the last format set is used for any project without a VisualState file. I imagined that I worked with a project and set the format according to my preferences. If I now load a new project (without a VS file), I would be surprised if the format suddenly changed to some default format and I need to reapply my preferences. And if I were to load more projects after that, I would probably not only be surprised, but also annoyed soon.
So overall I thought by using the last format set in these use cases, would be beneficial for the user. We can consider this behavior as some 'flexible' default format instead of some hard-coded, fixed default format.
I'll mention it separately: if I restart TestCentric and load a project (without a VS file), the last format set will be applied also in this use case. I imagine whenever I did a 'clean' of my workspace and all of my VisualState files gets cleaned up, I would be happy if someone remembers my preferences (I hope that this isn't just happening to me :-)) Therefore I would not loose the setting on exit.
Another consideration: so far I have thought to implement this in such a way that the this setting is updated in the background whenever the user changes the format from the menu (so finally it's stored in the settings and the VS file). But of course I can also extend the settings dialog in which the user can configure his preferred format himself - which will still only be applied when no VS file exists. I mention it only as an alternative - I believe it's not required now. And I'd stick with the 'last format set' idea.
No 5: I noticed that VS file is save already when starting a test run. And I was also glad about it!
However I wonder myself, if it makes a difference in the long run? Maybe I don't have an overview - but I expect that the GUI won't crash even if there's an exception in some user code or some user extension. Maybe that's not always the case right now, but that should be the target state, isn't it?

**Comment by CharliePoole** [comment]
On No. 4. OK, I'm convinced. My thinking was based on the older paradigm when Visual State files were an experimental feature and not used so often. Now there is no choice and they are always created.

On No. 5. Let's not change what it's now doing. 

On background changes... the settings are always updated in the background _in memory_. There should be no need to save them until the end of the session. Also if we did save on a background thread, we would have to consider the possibility that two instances are running, which I'd rather avoid. :-)

**Comment by rowo360** [comment]
This bug is solved with PR #1102 
I' ve good feeling that users can work with the different tree display formats, now. Unfortunately it's not perfect yet - I noticed crashes in two scenarios. However I prefer to create separate issues for those - because maybe it needs to be discussed in detail first and it would enlarge this issue and PR further.
