### ISSUE TITLE
Eliminate .Net 5.0 Agent

### ISSUE THREAD

**Issue by CharliePoole** [TestCentric/testcentric-gui#1115]
At this point, I'm inclined to do that. We have a .NET 6.0 agent and are about to add one for .NET 8.0. So tests targeting those two out of date runtimes can still be executed.

@rowo360  What do you think? This would be for the 1.7.0 release.

**Comment by rowo360** [comment]
Puh, that's a difficult question! I don't know if I can provide a good answer as I'm not that familiar how long .Net version were supported in the past? Or how the NUnit project deals with this kind of question?
Is such kind of change announced in advance?

As a developer, I always prefer that outdated versions are not supported for too long. It just increase the complexity for developing, testing and deploying. On the other hand, I also know from the company that sometimes you have to stick with one .Net version. You would like to change it, but unfortunately there are dependencies that you don't have access to.

If we drop the support for those versions, it would be a breaking change between 1.6.X and 1.7.0 ?
I'm just worried that some users will complain.

So overall, I wrote down some comments, but I still can't decide how to answer.
So maybe I prefer to keep them supported, but remove the support in the 2.0.X releases!

**Comment by CharliePoole** [comment]
Both of those have been unsupported by MS for a while. I dropped .NET 5.0 in the NUnit console, but Terje was a little uncertain about dropping .NET Core 3.1. I'll continue to think about this. 

I'm OK with breaking the semver rules here, if we do it, since we can't do a major update of the V1 code at this point. But we would have to list it as breaking so that users know. They would have to choose between support for .NET 6.0, .NET 8.0 and NUnit 4 versus continued support of the legacy runtimes in deciding whether to upgrade.

**Comment by CharliePoole** [comment]
@rowo360 I think we'll follow the NUnit project on these. .NET 5.0 was dropped in from the 3.18.0 engine while we decided to hold on to 3.1 for another six months or so. Renaming this issue accordingly to deal with the elimination of 5.0.
