### ISSUE TITLE
Test result icon in tree is not applied for group nodes

### ISSUE THREAD

**Issue by rowo360** [TestCentric/testcentric-gui#1118]
**Describe the bug**
When I run a test, the test results are displayed in the TreeNode with a matching icon.
This applies for all test nodes except group nodes.

Here are some screenshots:

1. 'Fixture list' view and group by 'Category' => run all tests
<img src="https://github.com/user-attachments/assets/244f3d2a-22d3-4530-8c23-a84f58d9bc31" width="250">

=> All category nodes keep their 'initial' state.

2. 'Fixture list' view and group by 'Category' => run only one single test case 'TestB'
<img src="https://github.com/user-attachments/assets/d877afb3-fd1f-4eaa-bbda-5e5de3ec5b98" width="250">

=> State of test fixture 'Feature1Tests' is updated; but Category node not

3. 'Test list' view and group by 'Outcome' => run tests of group 'Failed'
<img src="https://github.com/user-attachments/assets/2ed381d3-fae1-4488-8aaf-3ee94ea5b89b" width="250">

=> 'Failed' node is not getting updated

**Expected behavior**
I expect that the test result state is applied to all kind of tree node.
Even if only a subset of the tests is executed, its test results should be passed upwards. Just as I know it from the NUnitTreeDisplay format.

**Environment (please complete the following information):**
- TestCentric Version - latest developer build 2.0.0-dev00451
- OS: Windows 11

**Comment by rowo360** [comment]
I believe that the current system behavior can be explained by looking at the XML structure. Whenever the execution of a test case is completed, we receive an event and perform actions to update the icon. 

That's fine, however group nodes (like categories) are no represented in this XML structure, so we'll receive no events for them.
This means that we have to determine the correct test result for groups ourselves and then set the icon.

**Good news:**
I think that exactly this behavior is already implemented in the code base. But unfortunately it's not invoked anymore.
This code is located here: `CategoryGrouping.OnTestFinished()`

<img src="https://github.com/user-attachments/assets/62a2d791-84d6-472e-b03b-32492ace1996" width="400">

So my idea is to simply reactivate this code. If that works, then I can check why this is actually implemented in the CategoryGrouping class and how the two DuractionGrouping and OutcomeGrouping behave.

**Comment by CharliePoole** [comment]
Cool! Of course, it may be disabled because it caused some problem or it may be unfinished work, but let's find out.

**Comment by rowo360** [comment]
Issue is solved by PR #1121
