### ISSUE TITLE
Crash: Start test run using context menu while test is running

### ISSUE THREAD

**Issue by rowo360** [TestCentric/testcentric-gui#1130]
**Describe the bug**
When a test run is started all toolbar buttons like 'Run all' or 'Run selected' are disabled until the test run is finished.
However the context menu entry 'Run' is still enabled.

**To Reproduce**
1. Load a project and start a test run 
    Important: the tests should run slow, so that there's enough time to execute the next steps **before** this run is finished.
2. Open tree context menu and select 'Run'
3. Crash

**Expected behavior**
I believe the context menu entry 'Run' should be disabled while a test is running. That's the identical behavior to all those toolbar buttons.

**Screenshots**
<img src="https://github.com/user-attachments/assets/6af7f2d6-b0b4-4b3a-a63e-1e91df9b51b3" width="600">

**Environment (please complete the following information):**
 - TestCentric Version: latest developer build (and probably also 2.0.0-beta5)
 - OS: Windows 11

**Comment by rowo360** [comment]
The actual crash is happening from the progress bar! Somehow it get confused by the number of tests in the test run and the maximum value. I didn't look to the details here, because I think we should stop this use right from the start and disable the context menu in this case.
Probably the 'Debug' context menu entry should be disabled as well.

**Comment by CharliePoole** [comment]
They should be added to the relevant tests as well.

**Comment by rowo360** [comment]
This issue is solved by PR #1131 => closed
