### ISSUE TITLE
Crash - toolbar button 'Run selected tests'

### ISSUE THREAD

**Issue by rowo360** [TestCentric/testcentric-gui#1138]
**Describe the bug**
I noticed this crash when clicking on the toolbar button 'Run selected tests'.

<img src="https://github.com/user-attachments/assets/5cc60c3a-4fb0-4716-b1bd-0559a7f4870c" width="300">

This crash occurs only:
- A project is just opened
- The option 'Show checkboxes' is enabled
- The 'checked' state of any state was not changed at all

There must be an additional condition for this crash, but unfortunately I can't name it exactly. First I thought it's related to the current Strategy/Grouping, but repeating the same steps which were previously causing the crash suddently work.
That's strange and my only explanation for this is that an event may not be fired...

Actually I want to click 'Run all tests' and accidently hit 'Run selected tests' ;-)

**Environment (please complete the following information):**
- TestCentric Version - latest developer build
- OS: Windows 11

**Comment by rowo360** [comment]
The actual crash occurs because of a `NullReferenceException`:

<img src="https://github.com/user-attachments/assets/ea5ac6e4-59b8-400a-8dc3-b5522b300582" width="600">

The `SelectedTests` is null here and this kind of input is not accepted by the method `_model.RunTests`

In common the `SelectedTests` property is set when checking/unchecking tree nodes or even when loading a project (with or without VisualState file), but for some reasons this is not triggered in my use case !?!

I propose to fix this issue simply by checking this null case. Another option might be to initialize the `SelectedTests' not with null, but with an empty TestSelection. But I prefer the simplest approach right now without dealing with all details.

**Comment by rowo360** [comment]
This kept me wondering why the behavior seems so random. Usually you can quickly explain the behavior and it just seems random until you identify the root cause. That's why I started another attempt doing some further debugging/logging of this use case:
I didn't came to a final conclusion, but I describe my current investigation - maybe you notice something:

In common the property SelectedTests gets set in this use case (load project) by the TreeViewPresenter.AfterCheck:
<img src="https://github.com/user-attachments/assets/0e48d15e-156d-4bab-a78c-0339ddf84adb" width="400">

This method is invoked whenever the checked state (checkbox) of a tree node is changed. And in common this method gets called during project load, too. And in general: if this method is called, the SelectedTests property won't be null! It must therefore be the case that the method is not called in the crash scenario.

In common this method is invoked while loading the VisualState and applying the VisualState to each node:
<img src="https://github.com/user-attachments/assets/071e5303-6984-4690-8945-a16ae0b37b8e" width="600">

Finally I notice in the crash scenario that the VisualState for some reasons doesn't contain any nodes at all, so while applying the VisualState it won't iterate through all nodes and won't set the checked state on any node. So overall the property SelectedTests keeps uninitalized with null.
That's how the VisualState file looks like:
<img src="https://github.com/user-attachments/assets/1f1553b4-a09c-4b80-9fab-8ce8556e78b0" width="600">

Ok, that's not a final explanation for this crash yet. But it feels much better to get a couple of steps closer! :-)

**Comment by rowo360** [comment]
Now I'm finally happy and satisfied, because I managed to identify some use cases for this crash:

1. Use case
- Enable 'Show checkboxes' in the settings
- Load project without a VisualState file
- Press toolbar 'Run selected tests' => crash
2. Use case
- Load project and switch to outcome grouping
- Run all tests and close project 
=> VisualState file contain Node for Passed or Failed for example
<img src="https://github.com/user-attachments/assets/dd15af3d-5749-439c-be90-ca9331e23db5" width="400">

- Restart Testcentric and load project again
- Press toolbar 'Run selected tests' => crash
Here the essential part is that the node 'Passed' or 'Failed' which is described in the VisualState file does not exist when reloading the project! There's only the node 'Not run' at this point in time.
3. Use case
- Load project and switch to some grouping
- Run all tests
=> VisualState file is already created with an empty Nodes collection (see previous comment)
This kind of VisualState file would cause this crash also, if it would be applied when loading a project. But please be aware that this VisualState file is only an intermediate one - in common the VisualState file is written a second time when closing TestCentric or the project. And at this point of time the nodes collection in that file is present. So this intermediate VisualState file would only have an effect, if TestCentric crashes during the test run (for example) - so overall this is an extreme edge case! (But happened to me, because I stopped my debugging session accidently).

**Comment by CharliePoole** [comment]
I like the null object pattern, i.e. let's have an IsEmpty property if we don't already and check it rather than checking for null. Methods that take a TestSelection ought to throw on null.

**Comment by rowo360** [comment]
Issue is fixed with PR #1139 => issue closed
