### ISSUE TITLE
Zero Length VisualState.xml file results in exception

### ISSUE THREAD

**Issue by CharliePoole** [TestCentric/testcentric-gui#115]
To reproduce:

1. Create a dll with tests or use an existing one, such as mock-assembly.dll

2. Create an empty visual state file of the same name, like mock-assembly.VisualState.xml

3. Try to open the file in the GUI.

Expected: GUI should simply ignore the empty file, just as it does for a non-existent file.

For other errors in the XML, the error should be reported but the GUI should not crash.

**Comment by zBrianW** [comment]
my attempt for this is here: https://github.com/TestCentric/testcentric-gui/pull/116

**Comment by AbhiAgarwal192** [comment]
@CharliePoole i dont see the issue happening on my system. 

Here are the steps i tried:-

1) Created a file called mock-assembly.VisualState.xml under mock-assembly tests folder.
2) Executed TestCentric.Gui.Exe and opened my visualstate file on the GUI that popped up.

**Comment by zBrianW** [comment]
👌

**Comment by mikkelbu** [comment]
@zBrianW #117 has now been merged.
