### ISSUE TITLE
Use UpDown counter for number of recent files to display

### ISSUE THREAD

**Issue by CharliePoole** [TestCentric/testcentric-gui#12]
We currently use a text box for this purpose on the GUI settings page.

**Comment by CharliePoole** [comment]
__Hacktoberfest contributors...__

The general GUI settings page contains a textbox for entering the number of entries to display in the recent files menu. It would be better to replace this with an updown counter. This is a pretty simple GUI enhancement.

**Comment by drSte** [comment]
I'd like to contribute on this

**Comment by drSte** [comment]
@CharliePoole I managed to solve the issue, and in the meanwhile i also found a couple of bugs related to the feature ;). I messed up with the branches and the pull request. I will create a new PR as soon as i can

**Comment by CharliePoole** [comment]
This was working before merge but has an error after I merged it. Rather than back out the change, I would prefer to fix the problem.

**Comment by drSte** [comment]
commit c1e6377501389bd299014dad79a5f4831913cb90 shall make the test pass.
It maybe got lost with the squash

Il giorno mar 23 ott 2018 alle ore 22:43 CharliePoole <
notifications@github.com> ha scritto:

**Comment by CharliePoole** [comment]
Build has been fixed.
