### ISSUE TITLE
Double click test to start it

### ISSUE THREAD

**Issue by MartinZec** [TestCentric/testcentric-gui#138]
Hello,

I was using NUnit2 and changed now to NUnit3. As a GUI I use testcentric.

One feature which I miss in testcentric is starting a test by double clicking it. Is this planned for further releases?

Best regards,
Martin

**Comment by CharliePoole** [comment]
Now it is!

**Comment by drSte** [comment]
i will take care of it

**Comment by CharliePoole** [comment]
See if GitHub will allow you to assign the issue to yourself... if not, I will do it.

**Comment by CharliePoole** [comment]
@drSte Were you unable to self-assign this?

**Comment by drSte** [comment]
@CharliePoole no, I am not able to self assign, can you do it for me? Thank you

**Comment by CharliePoole** [comment]
Done. Thanks for checking - I'm trying to understand exactly what GitHub lets people do in various circumstances.
