### ISSUE TITLE
Changing font should affect status bar

### ISSUE THREAD

**Issue by CharliePoole** [TestCentric/testcentric-gui#153]
It does in the NUnit GUI but at the moment not in TestCentric.

**Comment by CharliePoole** [comment]
Sure... but wait till PR #174 merges. There are other changes to master as well, so be sure to pull them down.

**Comment by drSte** [comment]
Is the fix limited to status bar, or it has to be also applied to the menu bar?

**Comment by CharliePoole** [comment]
I kept it limited because I know we can change status bar. Not sure if we can change the menu. I'm in favor of very small changes if possible, however. :smile:

**Comment by CharliePoole** [comment]
PR #174 changing how fonts are set was merged so you can pull it all down now.
