### ISSUE TITLE
Start and stop button are misaligned

### ISSUE THREAD

**Issue by drSte** [TestCentric/testcentric-gui#175]
see attached screenshot

![misalligned_buttons](https://user-images.githubusercontent.com/7127806/49049032-8b2f4f00-f1dd-11e8-8cba-a53a94d65348.png)

**Comment by CharliePoole** [comment]
@drSte Feel free to label things with the standard labels when you create an issue.

**Comment by CharliePoole** [comment]
No longer seeing this. Apparently fixed by a recent commit. Re-open if it reappears.
