### ISSUE TITLE
Reload on Change not working

### ISSUE THREAD

**Issue by CharliePoole** [TestCentric/testcentric-gui#18]
We should set up file watchers and reload the tests if needed. Ideally, only reload the assembly that changed if multiple assemblies are open.

**Comment by CharliePoole** [comment]
__Hacktoberfest contributors...

This is a moderately complex issue. When Reload on Change is set, we should be creating a file watcher for each assembly opened. When a change is detected we should reload the test files.

There is existing code from NUnit V2 that relates to this but it needs to be carefully vetted and updated to work with NUnit 3. There's enough work here that you may want to consider doing it in several PRs.

**Comment by drSte** [comment]
i will try to fix this

**Comment by drSte** [comment]
@CharliePoole it is ok if i use a FileSystemWatcher object?

**Comment by CharliePoole** [comment]
You will want to look at how NUnit V2 does it, since we are basically emulating the V2 GUI for TestCentric 1.0.Basically, there are two classes that watch files for changes:

`FileWatcher` is used to watch for changes in a single project file. I don't think we need this right away since our support of project files is limited right now.

`AssemblyWatcher` looks for changes to the name of any assemblies being tested. It uses a collection of `FileSystemWatchers` to do it. That's the one you need - or something equivalent.

I think I'd do this in two stages....

1. Get AssemblyWatcher ported and working. It has tests, so that will be of some help. I think it belongs in the model.

2. Possibly as a separate PR, get it hooked up and working. If the user wants reload on change, then we have to set up the watchers and when they are triggered, we do our job. You'll find some commented out code where it was used in the original code I ported.

Good luck! Be sure to ask questions if you need to.

**Comment by CharliePoole** [comment]
@drSte Our comments crossed. Take a look at what AssemblyWatcher does. I think you will find that it's a lot more complicated than just a FileSystemWatcher for two reasons...

1. It has to watch a bunch of assemblies, whcih may be in various locations.

2. The assemblies change as you compile, first one, then another, etc. So we have to set up timers in order to avoid reloading before all the changes are complete.

**Comment by CharliePoole** [comment]
BTW, right now, we reload everythng when anything changes. A future enhancement might be to only reload affected assemblies.

**Comment by drSte** [comment]
@CharliePoole ,I am ready with the implementation, Will push it as soon as the previous PR will be accepted
