### ISSUE TITLE
Not building Mono 5.10 or 4.6 under Travis

### ISSUE THREAD

**Issue by CharliePoole** [TestCentric/testcentric-gui#185]
The Mono Latest job runs successfully but the other two fail with "Field 'System.Net.ExceptionHelper.WebPermissionUnrestricted' not found."

Initially, this appeared to be a Travis problem but the experimental GUI is not encountering it. The standard GUI apparently has a reference somewhere that is causing the issue.

**Comment by CharliePoole** [comment]
It looks like the problem started when Cake 0.31 was first used. The experimental gui is still pegged to use Cake 0.19.1 so it has not had the problem.

**Comment by mikkelbu** [comment]
I came to the same conclusion :). We could try to add something like https://github.com/TestCentric/testcentric-experimental-gui/blob/master/tools/packages.config#L3 in this repo and see if it solves the problem.

**Comment by CharliePoole** [comment]
Yes, the experimental GUI has packages.config in the repo but the standard GUI doesn't. That means we get whatever is the latest release without notice.

The downside of pegging it to a release is that you don't always remember to upgrade, but I think that's a risk worth taking.

The builds were working with 0.30, so I'll try pegging it at that version.

**Comment by CharliePoole** [comment]
That did it!

**Comment by gep13** [comment]
>@CharliePoole said...
The builds were working with 0.30, so I'll try pegging it at that version.

This is definitely what we recommend.  While we "try" not to introduce breaking changes in Cake, they do happen, and we have always recommended that builds are pinned to a specific version of Cake, and also specific versions of addins/tools/modules that are being used.  That way, a build that worked yesterday, is much more likely to continue working in the future.

Thanks for letting us know about this issue though, we will look into it.

**Comment by gep13** [comment]
@CharliePoole if you haven't already, I would recommend pinning the other build to 0.30.0 as well.  After NuGet introduced repository package signing, resolving NuGet packages would take a VERY long time in earlier versions of Cake.  We have corrected this issue in Cake 0.30.0, and this is what I would recommend is used.

**Comment by CharliePoole** [comment]
Agree 100% Not sure how this particular project ended up with a floating cake version - it definitely wasn't the intent.

**Comment by CharliePoole** [comment]
Yup. That'll be my next step.

**Comment by CharliePoole** [comment]
Of course, the downside of pinning versions is that they may stay pinned for too long and too far back. You have to keep an eye on the tools.

**Comment by gep13** [comment]
>@CharliePoole said...
Of course, the downside of pinning versions is that they may stay pinned for too long and too far back. You have to keep an eye on the tools.

Yes, that is true.  We do a blog post announcement with each release: https://cakebuild.net/blog/Release-Notes/ and all releases are documented on the GitHub Repo https://github.com/cake-build/cake/releases, as well as sending tweets and messages to Gitter.  In addition, we send out information to LinkedIn, Reddit, and Medium.  So we like to think we are covering most bases when it comes to letting people know.  If there is another communication route that we can add to, definitely let us know.

**Comment by CharliePoole** [comment]
I think you guys put out enough info. It's just a general problem with any project to track all the tools and __decide__ when to upgrade. Not to mention any frameworks your application links with! And, of course, adding features always gets the most attention.

It's just something that has to be dealt with in each individual project. :smile:
