### ISSUE TITLE
Project file watcher remains active even during closing.

### ISSUE THREAD

**Issue by elbaloo** [TestCentric/testcentric-gui#207]
If during closing the runner, there were changes to the project, the runner prompts for confirmation to save the changes which is ok, but after confirming, the watcher catches this change and prompts the user to reload the project even when the runner is closing.

**Comment by CharliePoole** [comment]
This issue was created for the NUnit V2 GUI in 2014 and was retained to ensure did not occur in the TestCentric GUI. It has never appeared and is now being closed.
