### ISSUE TITLE
Errors and Failures' Source Code Context highlights the wrong line while throwing exceptions.

### ISSUE THREAD

**Issue by elbaloo** [TestCentric/testcentric-gui#208]
Scenario:
Within a simple method there is more than one exception being thrown.
Method skips first exception throwing (meaning it's never thrown) but then throws another one (meaning a different exception) which happens to be the second in line.
Then execution halts and source code context highlights the first exception (that was never thrown) instead of the second one which was thrown.

``` csharp
void SomeMethod(bool someBool)
{
  if(someBool)
  {
    throw new Exception("im the 1st"); // I will be highlighted
  }
  else
  {
    throw new Exception("im the 2nd"); // I should be highlighted
  }
}

// Calling this.
SomeMethod(false);
```

**Comment by CharliePoole** [comment]
This issue was created for the NUnit V2 GUI in 2014 and was retained to ensure did not occur in the TestCentric GUI. It has never appeared and is now being closed.
