### ISSUE TITLE
GUI buttons Run and Stop get deactivated when tests stopped during execution and message box closed really fast

### ISSUE THREAD

**Issue by amsGeorg** [TestCentric/testcentric-gui#209]
NUnit 2.6.2 GUI has the problem of deactivating the Run and Stop buttons. When you press the Runbutton, and immediately afterwards stop the test run by pressing the Stop button and accepting the abortion of the testrun in the message box. Pressing the stop button is done with the mouse, while the message box is closed with the return key on the keyboard.

After this abortion both buttons are disabled and there is no possibility to start a complete testrun again, except when a test from the tree view on the left is selected, right clicked and run from the popup menu. This also reactivates the right buttons (Stop button is then activated again)

**Comment by CharliePoole** [comment]
This issue was created for the NUnit 2.6.2 GUI in 2014 and was retained to ensure did not occur in the TestCentric GUI. It has never appeared and is now being closed.
