### ISSUE TITLE
Appveyor build doesn't use generated identifier to tag packages

### ISSUE THREAD

**Issue by ChrisMaddock** [TestCentric/testcentric-gui#224]
@CharliePoole spotted this in nunit/nunit-project-editor#16 - which I'd based off the cake script here. 

The package names are built in a local variable at the start of the script, before the `packageVersion` var is modified in `InitializeBuild`. This then isn't reflected in the package names.

**Comment by CharliePoole** [comment]
@ChrisMaddock Looking at the script, this seems to have been fixed a long time back, but without closing this issue. If you think there's something more to do, we can re-open.
