### ISSUE TITLE
Display progress as text

### ISSUE THREAD

**Issue by amoiceanu** [TestCentric/testcentric-gui#227]
Currently, the progress bar is too small and also the progress is not displayed as text, so it's very hard to figure out how much of selected tests have been runned.

Probably would be best that if the progress bar will be adjusted to the whole width of the GUI, and somewhere below, the progress will be displayed as percent(e.g 41%).

![progress](https://cloud.githubusercontent.com/assets/22083246/18670017/5e466ce6-7f46-11e6-9894-38a35053ba07.png)

**Comment by CharliePoole** [comment]
Decision after reviewing this old issue: For the 2.0 GUI, the progress bar will remain where it is but will be enhanced to display number of tests run out of total.

**Comment by CharliePoole** [comment]
It seems about time to deal with this!

**Comment by CharliePoole** [comment]
Following the principle of doing "the simplest thing that can possibly work," I selected one format (percentage) and implemented it in our custom control. I added a property to turn the display on or off but haven't made it user accessible at this point. Seems like it will do no harm even if somebody doesn't need it.
