### ISSUE TITLE
Decide whether to use checkboxes or ctrl/shift to enable multi-selection in tree

### ISSUE THREAD

**Issue by amoiceanu** [TestCentric/testcentric-gui#228]
There are some situations when we need to run only specific tests from a suite, so we need to select only some of them(and not the entire suite).
A workaround for this is to use checkboxes, to specify which tests to run, but would be easier if multi-select will be enabled while holding Ctrl key.

**Comment by CharliePoole** [comment]
This is working well with checkboxes, so I've decided to keep it that way. Closing without further action.
