### ISSUE TITLE
Experimental GUI: missing test output

### ISSUE THREAD

**Issue by Trass3r** [TestCentric/testcentric-gui#236]
```cs
using System;
using NUnit.Framework;

[TestFixture]
public sealed class Test
{
	[OneTimeSetUp]
	public void FixtureSetup()
	{
		Console.WriteLine("f1");
		TestContext.Progress.WriteLine("f2");
		TestContext.Error.WriteLine("f3");
	}

	[TearDown]
	public void TearDown()
	{
		Console.WriteLine("T1");
		TestContext.Progress.WriteLine("T2");
		TestContext.Error.WriteLine("T3");
	}

	[Test]
	public void Output()
	{
		Console.WriteLine("1");
		TestContext.Progress.WriteLine("2");
		TestContext.Error.WriteLine("3");
	}
}
```

Only the console variant is output. R# gives all of them.

**Comment by CharliePoole** [comment]
It seems we need a test output tab as in the standard GUI. We already have all the code for this, just not in the experimental GUI. I'd prefer to get the beta out before adding significant work to the experimental GUI. Moving this to the 1.0 milestone so we can try to share the existing code after the beta but before the final release. If it can't be done easily, I'll postpone again, till after the 1.0 release.
