### ISSUE TITLE
Categories on test fixtures not considered in test list

### ISSUE THREAD

**Issue by chm-tm** [TestCentric/testcentric-gui#238]
I use the `CategoryAttribute` on individual test cases. When all test cases of a test fixture belong to a specific category, I place the `CategoryAttribute` right on the test fixture.
I expect this to be functionally equivalent as if I had marked each test case, when dealing with test cases.

However, in the test list view, when grouping by categories, categories defined by means of the test fixtures are not considered.

The following code:
```C#
[Category("a")]
public class A
{
    [Test]
    public void A1() {
    }

    [Test]
    public void A2()
    {
    }
}

public class B
{
    [Test]
    [Category("a")]
    public void B1()
    {
    }

    [Test]
    [Category("a")]
    public void B2()
    {
    }
}
```
produces this grouping: 
![this](https://cloud.githubusercontent.com/assets/8878006/25661378/a2467546-3010-11e7-943d-e237d1d5d90e.png)

I'd expect A1 and A2 to appear under the category `a`.

I should be able to make a PR for this.

**Comment by CharliePoole** [comment]
@chm-tm Thanks for your work! Sorry this took so long.

As noted on the PR, the GUI now has a separate option for "By Category (Extended)". This needs some further explanation if we keep it, but I suspect that the GUI will change in this area before he final release of 1.0.
