### ISSUE TITLE
Experimental GUI: Load tests on background

### ISSUE THREAD

**Issue by ParanoikCZE** [TestCentric/testcentric-gui#240]
Seems like tests library is being loaded directly in UI thread. Loading bigger test suite causes it to not responding to commands and eventually into not responding state.
I can imagine that tests list will be updated as data comes with some progress info if possible.

**Comment by CharliePoole** [comment]
I'm not able to either confirm or convincingly disprove this issue using the current code... at least not in time for the release. Moving to post-1.0 milestone.

**Comment by mikkelbu** [comment]
Just for fun I tried to create a TestFixture containing 50K tests using T4 (inspired by this [document](https://docs.microsoft.com/en-us/visualstudio/modeling/design-time-code-generation-by-using-t4-text-templates?view=vs-2019#creating-a-design-time-t4-text-template)) and that loads in approx. 5 seconds on my old laptop. This is of course a very contrived as there are no TestCase(sources) ect. to affect the load time.

```code
<#@ template debug="false" hostspecific="false" language="C#" #>
<#@ output extension=".cs" #>
using NUnit.Framework;

[TestFixture]
class MyGeneratedClass {
<# // This code runs in the text template:
  for (int i = 0; i < 50000; i++){ #>
  
  [Test]
  public void Test<#= i #>() { }
<# } #>
}
```
which generates 
```csharp
using NUnit.Framework;

[TestFixture]
class MyGeneratedClass {
  
  [Test]
  public void Test0() { }
  
  [Test]
  public void Test1() { }
...
  [Test]
  public void Test49998() { }
  
  [Test]
  public void Test49999() { }
}
```

**Comment by CharliePoole** [comment]
We'd need to put the delay in the TestCaseSource entries, I suppose.

**Comment by CharliePoole** [comment]
We haven't ever been able to repro this and the code has moved on substantially from where it was when this was reported. Nobody else has reported the same. I'm closing this as norepro. Of course, if it comes up again for anyone, we'll look at it.
