### ISSUE TITLE
TestContext.CurrentContext.TestDirectory makes GUI crash/not load

### ISSUE THREAD

**Issue by wanted156** [TestCentric/testcentric-gui#243]
We have a test bench with a ton of tests and adding the above mentioned function into the code (so it reads from the right config file) makes the GUI crash / not load at all. Without that function the config is not detected in the right path and therefore gives tests errors, but it loads the GUI up perfectly.

**Comment by CharliePoole** [comment]
This was reported originally against the experimental GUI, which no longer exists, so closing without action.
