### ISSUE TITLE
nunit-agent.exe does not clean memory and uses more and more over test runs

### ISSUE THREAD

**Issue by arphox** [TestCentric/testcentric-gui#246]
Hello!

Today I used the nUnit GUI to run our production code's tests.
1. I opened the DLL which contains the tests
2. I ran all of the tests multiple times (~3-4)

And after this I noticed that the **nunit-agent.exe** process eats more and more memory, depending on the number of "test batch" repetitions.

Now the application is only usable for me if I restart the whole GUI+agent processes before each test batch run, otherwise GB's of memory will be used. (One test batch contains over 300 tests using SimpleInjector, AutoMapper and complex object structures)

I recommend a quick fix for this: before each test run, restart the nunit-agent.exe process, so this won't be the case.

**Comment by CharliePoole** [comment]
This issue has not been seen for a long time and I believe it was fixed in the redesign of the engine. Closing but will reopen if somebody comes up with a current, reproducible test case using the testcentric-agent.
