### ISSUE TITLE
Clear Results Setting is on wrong page

### ISSUE THREAD

**Issue by CharliePoole** [TestCentric/testcentric-gui#26]
The setting for Clearing results when reloading is on the tree settings page but affects more than just the tree. It probably belongs on the reload page.

**Comment by CharliePoole** [comment]
Or maybe general GUI?

**Comment by CharliePoole** [comment]
@TestCentric/gui-team Looking for feedback on where this setting should be!

**Comment by mikkelbu** [comment]
> The setting for Clearing results when reloading is on the tree settings page but affects more than just the tree. It probably belongs on the reload page.

If "reload page" means the page denoted by "Assembly Reload" then I think it is fine, but it is not something that I feel strongly about.

**Comment by CharliePoole** [comment]
I got tired of seeing this in the wrong place, so I'm fixing it now.
