### ISSUE TITLE
Older framework support

### ISSUE THREAD

**Issue by NN---** [TestCentric/testcentric-gui#268]
You can use Theraot.Core and easily support order frameworks

https://github.com/theraot/Theraot

**Comment by NN---** [comment]
AFAIU it won't work 100% as expected:
```Because TestCentric runs under .NET 4.5 or higher, any tests that you cause to execute in-process will run under that version of the frameowrk. In some cases, this may give variable results. By default, tests are run out-of-process.```

**Comment by CharliePoole** [comment]
The idea is that you shouldn't do that as a user. :smile: If you select to run inprocess and it's not possible (for example, tests target .NET Core) then you get an error message. If you select to run inprocess and it's possible but might give different results, we do it, based on the old NUnit principle of doing what the user tells us to do. 

Of course, we __could__ give a warning message, but that would require some user input. In the past (with NUnit that is) we had a lot of discussion about this and it seemed the best action is to run without warning. I suppose it depends on what level of knowledge you assume your user base has.

BTW, although it's now possible to create a default setting to run in process, I"m thinking of removing that capability and simply making it a setting you select from the menu as I did in the experimental GUI. That may mitigate the problem.

Of course, this is alpha-level software, so not everything is yet implemented.

**Comment by CharliePoole** [comment]
Closing this as there seems to be no action to take right now. If you have questions or comments, you can still post here and we will see it and respond.
