### ISSUE TITLE
How should we distinguish issues on the experimental GUI?

### ISSUE THREAD

**Issue by CharliePoole** [TestCentric/testcentric-gui#283]
I'm making this a question to ask ourselves.

Some similar-sounding issues may be for the standard GUI or the experimental GUI. Right now, I have an `experimental` label on those that impact the experimental GUI, but I'm not sure that's useful given that there are so many of them.

One approach would be to use a milestone. Another would be to create an experimental GUI project. Maybe you guys can think of other ideas.

**Comment by immeraufdemhund** [comment]
At work we'd probably use something similar to a milestone so that feels like a natural answer for me.

**Comment by CharliePoole** [comment]
I could set up an "Experimental" milestone and then as each release milestone comes along just move those done items into it.

**Comment by CharliePoole** [comment]
I went ahead and created the Experimental milestone. Closing this.
