### ISSUE TITLE
NUnit Agent locks dll

### ISSUE THREAD

**Issue by MartinZec** [TestCentric/testcentric-gui#285]
Introduced from alpha2 to alpha3:
When Testcentric is running, I cannot recompile my MY_TEST.sln in VS2017.

I get following error message:

Could not copy "PATH_TO_MY_FRAMEWORK\bin\Debug\MY_FRWK_DLL.dll" to "bin\Debug\MY_FRWK_DLL.dll". Exceeded retry count of 10. Failed. The file is locked by: "NUnit Agent (14736)"		

Unable to copy file "PATH_TO_MY_FRAMEWORK\bin\Debug\MY_FRWK_DLL.dll" to "bin\Debug\MY_FRWK_DLL.dll". The process cannot access the file 'bin\Debug\MY_FRWK_DLL.dll' because it is being used by another process.

The disable shadow copy option is disabled.

**Comment by CharliePoole** [comment]
@MartinZec Just to confirm: this is a an assembly with your tests, not the tests of testcentric itself, right?

**Comment by arulvenkatesh** [comment]
Hi @CharliePoole ,
This issues pops up again with testcentric-gui-1.0-alpha3. I didnt see this issue with testcentric-gui-1.0-alpha2. Any idea about it?

Thanks
Arul

**Comment by CharliePoole** [comment]
@arulvenkatesh The issue was reported on alpha3, fixed for the beta.

**Comment by arulvenkatesh** [comment]
Sorry mate I completely missed out to read that piece of information from the description.
