### ISSUE TITLE
Choosing "Run as X86" from menu doesn't actually load the X86 agent.

### ISSUE THREAD

**Issue by JeffKryzer** [TestCentric/testcentric-gui#299]
1.  Run testcentric.exe.
2.  Load a test assembly.
3.  Open Task Manager and look at processes.  You will notice **nunit-agent.exe** in the list.
4.  Choose File --> Process Model --> Run as X86
5.  You are prompted to reload.  Click Yes.
6.  Look in Task Manager again.  **nunit-agent.exe** is still in the list, rather than nunit-agent-x86.exe.

In addition, running a test assembly which requires 32-bit will fail, confirming that it is still running in a 64-bit process.

**Comment by CharliePoole** [comment]
I'm wondering if we even want the dialog that asks if you want to reload. Why would you say no?

**Comment by JeffKryzer** [comment]
I agree.  But the prompt is in the generic ChangePackageSetting method which is used for changing all settings.  Suggestions?  Pass in a bool like changeRequiresPrompt (forcing the caller to be in charge)?  Or hard code a list of settings which can skip the prompt?  Or just leave it.  You could argue the prompt gives validation that it is being reloaded.  You could remove the Yes/No and just change it to an OK button.

**Comment by CharliePoole** [comment]
It does get complicated! I'll look more closely in the morning.

**Comment by CharliePoole** [comment]
@JeffKryzer Can you confirm that  loading a test assembly that is compiled to target X86 runs the X86 agent even if the menu is not checked? That's what is supposed to happen. If it isn't working, that's an even more serious error.

The X86 option actually means __force__ it to run as X86.

**Comment by CharliePoole** [comment]
Upon review, I see that the ChangePackageSettings method is private and only used for changes to framework, process model, domain usage and runasx86. I think we can reload in all those cases.

Method name could be changed to ChangePackageSettingsAndReload for clarity.
