### ISSUE TITLE
Feature:  Make "Run as X86" persist between gui launches

### ISSUE THREAD

**Issue by JeffKryzer** [TestCentric/testcentric-gui#302]
For a user who always wants to test their assemblies using X86, it is quite annoying to have to change to X86 every time after launching the gui.

I don't think it needs to be in the Settings dialog, just needs to keep track of the last menu choice.

**Comment by CharliePoole** [comment]
It seems to me that this should be a per-project setting, not a global setting. Currently, we don't have a way to do that, of course, but maybe that's what we should be working towards. Somebody who __always__ wants to run tests using X86 is presumably doing that because they only work on stuff that needs X86. It's associated with the assembly's needs, not a user preference.

**Comment by CharliePoole** [comment]
@TestCentric/gui-team I'd appreciate your thoughts on what we should do about this. See my comment above.

I should add that the setting should __not__ be necessary if the test itself requires X86. In that case, it will be run that way by default. However, the GUI display makes it appear as if it will not.

**Comment by CharliePoole** [comment]
@mikkelbu @immeraufdemhund What do you guys think?

My own take: 

 * This should __not__ be a global setting. If I have one assembly that requires X86 and another that doesn't, and I work on them alternately, I would have to change it every time I switched projects. Current assumption is that X86 is the exceptional situation and that seems to be working for the console runner.

* If the __test assembly__ targets X86, no setting should be needed. We ought to at least verify that this is working, of course. Forcing use of X86 should only be needed when some library called by a test that is __not__ X86, requires X86. I'm not clear why you wouldn't just make the test X86 in the first place, however, we have an escape option in the console runner so it's probably good to have one here.

* It could be that the "Run as X86" checkbox item is misleading. That is, it looks as if __not__ checking it makes things run as 64 bits. That's not actually what happens. The switch is really between "let NUnit decide" and "Force use of X86." Maybe we should change the UI to reflect this better.

* The V2 GUI had an Assembly Info menu item, which displayed important information about each assembly loaded. Maybe we need to bring that back for this GUI.

**Comment by immeraufdemhund** [comment]
I agree that it needs to be per project. I had one project that had 3 assemblies that were x86 and 2 that were any cpu. Maybe a marker in the test tree that it is x86?

**Comment by CharliePoole** [comment]
@immeraufdemhund Bear in mind that using the default process-per-assembly execution, your X86 assemblies should all run as X86. If you force them everything to run in one process, then they should all end up as X86, which may or may not work. 

If you had non-x86-target projects which must be run as X86 for reasons of dependencies, that's when we would need a setting. As you point out, it should be per-assembly.

Right now, I guess the key to this is to make sure that the default of running x86 targeted assemblies as x86 is working correctly in the GUI.

**Comment by immeraufdemhund** [comment]
yeah I remember having to force things into x86 as otherwise pinvoke calls woudln't work or getting registry values.. etc etc. it's been a long time though.

**Comment by mikkelbu** [comment]
I much agree with https://github.com/TestCentric/testcentric-gui/issues/302#issuecomment-477923037, so I just answered with a 👍.

**Comment by CharliePoole** [comment]
Keeping this open till we decide what exactly needs to be done. Post 1.0, however.

**Comment by CharliePoole** [comment]
In some recent issues, we decided not to do this. Instead, there is a command-line option `-x86`. Anyone who wants to always run tests in x86 mode can set up a shortcut with that option specified.
