### ISSUE TITLE
Reorganize Settings

### ISSUE THREAD

**Issue by CharliePoole** [TestCentric/testcentric-gui#315]
In reviewing issues #232 and #233, a general problem became evident: the TestCentric GUI uses different settings keys and values from the Experimental GUI.

The problem is exacerbated because the settings used by the TestCentric GUI are hosted by the TestModel, while those used for the Experimental GUI are local to that assembly. In a few cases, the model itself is looking at it's own setting rather than the one that is set by the Experimental GUI. ReloadOnRun is one such case, for example.

Ideally, all the settings that belong to a particular GUI should be private to that GUI. So, for example, the TestCentric GUI might use `UserSettings.TestCentric` and the Experimental GUI `UserSettings.Experimental.

Settings pertaining to the engine itself are a different matter. In some cases, we may want them to always be the same but in other cases users may prefer different settings when using different runners. Most likely, the easiest way to provide for both cases will be to have separate settings per GUI, even for engine-related options, and allow the user to set both of them to the same value if that's what is desired.

This is potentially a blocking issue for #232 and #233. I'll do some investigation to see whether it's reasonable to change how settings are organized prior to the 1.0 release. For now, I'm putting this into the 1.0-Beta milestone.

**Comment by CharliePoole** [comment]
Upon review, there's even more to this. The two GUIs actually need an entirely separate set of settings, each set using a different prefix. Those settings need to be defined in the code for each GUI, that is in the`Testcentri.Gui` and `Experimental.Gui` projects. The TestModel really shouldn't know about them and each GUI should communicate what it wants done from the presenter by use of commands to the model and `TestPackage` settings.

That's the way the Experimental GUI currently works but the TestCentric GUI uses settings that are defined in the model itself. In a small number of cases, the model uses those settings directly and that needs to be changed to make the model compatible with both GUIs. This is something I missed when the experimental GUI code was merged into this repository.

This being a fairly large job, I'm postponing this issue until after the 1.0 release. Issues #232 and #233 will be resolved, if possible, using workarounds.

**Comment by CharliePoole** [comment]
Thoughts on design of persistent settings...

1. Runners should save and retrieve settings, passing instructions to the engine. Engine should not be aware of specific persistent settings.

2. Currently, the engine provides the underlying implementation of settings, which means that all runners use the same implementation, an XML file. But in the future, different runners may not want to use that implementation. They should be free to use their own.

3. With item 2 in mind, our eventual goal should be to remove the SettingsService from the engine. In the shorter term, we can keep it provided we eliminate all use of the SettingsService from other parts of the engine.

4. Since the RecentFilesService depends on SettingsService, it will need to be removed from the engine as well. Different runners that use the service will need to implement it themselves, either independently or based on Settings as is now done.

5. Within the two GUIs, which use the MVP architecture, the SettingsService needs to be implemented by the model. That's because presenters need to react to settings changes and refer to individual settings. The model is the only component that is shared by all presenters.

6. OTOH, the model should generally __not__ act directly on any of the settings. Like the engine, it should not be aware of what specific settings are in use by the runners. This allows the model to be reused for multiple runners, including the two that are now supported. All communication with the model should be via it's properties or the settings in the TestPackage.

7. For each runner, the model may need to be initialized with a prefix and/or file name for use in storing the settings. This can be done either by the main presenter or in the main entry point.

@mikkelbu @immeraufdemhund Do the above principles make sense to you?

**Comment by immeraufdemhund** [comment]
1. agreed. I personally like the way git handles settings and how it is all shared. For instance with git itself you can configure global in your user profile, or you can configure the individual repo itself. And if you use their built in gui tool (gitk or git gui) they have their own settings files stashed away somewhere. Having a well known save location for the engine settings that can be easily overridden on a per project basis sounds nice to me.
1. agreed
1. ok
1. ok
1. makes sense
1. yeah I wouldn't want the model affecting things just showing what is configured.
1. makes sense

sorry it's not much in terms of meat when replying. sounds like a well thought out approach though
