### ISSUE TITLE
Deploy development builds automatically

### ISSUE THREAD

**Issue by CharliePoole** [TestCentric/testcentric-gui#325]
This could either use the same approach as nunit / nunit-console or be based on versioning provided through GitVersion.

**Comment by CharliePoole** [comment]
@TestCentric/gui-team I'm strongly leaning toward going with GitVersion moving forward.

Key benefits I see...
 * All builds, local and CI, building to the same version and package names
 * Repeatability of the builds
 * Elimination of need to do a separate code update in order to release... i.e. we could just release the code we already tested. (This assumes change log is kept up to date, of course)

Approach...
 * Easiest approach will be if we use semver version format for everything, since that's what GitVersion does.
 * We may need to go with naming branches with a `feature/` prefix to get there. At least so far I have not been able to adequately control what GitVersion does when the branch is simply "name-of-feature". Ideas anyone?
 * If we can't solve the previous point, then we can use code (as we now do) in build.cake to generate the versions. Right now I'm trying to see what GitVersion can do unassisted.

I've played with this before but haven't used it in a production system. Has anyone else?

**Comment by immeraufdemhund** [comment]
nope, but the less that we have to do manually the better. I hope someone has figured this out

**Comment by CharliePoole** [comment]
Here is the (tentative) package versioning I am aiming for versus the current versioning, which was taken from the NUnit project...

Branch | Current | Proposed
--------  | ---------- | ------------
master | 1.1.0-dev-AAAAA | 1.0.1-devNNNNN
feature | 1.1.0-ci-AAAAA-BRANCH | 1.0.1-ciNNNNN-BRANCH
pull request | 1.1.0-ci-AAAAA-pr-PPPPP | 1.0.1-prPPPPP-MMMMM

Where...
 * BRANCH is the branch name
 * AAAAA is the Appveyor job number
 * NNNNN is the pre-release number calculated by GitVersion
 * PPPPP is the PR number

The general idea is that all produced versions are pre-releases unless we tag them or use a branch name with a version in it.

I'll do multiple PRs against this issue so we can see how well it works on the PRs themselves and when the code is merged. This may disrupt some of our sequences in MyGet, but I can clean up by deleting things that are incorrectly numbered.

Strongly requesting any suggestions!!!

**Comment by CharliePoole** [comment]
Tasks...

 - [x] Get versioning working as we want for feature branches, PRs and master. (PR #384, merged but needs review of the formats)
 - [ ] Publish dev builds of master to MyGet
 - [ ] Set up release builds and tagging
 - [ ] Manually release builds built in CI rather than locally
 - [ ] Programmatically release builds built in CI

**Comment by CharliePoole** [comment]
First automatically created build is now deployed to MyGet as version 1.0.1-dev00005.

@immeraufdemhund @mikkelbu If one of you could give the download a try that wouold be helpful.

**Comment by immeraufdemhund** [comment]
I've tried both `TestCentric/testcentric-gui` and `testcentric-gui` and both of them say not found

```bash
$ ./tools/nuget.exe install -ExcludeVersion -OutputDirectory './tools/' testcentric-gui
Feeds used:
  https://www.myget.org/F/testcentric/api/v2/
  https://www.myget.org/F/testcentric/api/v3/index.json
  https://api.nuget.org/v3/index.json
  https://api.nuget.org/v3/index.json
  https://www.myget.org/F/nunit/api/v3/index.json
  C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\

Installing package 'testcentric-gui' to './tools/'.
  GET https://api.nuget.org/v3/registration3-gz-semver2/testcentric-gui/index.json
  GET https://www.myget.org/F/nunit/api/v3/registration1/testcentric-gui/index.json
  GET https://www.myget.org/F/testcentric/api/v3/registration1/testcentric-gui/index.json
  NotFound https://api.nuget.org/v3/registration3-gz-semver2/testcentric-gui/index.json 116ms
  GET https://api.nuget.org/v3/registration3-gz-semver2/testcentric-gui/index.json
  NotFound https://api.nuget.org/v3/registration3-gz-semver2/testcentric-gui/index.json 34ms
  GET https://www.myget.org/F/testcentric/api/v2/FindPackagesById()?id='testcentric-gui'&semVerLevel=2.0.0
  OK https://www.myget.org/F/testcentric/api/v3/registration1/testcentric-gui/index.json 569ms
  NotFound https://www.myget.org/F/nunit/api/v3/registration1/testcentric-gui/index.json 596ms
  OK https://www.myget.org/F/testcentric/api/v2/FindPackagesById()?id='testcentric-gui'&semVerLevel=2.0.0 252ms
Unable to find package 'testcentric-gui'
```

**Comment by CharliePoole** [comment]
Sorry... it's a chocolatey install, not night. I'm on my phone so this is from memory...

1. Run command-line as administrator.

2. Download the file to current directory. 

3. choco install testcentric-gui -s . 

Now that I think of it, it would be easier if I published it as a pre-release on chocolatey.

**Comment by immeraufdemhund** [comment]
I was able to install straight from chocolatey without specifying a source.... I don't think i have the right build though
![image](https://user-images.githubusercontent.com/3466221/62879598-7823c700-bcf9-11e9-986e-88b9fe2d8e16.png)

**Comment by CharliePoole** [comment]
Yes, that's the 1.0 release. The package on myget is 1.0.1-dev00005. I wonder if choco can install from myget.

**Comment by CharliePoole** [comment]
OK, new instructions for installing chocolatey build from myget. The instructions for a local install in my earlier comment are still valid, but unnecessarily complicated once the build is on myget.

1. Run Command Prompt as administrator

2. If you have an old install of testcentric-gui run `choco uninstall testcentric-gui`. (You can also use `--force` when installing, but I find it cleaner to just uninstall.)

3. Run `choco install testcentric-gui --pre -s http://www.myget.org/F/testcentric`

You can now run either `testcentric` or `tc-next` from the command-line in any directory.

**Comment by mikkelbu** [comment]
I've just successfully installed from myget and used `testcentric` and `tc-next`

**Comment by CharliePoole** [comment]
@mikkelbu Thanks for the review. 

I'm thinking about the whole business of dev releases on myget as being possibly overkill. What if, instead of doing that, we just uploaded to chocolatey with the -dev suffix? Anyone wanting pre-releases could then get them. So, for example, on chocolatey you might find

    1.0.0
    1.0.1-dev-xxxxx
    1.0.1-dev-yyyyy
    1.0.1  // Final release with hotfix
    1.0.2-dev-zzzzz
    1.1.0-rc // If we do rc releases
    1.1.0 // Next feature release

Note that in the above, there is never a 1.0.2 release, because there was no critical issue to trigger it, but that's OK because it's all in the same order.

I'm actually thinking of no longer doing alphas and betas but just releasing continuously.

**Comment by CharliePoole** [comment]
Removing tasks that go beyond deploying dev builds so as to close this and include it in the 1.0.1 release.
