### ISSUE TITLE
In TestCentric gui, Selected Categories are cleared on Reload

### ISSUE THREAD

**Issue by JeffKryzer** [TestCentric/testcentric-gui#336]
1.  Load a test assembly which has Categories into the TestCentric gui.
2.  Select a Category so it appears in the Selected Categories list below.
3.  Choose File --> Reload Tests.
4.  Selected Category is cleared.

This behavior did not happen in nunit_gui 2.x.

**Comment by CharliePoole** [comment]
Confirmed this. Seems to be a side effect of the fact that we simulate reload using unload and load.
