### ISSUE TITLE
TestCentric treeview selection is lost when test assembly is recompiled

### ISSUE THREAD

**Issue by JeffKryzer** [TestCentric/testcentric-gui#338]
1.  Load a test assembly with a couple classes/tests.
2.  Choose one test out of the treeview to run (not using checkboxes in the treeview).
3.  Now recompile the assembly you had loaded.
4.  TestCentric gives you the "Reloading" popup, then when it goes away, the top node of the treeview is selected, rather than the test you had previously selected.

Note.  If you select File --> Reload Tests, it properly keeps your treeview selection.  It only loses the selection if you recompile/replace the assembly.

**Comment by CharliePoole** [comment]
Verified that this is no longer the case in the current build. Other  changes related to reload seem to have fixed it. If you continue to see it in the next beta, we can reopen.
