### ISSUE TITLE
Installed Extensions fields not cleared

### ISSUE THREAD

**Issue by CharliePoole** [TestCentric/testcentric-gui#350]
When no installed extensions are shown for an extension point, the extensions dialog should clear the Description and Properties fields.

**Comment by jaywha** [comment]
@CharliePoole Although not labeled as an easy fix, I could give this a shot this weekend.  

Planned Flow:
- [ ] :package: Fork Repo & Verify Vanilla Build :package: 
- [ ] :hammer_and_wrench:  Branch to Feat-ClearExtensionFields & Implement Fix :hammer_and_wrench: 
- [ ] :confetti_ball:  Do Pull Request :confetti_ball:

**Comment by CharliePoole** [comment]
Glad to have you do it. Should be an easy one in fact.

**Comment by CharliePoole** [comment]
We haven't heard from @jaywha since @immeraufdemhund reviewed the code. I'm going to pull it down and fix the formatting issues in a separate branch and PR.
