### ISSUE TITLE
Incorporate NUnit Engine as a subtree

### ISSUE THREAD

**Issue by CharliePoole** [TestCentric/testcentric-gui#352]
It's really very hard to debug engine problems as they affect the GUI while using a released engine package. As a first step, I'll use git-subtree to pull the source code into the testcentric repo and build engine, engine.api and the agents. That way, I can step through the engine calls in debug more easily.

This, of course, is exactly how console runner development works!

High priority because there are three other issues that require debugging the engine.

**Comment by immeraufdemhund** [comment]
Wish I would have had access to my computer over the weekend. I've never used subtree before as I'm used to submodules. Any particular reason we used subtree over submodule?

**Comment by CharliePoole** [comment]
@immeraufdemhund Just noticed I hadn't answered you. 

I never used either of them, so I researched the options without any preference to one or the other. Subtree sounded a lot simpler to use and indeed it was for what I have done so far. If we get to the point of pushing changes back upstream, that will be the real test.
