### ISSUE TITLE
Review whether File menu settings should be saved

### ISSUE THREAD

**Issue by CharliePoole** [TestCentric/testcentric-gui#357]
Some new file menu settings replaced the entries in the settings dialog. One side effect is that the last value is no longer saved. For example, if I load an assembly in process, should that be the new default value?

The particular settings I'm concerned with are
 * Process model
 * X86 setting
 * Domain usage
 * Runtime Framework
 * Number of agents

For this issue, I'm not assuming they should be saved. The answer may be different for each one of them. Choices seem to be
 * Don't save at all
 * Save for the particular assembly
 * Save as an overall default setting

If "Don't save" is the choice for all, this question will have been answered. If anything else is needed, this will be come a feature implementation issue for either 1.0 or 1.1.

**Comment by CharliePoole** [comment]
Conclusions after examining existing code and usage...

1. There should be no general setting for Process Model, X86, Domain Usage, Runtime Framework or number of agents. We should ensure these settings are not being saved.

2. Since we are not saving them, we should not use any setting saved by an earlier version of the GUI. One thing I discovered is that it's quite surprising if an earlier saved setting is used with an NUnit project, because it __silently overrides any settings in the project__. See issue #358.

3. All of the above should be settable on a project basis in either an NUnit project file or a future TestPackage file (planned for the 1.1 release).

@TestCentric/gui-team Comments?

**Comment by CharliePoole** [comment]
@TestCentric/gui-team All of the points above are already satisfied except for the command-line options, which I'll add as part of this issue.

IOW a user who wants to "always" run as x86 should simply use that option at the command-line.

**Comment by immeraufdemhund** [comment]
how will the user know to do that? other than that I don't mind

**Comment by CharliePoole** [comment]
Well, I guess from the docs.
