### ISSUE TITLE
Beta3: unhandled .net exception

### ISSUE THREAD

**Issue by MartinZec** [TestCentric/testcentric-gui#370]
Hello,

I downloaded testcentric-gui-1.0-beta3.zip. After unzipping and executing testcentric.exe an unhandled .NET exception is triggered.
I tried to unblock all *.dlls and deleted the existing Nunit30Settings.xml (C:\Users\USERNAME\AppData\Local\NUnit) to be sure no old setting are causing this issue. But the issue was not resolved by this.

OS: Win10 x64

![error](https://user-images.githubusercontent.com/44475413/61205600-c80a7080-a6f0-11e9-89b8-494885b670b5.png)
![error_2](https://user-images.githubusercontent.com/44475413/61205601-c80a7080-a6f0-11e9-840d-c2dc8dff0940.png)

Best regards,
Martin

**Comment by mikkelbu** [comment]
@MartinZec Can you see which exception it is (by attaching the debugger)? I'm on my phone, so I cannot check it now.

**Comment by MartinZec** [comment]
System.ArgumentNullException: 'Value cannot be null.
Parameter name: value'

 	TestCentric.Gui.Runner.dll!TestCentric.Gui.AppEntry.Main(string[] args) Line 75
 	testcentric.exe!TestCentric.Gui.Class1.Main(string[] args) Line 39	


  | Name | Value | Type
-- | -- | -- | --
  | StackTrace | "   at System.Enum.EnumResult.SetFailure(ParseFailureKind failure, String failureParameter)\r\n   at System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)\r\n   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)\r\n   at TestCentric.Gui.AppEntry.Main(String[] args) in C:\\Users\\charlie\\dev\\TestCentric\\testcentric-gui\\src\\TestCentric\\testcentric.gui\\AppEntry.cs:line 75\r\n   at TestCentric.Gui.Class1.Main(String[] args) in C:\\Users\\charlie\\dev\\TestCentric\\testcentric-gui\\src\\TestCentric\\testcentric.exe\\Class1.cs:line 39" | string

**Comment by CharliePoole** [comment]
Somehow I didn't get (or see) an email notice for this issue. Try using `--trace` on the command-line, even `--trace:Off`.

**Comment by CharliePoole** [comment]
I think this is a packaging error. Really need to automate that as soon as 1.0 is out.

**Comment by CharliePoole** [comment]
Verified that the code released in the packages was not the latest beta3 code, so closing this without a PR and will do a beta4 release.
