### ISSUE TITLE
Display version and path of loaded extensions

### ISSUE THREAD

**Issue by Sharken03** [TestCentric/testcentric-gui#395]
In relation to #340 where an update to the NUnitV2Driver was made, it would be very useful to amend the Tools->Extensions page. 
  Details about version and path of loaded extensions are the helpful bits of information that are missing. According to @CharliePoole something similar is being prepared for the nunit console project.

**Comment by CharliePoole** [comment]
@Sharken03 WRT the console, I did say I filed an issue, but I can't seem to find it. I might have just made a comment. I'll check further. In any case, I can't say that a fix is "being prepared" - I only make requests, just like you. :smiley:

**Comment by ChrisMaddock** [comment]
@CharliePoole You're right it was a comment and not an issue, I remember. "Contributions welcome" on that one! 😄 

@Sharken03 would you be interested in doing a PR to the NUnit Enigine to make this one possible? It should be pretty simple to expose in the engine through the IExtensionNode interface. Charlie may also appreciate a PR to do the second half in this project, but I'll leave that to him. 😄

**Comment by CharliePoole** [comment]
@ChrisMaddock Something to consider would be to do it by convention rather than by looking at the version of an assembly.

Extensions already support properties. We could pick a name like "ExtensionVersion" for the property that will hold a version. The console runner `--list-extensions` option already lists properties and so does the GUI.

This would not necessarily match the version of any assembly. But some extensions have multiple assemblies and they could have different versions. Anyway, it's the package version we probably want, including any pre-release suffix.

**Comment by ChrisMaddock** [comment]
We could. But for such a fundamental concept, I'd personally argue for a type-safe property on extensionnode, rather than a string-based property in a dictionary. 🙂

**Comment by CharliePoole** [comment]
Except it would be an Attribute specified by the author if the extension in either case, either an extension property or AssemblyFileVersion. And we already depend on such properties of extensions for a lot of things including the required engine version to use the extension.

**Comment by Sharken03** [comment]
So for the console runner (Properties box in TestCentric), the output would go from this:
```
Installed Extensions
  Extension Point: /NUnit/Engine/NUnitV2Driver
    Extension: NUnit.Engine.Drivers.NUnit2FrameworkDriver(.NET 2.0)
```
to this
```
Installed Extensions
  Extension Point: /NUnit/Engine/NUnitV2Driver
    Extension: NUnit.Engine.Drivers.NUnit2FrameworkDriver(.NET 2.0)
      Version: 3.7.0
      Path: C:\ProgramData\chocolatey\lib\nunit-extension-nunit-v2-driver
```

When installing with Chocolatey, the assemblies are placed in a tools\ folder within the above path, so one could argue that it would be a better choice for path.
