### ISSUE TITLE
Save test results in alternative formats

### ISSUE THREAD

**Issue by CharliePoole** [TestCentric/testcentric-gui#4]
You can currently save the test result as XML but only in nunit3 format. The GUI has info available as to which other formats are supported and could offer a selection of them on the menu.

**Comment by FlexOr2** [comment]
In my opinion it would be great if there is an option so that the alternative report will be created automatically after test execution.

**Comment by CharliePoole** [comment]
@FlexOr2 What sort of an option would you imagine? That is, how would the user tell us to do that? For example, command-line option? Menu? Something permanent?

**Comment by FlexOr2** [comment]
I think a GUI menu option would be great to turn the option on or off as needed.

**Comment by immeraufdemhund** [comment]
isn't this fixable with the use of extensions? or am I getting confused by the console runner?

**Comment by CharliePoole** [comment]
@immeraufdemhund The extensions exist, but to offer the user a menu option the GUI will need to determine which extensions are installed and create menu options to select them.

@FlexOr2 We could allow the user to save a preferred format option, but there's a problem in the fact that different extensions may be installed and uninstalled and you could have a saved extension that's not available. Of course, we could just ignore the setting in that case.

**Comment by FlexOr2** [comment]
Yes, I think to be able to select a preferred format seems ok.
And if it's not available the default format will be selected.

**Comment by CharliePoole** [comment]
Implemented this as a menu option, requiring the user to select the format.
