### ISSUE TITLE
Set Project Configuration to use

### ISSUE THREAD

**Issue by CharliePoole** [TestCentric/testcentric-gui#402]
NUnit V2 has a Project | Configurations submenu listing all configs in the open project. 

This is currently not available for the TestCentric GUI V1.0.

Issue #216 deals with resolving this problem for the experimental GUI. This issue aims at a fix for the standard GUI, for version 1.1.

There are two options for initial implementation.

1. A single setting that applies to all open projects. While not fully satisfactory, it would work for the common case where only one project is available. A suboption is to only allow setting the configuration where there is a single project open.

2. Allowing setting the configuration separately for each project, possibly through the properties panel or a right-click menu item in the tree.

Design work is needed to decide which option to use.

Priority is high because this is an existing feature of the V2 GUI.

**Comment by CharliePoole** [comment]
Actually, after reviewing the code, it seems as if the approach of allowing the config to be set separately per project is the one most easily implemented.

If we try to set it globally, we need to deal with a number of exception cases, like a project not having the selected config or not having any configs. By tailoring the options to each project, we can avoid that, at least for now.

**Comment by CharliePoole** [comment]
OK... here's an issue that took me by surprise. The engine doesn't expose the ProjectService publicly!

Options:

1. Expose it.
2. Expose a pseudo-service that only provides the names of the configs without anything else.
3. Require the user to know the names of the configs and type in the desired config.

I don't much like 3.

**Comment by immeraufdemhund** [comment]
I like 1

**Comment by CharliePoole** [comment]
Simply exposing the interface is non-breaking, in my view. It's currently a public interface in the `nunit.engine` assembly, which users are not supposed to reference directly. We would move it to `nunit.engine.api` making it a part of the published api. I like that because it's really simple.

We could also consider adding a method to the interface that returns the config names. Otherwise, you need to make several calls to get the names.

**Comment by CharliePoole** [comment]
OK, this is getting complicated. Will create separate PRs for some of these:

- [ ] Expose IProjectService in the engine to enable the model to make use of it. Will also add the private `LoadFrom` method to the interface, to allow getting project information without needing to expand a package in the process.

- [ ] Make the engine `TestPackage` property public and allow presenters to set properties directly on a particular subpackage rather than through the current `PackageSettings` property, which affects __all__ subpackages. Provide a way to identify Package level tests (test run, project, assembly) and associate the TestNode with a particular TestPackage.

- [ ] Refactor and clean up current handling of context menus, which differs between the two GUIs.

- [ ] Finally, implement setting the active config on a subproject in the GUI, based on user selection.

The last task will also need to be done for the experimental GUI, but there's a separate issue for that.

**Comment by CharliePoole** [comment]
Although PR #408 completes the planned work, I'm keeping this open so that it can be improved in some special cases:

1. Where there is only a single project
2. Where there are multiple projects with the __same__ configs (like Debug and Release)
