### ISSUE TITLE
Opening nunit-gui.exe immediately crashes, no gui is shown

### ISSUE THREAD

**Issue by abelbraaksma** [TestCentric/testcentric-gui#413]
I just downloaded the latest ZIP from the releases (build date 16/8/2019, version 3.11), and figured I could just doubleclick it to load it. Forgive me if that is not how it is supposed to work, but it immediately crashed. Same if true for the x86 version.

![image](https://user-images.githubusercontent.com/16015770/66724751-e5eb8c80-ee29-11e9-846c-c077cd79630c.png)

Debugging shows: 

> System.IndexOutOfRangeException: 'Index was outside the bounds of the array.'

I couldn't get a stacktrace because there was no pdb.

_EDIT: my apologies, I needed to run `testcentric.exe`, which, because it doesn't yet have an icon, I didn't doubleclick, I thought it was a console program. My bad. However, I do think that the crash as mentioned is not entirely warranted, so I leave this open._

**Comment by CharliePoole** [comment]
The program `nunit-agent.exe` is part of NUnit, but used in TestCentric. It is not a command-line program that you are intended to run. Rather, it is launched by the NUnit engine and expects to have certain arguments provided. The absence of those arguments caused the error you saw.

The `testcentric.exe` program should have an icon. Can you let me know what version you are using? There is no 3.11 version of the program. The TestCentric version is indicated by the name of the zip package you downloaded. The latest release is 1.0.

**Comment by abelbraaksma** [comment]
@CharliePoole, the zip package is the `testcentric-gui-1.0.1.zip`. Version 3.11 was the version info in the `nunit-gui.exe` file (probably not yet updated after the move to testcentric perhaps?).

This is how the download looks in my explorer. Note also that quite a few files have pdb's, but not all of them:

![image](https://user-images.githubusercontent.com/16015770/66725245-41b91400-ee30-11e9-9217-ad3a82976be8.png)

**Comment by CharliePoole** [comment]
@abelbraaksma There is no `nunit-gui.exe` file in the package. I thought at first that it might have slipped in from some earlier release, but I just downloaded it from our github release page and the file was not present. Your error message suggested to me that you were running `nunit-agent.exe` and `nunit-agent-x86.exe`, which are not intended to be run by users.

Version 1.x of the TestCentric GUI aims to run NUnit tests only. As a result it bundles a bunch of nunit test engine files. Later releases will replace these with a new engine. The "nunit" name and versioning tells you which files are which.

It does seem clear that the install docs need to say more about what to do after unzipping the package!

About the icon... that may be an unexpected error. There is an icon, which is displayed in the upper left corner of the GUI window. It's not clear to me why that icon is not picked up when creating a shortcut, so I'll need to do some research.

**Comment by abelbraaksma** [comment]
> There is no nunit-gui.exe file in the package. I thought at first that it might have slipped in from some earlier release, but

Oh my, you're absolutely right, must've been the late hour, I would've sworn that I clicked on `nunit-gui.exe`. But indeed, it was the agent.

I guess this can be closed as not a bug, unless for the issue with the icon (it's of course possible to pick the icon from another file, but I would assume it ought to be part of the exe as a resource).

**Comment by CharliePoole** [comment]
I spawned two issues from this one, which I'll close now.
