### ISSUE TITLE
Not possible to run explicit tests using the GUI

### ISSUE THREAD

**Issue by mikkelbu** [TestCentric/testcentric-gui#42]
As far as I can tell it is not possible to run explicit tests using the GUI. If I only select explicit tests and run the tests the effect is that all tests are run, since we in `Filters.MakeIdFilter` remove all explicit tests, so we  
and up with the "empty" filter `{<filter></filter>}`.
![image](https://user-images.githubusercontent.com/1007631/38048736-7aa3590a-32c6-11e8-9a60-1415da0b7648.png)

**Comment by CharliePoole** [comment]
I'm not looking at the code for the moment, but we need to distinguish between the actual checked tests and their descendants. We should exclude explicit tests for the descendants only.

**Comment by CharliePoole** [comment]
The check came from the experimental GUI, where it's actually needed, at least in some cases. For this GUI, it isn't so I removed it.
