### ISSUE TITLE
Update assemblyinfo automatically

### ISSUE THREAD

**Issue by CharliePoole** [TestCentric/testcentric-gui#428]
Currently, the cake build uses GitVersion to determine the version for the packages but the updating of CommonAssemblyInfo.cs must be done manually. The build should update the file automatically.

**Comment by CharliePoole** [comment]
One difficulty with this is that we are tracking four different versions...

1. The overall product version, most recently 1.3.1.
2. The version of the experimental GUI, currently 0.18.1.
3. The version of the TestCentric engine, currently 0.2.1
4. The version of the engine API, which is still tied to NUnit at 3.11.

As a preparatory step for automating this, I want to get down to either one or two versions.

The experimental GUI should start taking on the version of the overall release, in spite of its being experimental.

The Engine is in a pre-release stage (pre-1.0) because it has never been released separately. One possibillity is to map it immediately to the overall product version. Another is to make it a pre-release of 1.0 and keep it that way until we release a full 1.0 engine separately from the GUI. That is, the engine would be at 1.0.0-someprerelease for the time being.

It's probably simplest to make the API match the engine at this point.

It goes without saying that I'd like some input on this issue from the @TestCentric/gui-team

**Comment by immeraufdemhund** [comment]
keeping it simple sounds like the best option to me. I remember it being kind of a pain to manage multiple versions and have the main assembly know what minimum versions had to be with what to work correctly... Although once I got it working it was nice.

**Comment by CharliePoole** [comment]
It's especially hard since GitVersion only can calculate one version for the repo as a whole. So we have to use that version or one we can derive from it.

However, although I had reasons to keep those other versions different, I think it's really not necessary...

1. With the name "Experimental" I think the alternate GUI can simply pay no attention to semantic versioning. Features can come and go. We can document that.

2. When we finally release a separate package for the engine, it doesn't have to be 1.0. It can be whatever is the next release, 1.4, 1.5, 2.0, or anything else. __After that__ it should follow the rules, of course.

3. We can keep the same pattern we now have for the Api assembly by using `M.0.0.0` for the AssemblyVersion, where M = the major version component of the engine itself.
