### ISSUE TITLE
include plugins folder setting

### ISSUE THREAD

**Issue by immeraufdemhund** [TestCentric/testcentric-gui#446]
I installed test-centric through the choco package. fired it up and tried loading my project through the solution folder (hoping that the extension was installed). Since the extension wasn't installed or included it couldn't load. Knowing where the library folder is in chocolatly probably shouldn't be a requirement to install a plugin I think it would be nice to have a way to copy in extensions from the UI, or install it from UI, or choose a folder location where plugin libraries are located. Thoughts?

**Comment by immeraufdemhund** [comment]
well that was hasty on my end.. install the plugin through choco and i'm all set.. now to just get this program to work with .net core 3 💡

**Comment by CharliePoole** [comment]
Right. My general idea has been that any installation should by default access the extensions installed using the same package type. So, for example, if you install the console with nuget, then it uses any extensions you installed to the same project with nuget. But if you install with chocolatey, it finds extensions installed with chocolatey. So only our install needs to know where chocolatey puts stuff, not the user. That's one of the things I love about chocolatey installs.

Are you thinking of doing some work on running .NET Core tests or running the gui under .NET Core 3? I've started to do some small bits along the lines of the first. See #445. It's a challenge to break such a big goal up into small steps!

**Comment by immeraufdemhund** [comment]
i have a need/want to run tests in .net core 3 because our wpf app that we are writing is in .net core 3. frequently i get errors in the Rider test runner that the test aborted when running async tests that throw an exception. I'm not sure if it is Rider, or NUnit, or VS test.

**Comment by CharliePoole** [comment]
So to do that, we need...

1. An agent process that runs under .NET Core 3.

2. Probably, a core 3 build of nunit.engine.core.dll. Maybe not... if the core 2.1 engine core can run core 3.0 tests but that's probably what you are already having problems with.

3. A way to identify that the test assembly is core 3 and launch a core 3 process to run it. That's what I'm working on.

Of course, an alternative solution is to have the GUI itself running core3. We'll want that eventually, but I don't think it should have to run target core 3 to run core 3 tests.
