### ISSUE TITLE
Engine will not recognize .NET Framework versions beyond 4.5

### ISSUE THREAD

**Issue by CharliePoole** [TestCentric/testcentric-gui#447]
Recognizing 4.6, 4.7 and 4.8 is easy. However, there's an added problem in recognizing 4.6.1, 4.6.2, etc.

The RuntimeFramework class takes a version in it's constructor. When the version has only two components, it is taken to be the framework version. When it has three or four, that is taken to be a CLR version and a different path is followed.

We __could__ implement a hack, whereby small values in the third component indicate a framework version. I'd prefer to fix it so that the constructor always deals with framework version and we use some static method to construct from CLR version. Alternatively, we could just not allow use of a CLR version, which was introduced back when it was common to have pre-releases with a different CLR.

@mikkelbu @immeraufdemhund @ChrisMaddock Which way do you think I should go? I'll replicate this issue in the nunit-console repo as well.

**Comment by immeraufdemhund** [comment]
I honestly have no idea. I've never cared which version I had, but our company often made us upgrade programs to the latest revision because of "security".

**Comment by ChrisMaddock** [comment]
I personally think we need to separate Runtime and Target Frameworks out into two separate classes entirely. 🙂 Anything else seems like a representation which will always be open to ambiguity.

**Comment by CharliePoole** [comment]
Could you clarify what you mean by Runtime vs Target Framework? What would be separated?

**Comment by ChrisMaddock** [comment]
Just the representation of the two.

An example, I have a test assembly that targets .NET Framework 4.5. On my (hypothetical!) machine, I have three runtimes that I could choose to run that on: CLR v2, CLR v4 and Mono. Like wise for a test assembly that targets .NET Standard 2.0 - I could chose to run it on CLR v4, Mono or .NET Core.

I've found it confusing before how we currently use the same `RuntimeFramework` class to represent both concepts. I'd like to separate that out, and make which target frameworks which we support running on which platforms a little clearer. 🙂

**Comment by CharliePoole** [comment]
Yes, I see your point. I have added a compatible implementation of `FrameworkName` to my .NET 2.0 build in order to deal better with target frameworks. One thing that `RuntimeFramework` has, which complicates things a bit, is the ability to specify "Any" framework and/or any version. So, for example, `mono` means any version of Mono and `Any` means any version of any runtime. This was probably a case of over-complicating things.

I'm going to give this some more thought.

That said, it seems to me that the console option `--framework:net-4.6.1` ought to work in the current setup. That's what this issue is for. The code will be in my build of the engine shortly.

**Comment by CharliePoole** [comment]
@immeraufdemhund @mikkelbu @ChrisMaddock @jnm2 

I've solved this in two ways and I'm trying to decide which one to keep. It's a question of the best way to maintain a robust program, I think. (Chris and Joseph, you guys are mentioned because it's probably a decision the NUnit project will need to consider eventually, so why not pick your brains?)

First approach: RuntimeFramework Constructor recognizes whether supplied version is a framework version. Heuristic is that Build is missing or less than 3 and Revision is missing. It follows a different path, depending.

Second approach: Builds on the first by using a static `FromClr` method to create the CLR. Difference is that calling the constructor with a version that doesn't look like a framework version causes an exception.

Should caller always know whether they are using a framework or a CLR version? If so, the static makes sense. Both the static and the constructor can throw if used with the wrong version type. If we are talking about some version typed in by the user, of course, then the main program will have to figure out which it is using the same heuristic.

One key thing to remember: It is not possible to construct  an object from the CLR for .NET Framework 3.0, 3.5, 4.5, 4.5.1, 4.5.2, 4.6, 4.6.1, 4.6.2, 4.7, 4.7.1, 4.7.2 or 4.8. Trying to do that will always give you either .NET 2.0 or 4.0! So I lean toward an approach that makes sure people don't use the CLR where ambiguity is unacceptable. OTOH, if you are running on 4.0 or lower, there's no other way to do it.

The latest build of issue-447 branch uses the first approach. I'll add a final commit to illustrate the second approach as fast as family activities this weekend allow.

**Comment by CharliePoole** [comment]
Thinking more about it, particularly in light of @ChrisMaddock 's comment about the need for separate objects, I've decided to limit this change to the current structure, where `RuntimeFramework` takes __either__ a framework or a clr version.

The main obstacle to separate creation methods is that `RuntimeFramework` supports `Any` framework and/or version. Of course, there is no target runtime called "Any" and no "Any" version. We eventually have to select some actual runtime on which to run the tests. "Any" is simply a "don't care" value used when setting criteria for the runtime we want to use. I'm starting to think we need some sort of "RuntimeCriteria" object that can be used to say things like "I want the target runtime for which this test was built and nothing else will do" OR "I want any version of Mono" OR "I want to run this on .NET Core 3.0"

So, I'm moving on with cleaning up the version of this branch that I now have.

**Comment by CharliePoole** [comment]
BTW... it should be clear that this issue only deals with __recognizing__ runtimes - either target or available - not with using them. More work is needed to ensure (and verify) that a specific request is honored. In particular, we don't have tests like: force this to run with .NET 4.5.2 behavior and verify that it actually happened though if a higher runtime is actually installed.
