### ISSUE TITLE
Update Copyright headers in all files

### ISSUE THREAD

**Issue by CharliePoole** [TestCentric/testcentric-gui#466]
As part of migrating from nunit.engine to testcentric.engine, the copyright headers in the source files need to be modified. This seems like a good time to make a change I've been wanting to do: moving away from including the full license on every source file. This will simplify the headers so that they will not need frequent updating, which confuses the history of commits.

I've used the proposed .NET Foundation standard (https://forums.dotnetfoundation.org/t/file-headers-and-copyright-statements/1276) as inspiration but modified based on some other projects' practice and my own experience.

The new standard header for C# files in the engine will be:

// ***********************************************************************
// Copyright (c) Charlie Poole and TestCentric Engine contributors.
// Licensed under the MIT License. See LICENSE.txt in root directory.
// ***********************************************************************

The headers for the remainder of the GUI will be similar:

// ***********************************************************************
// Copyright (c) Charlie Poole and TestCentric GUI contributors.
// Licensed under the MIT License. See LICENSE.txt in root directory.
// ***********************************************************************

Note that this notice does not contain the year and so will not require updating on each change. The LICENSE.txt file in the root of the project will need to be updated each year.

Tasks - It's probably best to do this by each solution folder containing projects...

- [x] Common
- [x] Experimental
- [x] GuiException
- [x] TestCentric
- [x] TestEngine - PR #482
- [x] TestModel
- [x] tests

**Comment by immeraufdemhund** [comment]
This seems like a good one for me to get into as it involves touching all the files. I won't claim it yet, but i'm keeping this on my radar

**Comment by CharliePoole** [comment]
That will be great.

**Comment by immeraufdemhund** [comment]
awesome. i'll try to pick this up tonight.

**Comment by CharliePoole** [comment]
@immeraufdemhund I just submitted a PR changing all the namespaces in the engine and a few others. I think the merge should handle it, but if you haven't gotten to far, you may want to rebase once PR #491 merges... waiting now for the CI to pass.

**Comment by immeraufdemhund** [comment]
ok, sounds good

**Comment by immeraufdemhund** [comment]
@CharliePoole  what about `src/ProjectEditor/` does this get included too?

**Comment by CharliePoole** [comment]
We can leave it out for now, since we don't build it.

**Comment by CharliePoole** [comment]
Ah! I see you already did ProjectEditor. No problem... and thanks.

**Comment by CharliePoole** [comment]
Closing manually... FYI in order for the merge to auto-close the issue, the PR description should contain "Fixes" or "Closes" followed by the issue reference, i.e. #466.
