### ISSUE TITLE
Establish Initial Version for TestCentric engine

### ISSUE THREAD

**Issue by CharliePoole** [TestCentric/testcentric-gui#473]
@mikkelbu @immeraufdemhund 

I just realized i can't release 1.2 without making a decision about the version of the testcentric engine we just created. It's currently still using 3.11, just like the NUnit engine.

Additionally, we have to keep in mind that it will eventually be released as a separate package, so what we do now needs to feed into what we want it to be at that point.

I'm considering...

1. Continue from 3.11, making this one 3.12 and plan on the eventual separate release as 4.0. 
2. Call this one 0.3.12  or 0.312 and plan on the eventual separate package being 1.0.

I'd appreciate your feedback so I can get this release out!

**Comment by immeraufdemhund** [comment]
my understanding of changing only the minor version is that it is compatible with the old. If you ran this engine in the other nunit projects would it still work? I'd bet not because of the rename. I'm voting for changing it to 0.3.12

**Comment by CharliePoole** [comment]
@immeraufdemhund Thanks for the quick reply.

You're right, of course, it would not run with NUnit. But then the name change is intended to say that it's no longer NUnit. In fact, I don't think it would run correctly with NUnit even now, because of code changes I've made over the past few months leading up to this.

The thought behind 3.12 => 4.0 is more marketing than compatibility, of course. There's precedent for that in the Microsoft world. :smiling_imp:

**Comment by CharliePoole** [comment]
As a thought experiment, imagine we had not renamed nunit -> testcentric. Let's try to run nunit3-console with the engine. In that case, it would have breaking changes. By the logic of semantic versioning, it should already be 4.0!

However, the rename says "This is a different piece of software" so there's nothing with which it needs to be backward-compatible. Aiming toward an eventual 1.0 release is reasonable.

OTOH, aiming toward a 4.0 release doesn't break any rules either, so I could see us going either way. I go back and forth between the two.

**Comment by immeraufdemhund** [comment]
> However, the rename says "This is a different piece of software" so there's nothing with which it needs to be backward-compatible. Aiming toward an eventual 1.0 release is reasonable.

this is what I lean towards because I don't want to be anything like Angular...

**Comment by CharliePoole** [comment]
Ha! I had to look that up, but I get your point. So, I think I'm convinced it's 0.x.x.

For the minor and revision, I said 0.3.12 to match NUnit, but as soon as it's incremented it doesn't make any more sense. Should we just start at 0.1 and continue from there? If (for example) we reach 0.3 and are ready to publish (and reference) it separately, we would just keep going until we think it's ready for 1.0. That would allow continued breaking changes pre-1.0 according to semantic versioning.

**Comment by immeraufdemhund** [comment]
sounds good to me

**Comment by CharliePoole** [comment]
Funny thing... version 0.1 breaks the engine because `TestEngineActivator` uses a default minimum version of 3.0 when searching for the engine. For now, I changed that to 0.0, meaning there is no minimum, but this area will need reworking after the release.

**Comment by CharliePoole** [comment]
Closing this since we made the decision. Actual implementation is on my release-1.2 branch.
