### ISSUE TITLE
Eliminate use of Mono.Cecil from engine core assembly

### ISSUE THREAD

**Issue by CharliePoole** [TestCentric/testcentric-gui#476]
Much of the usage of Mono.Cecil in the engine core came about simply because the package was available already. Removing it's use would be good because:

1. The core needs to be built for all execution targets and Mono.Cecil may not be available for all.
2. It would reduce the size of the core.
3. It could eliminate the problem we have with using multiple versions of Mono.Cecil by eliminating version 0.9, the last one that supported .NET 2.0.

Much of what we do with cecil in the core can be done easily via reflection. Other info can be passed on from the upper level of the engine in the TestPackage, as we now do for many things. 

We should bear in mind that we started using Mono.Cecil for examining assemblies when we might not be able to load them successfully. However, once we are done in the engine core, we have already decided to load the assembly and we may as well do so and then reflect as necessary.

I believe this change would also fix issue #475

**Comment by CharliePoole** [comment]
Currently experimenting with a much broader option on the issue-476 branch. I'm reviving our old `AssemblyReader` class, refactored and renamed as `AssemblyInspector` and working to make it do the (very few) things that we currently get from `Mono.Cecil`

Here's the list of functionality we need, which is really quite small in comparison to what `Mono.Cecil` can do:

 - [ ] Examine an assembly even if we are not currently running under the runtime it targets.
 - [ ] Make sure it's a valid managed (.NET) assembly.
 - [ ] See if 32-bit execution is required.
 - [ ] Get the runtime version (CLR version) used for the assembly
 - [ ] Look at assembly references to find what test framework it uses.
 - [ ] Examine assembly attributes, in particular the TargetFrameworkAttribute.

**Comment by CharliePoole** [comment]
So, in order to get assembly references, I started pulling in some files from `Mono.Cecil`, because interpreting all the metadata tables is too complex to invent when code already exists!

I ended up with my own class plus a dozen or so `Mono.Cecil' classes. But it looks like I can just add a few more from Cecil and drop most of my own. The Cecil code is already well-tested, so that's what I'm about to do. 

I'm noting this here because the existing code will disappear as soon as I do a forced push.

**Comment by CharliePoole** [comment]
I've moved the code for `AssemblyView` and it's dependencies to a separate assembly. It was very confusing to have a reference to `Mono.Cecil` in the same project I'm working in to replace it!

**Comment by CharliePoole** [comment]
@immeraufdemhund @ManfredLange @ChrisMaddock

Tagging you guys to make sure you are all seeing this, in particular Chris, since the resolution could also be useful for NUnit. In particular, in addition to the code review itself, there are several alternative approaches to what I've been doing, which have now come to my mind. I'll next outline them... more to come...

**Comment by CharliePoole** [comment]
Using this comment to back up a bit and write about (1) what I want to accomplish and (2) three ways I think it might be done.

GOAL

To eliminate use of Mono.Cecil by engine.core... and maybe completely! The initial issue description explains why that would be useful, but the biggest reason for me is that I don't want Agents to need Mono.Cecil. In future, we may want to write agents for platforms that Mono.Cecil doesn't support.

STRATEGIES

I have identified three main strategies for dealing with this issue.

1. __Use our own code rather than Mono.Cecil.__

   That's what my work so far has been about. I started with some code I wrote several years back, which reads an assembly into memory and examines all the header information. At it's current stage of implementation, it actually uses parts of the Mono.Cecil source code, which leads to...

 2. __Build and use our own subset of Mono.Cecil.__

    I have an alternate build that actually does this, but which I have not yet pushed to GitHub. It seems to run all tests well. Currently, it uses my build of Cecil for the core and the nuget package for the engine itself, but I think it could easily be used in both places.

 3. __Limit use of Mono.Cecil to the engine only.__

     Currently, the engine.core uses Cecil for the `ExtensionService`. That has to be in the core, because the core uses an extension point to locate the correct framework driver. It seems like we could relatively easily figure out what driver to use in the engine itself and pass that assembly name down to the agent and core in the TestPackage, just as we already pass lots of information. This would significantly reduce the size of the agent and make it much simpler to create agents for a variety of platforms.

Some comments on the three strategies...

 * Approaches 1 and 2 are similar and actually represent a range of options from 100% our own code to 100% Cecil. We could use either of these to replace Mono.Cecil in the core or entirely. In fact, we would most likely drop it completely, rather than trying to maintain two ways of doing the same thing.

 * Approach 3 can be used in itself, maintaining use of Mono.Cecil in the engine, or it could be combined with either 1 or 2. 

 * The choice will depend on current and future platform support, which means that different approaches may work best for the NUnit and TestCentric projects.

Please use this issue to feed in your thoughts on these general approaches. As I continue to experiment, I will annotate each of the above descriptions with the names of branches and PRs that implement them.

**Comment by ChrisMaddock** [comment]
I think three is a good move in general. Options 1 & 2 are both much of a a muchness to me, personally I’d be tempted to go with option 2 - on the basis that I expect the mono project has already hit a bunch of edge cases that wouldn’t cross my mind!

**Comment by immeraufdemhund** [comment]
I'm going with Chris on this one too. Approach 2 seems like the easiest.

**Comment by CharliePoole** [comment]
I like number 3 as well... independent of either 1 or 2. The only issue is that it means changing the interface for framework drivers... or creating a new interface and dropping support for the old one.

The new interface would need to return an AssemblyName (or a FullName string) for the selected driver. The engine would put the FullName into a package setting and the agent would simply load that framework.

I don't know if there are any framework drivers other than our own, so maybe it wouldn't be a problem. But of course somebody could turn up.

One way to keep old drivers working is to have the engine get the driver, extract an assembly name and then dispose of it. That's a pretty big hack, however.

This is one of those places where TestCentric could break "compatibility" freely, since it's a new application. For NUnit you may have to think about it more.

In any case, if we go with three, the question becomes should we also go with 1 or 2? I think that ties to whether in-process execution continues to be supported. If the answer is no, then it seems likely that Mono.Cecil will continue to support targets that would be used.

For example, in TestCentric, I'm thinking the GUI will eventually run under framework 4.7.x or 4.8 and .net core 3.0. Mono.Cecil is built for framework 4.0 and .net standard 2.0, so that will be OK. It seems likely that Mono.Cecil will continue to support runtimes (for execution that is) which we would want to use for a frontend app. The main problem is that they are likely to drop support for older frameworks, as they get older, for which we may want to execute tests. So, use of Mono.Cecil by the agents is problematic.

**Comment by CharliePoole** [comment]
I think I need to do some of the re-structuring that @ChrisMaddock has talked about before implementing option 3. In particular, we need a separate service to examine assemblies and add info about them to the packages so it's done all in one place... AssemblyTargetingService or some such name. That way, all the usage of Cecil or its replacement could be centralized.

**Comment by CharliePoole** [comment]
On hold, waiting for #502

**Comment by CharliePoole** [comment]
I've done quite a bit of work on option 3 but I have now realized there is a fundamental problem to be overcome!

Drivers are discovered as extensions implementing `IDriverFactory`. In the process of discovery, we ignore all extensions that could not be loaded under the current runtime. So, if the engine is running under .NET 2.0, extensions written for .NET Standard or .NET Core will not be reported. If running under .NET Core, the reverse is true.

For the approach I planned on to work, we would need to discover and maintain nodes for __all__ runtimes and allow agents to select those that are capable of loading. That's a major change to the extension service.

At this point, I'm not sure what to do in the short term.

**Comment by CharliePoole** [comment]
OK... looked over the options... for now, I plan to go with option 2, which has the advantage over the others that it's the only one that is fully working!

So, for this issue, `testcentric.engine.core` will use my own subset of Cecil, while `testcentric.engine` will continue to use full Cecil. For the core assembly, this gives us the following advantages:

1. The subset builds and works for all runtimes on which we run tests.
2. The combined size of the Cecil assemblies (370K) is eliminated in favor of a single assembly, which is currently 170K. I'll go through next to see if this can be reduced further.
3. We use the same code in all runtime builds.

In a separate PR, we might consider eliminating Cecil in the `testcentric.engine` as well. This would have the same advantages as for the core. Work would need to be done to ensure that the subset has all the functionality that is needed. Most likely, it does, since it already works in the core for the extension service.
