### ISSUE TITLE
Release schedule for the GUI

### ISSUE THREAD

**Issue by CharliePoole** [TestCentric/testcentric-gui#49]
Right now, we have only a 1.0 milestone, with no releases planned before then. Let's figure out if we want any other releases @TestCentric/gui-team as well as what should be in them.

1. Is there anything in the 1.0 milestone that doesn't need to be done to have a first production release that gives equivalent functionality to the V2 GUI?

2. Is there anything missing?

3. I'm assuming we'll do a beta when we have all the features done for 1.0, although I didn't set up a specific milestone for it. I'm using "feature-complete" as my criterion for a beta.

4. Do we want any prior releases, either 1.0-alpha or 0.x? What features are needed to have a minimum releasable alpha?

I'd appreciate it if you could all weigh in on these questions.

PS: I'm kind of re-defining "question" here as questions we are asking ourselves. Seems reasonable to me. 😄

**Comment by CharliePoole** [comment]
@TestCentric/gui-team As a further help toward planning, I'd appreciate it if each of you would let me know, either here or by email, whether you want to keep working on this and / or any of the other TestCentric projects and at what degree of involvement. 

If some of you want to remain involved but don't have sufficient time to do coding, I'll start recruiting new folks to do the work. 😺

**Comment by immeraufdemhund** [comment]
I currently have two side jobs that don't look like they have any end in the near future. When I first joined I had no side jobs. I think I might have to either be kicked or be allowed for code reviews. I just can't see myself having any extra time to code.

**Comment by CharliePoole** [comment]
@immeraufdemhund Hey, that's too bad for us but reviews are actually a big help. Whenever it changes, feel welcome to step back in.

**Comment by CharliePoole** [comment]
@TestCentric/gui-team I've created a release schedule in the form of three milestones:
 * 1.0-alpha
 * 1.0
 * 1.1

Please comment here.

**Comment by mikkelbu** [comment]
> If some of you want to remain involved but don't have sufficient time to do a lot of coding, I'll start recruiting new folks to do the work. 😺

Actually, I'm unsure if this is meant to be ironic or not, but I think the more contributors the better. Currently, I'm pretty booked at work (and also at home), so combined with regular NUnit work, dotnet/docs and dotnet/roslyn work, etc. then I don't have much time to work on TestCentric tasks.

Wrt. the milestones, then I think they are fine, but I don't see #11 an #12 as important, so we could just as well postpone these. I think it is more important the remove the bugs and then (pre)release it to get some feedback from the users.

**Comment by CharliePoole** [comment]
@mikkelbu @TestCentric/gui-team No, not intended ironically at all, in spite of the smiley.

Here's the thing. I do not want a large team actually coding on this. I think three or four people is ideal. You guys are familiar with what we are trying to do and are the best people I know for the job. I'll recruit others and save you for reviews, advice and backup if necessary, but otherwise you are the ones I want on this and / or on the new GUI.

I also recognize that the new gui is more likely to be fun. You may want to save yourselves for that.  😄 

Issue #11 was low priority and I just made #12 low priority as well. Low priority, for purposes of the release, means I don't care if it gets in. I suspect #11 will get dropped but #12, which is pretty trivial, might make it.
