### ISSUE TITLE
Engine Tests don't run under .NET Core 2.1

### ISSUE THREAD

**Issue by CharliePoole** [TestCentric/testcentric-gui#499]
Through code inspection, I discovered that we are running the `testcentric.engine` tests twice under .NET 3.5, even though the task names indicate we run under .NET 35 and .NET Core 2.1.

This is a high priority, even though we don't yet use the .NET Core App build in the GUI because, if unresolved, it may lead us to perpetuate problems we are not able to see!

**Comment by mikkelbu** [comment]
This needs to be changed https://github.com/TestCentric/testcentric-gui/blob/c19e069e722d867096bc8d05c1daf3b752499432/build.cake#L259 to use runtime

**Comment by CharliePoole** [comment]
Yup! That's the "code inspection" that led me to discover this, but I felt an issue was needed for the readme.

**Comment by CharliePoole** [comment]
Fun fact: I had seen those same errors when I first started running the tests for NETCoreApp2.1. At some point, it seemed as if I had mysteriously "fixed" them! Now we know how. :smile:

**Comment by CharliePoole** [comment]
I see that the NetCoreApp build only has MasterTestRunner, AggregatingTestRunner and LocalTestRunner. So it only can run tests in process, which makes it not very useful.

As it is, we can run .NET Core tests in an agent but we can't have a NET Core GUI build, because it would only be able to run .NET Core tests and only in-process. We'll have to add back in the ProcessRunner, MultipleProcessRunner, etc. in the 2.0 GUI.

For now, the tests simply reflect what the .NetStandard 2.0 engine is actually doing, not what we may want it to do in the future.
