### ISSUE TITLE
Cannot load test assembly after 1.3 update

### ISSUE THREAD

**Issue by MartinZec** [TestCentric/testcentric-gui#535]
Hello,

I downloaded "testcentric-gui-1.3.0.zip" and tried the new version.
With 1.2.0 I could load the test assembly and execute tests.
With 1.3.0 I see at the Assembly Properties a 
"Test Count: 1 Should Run? No" and "NotRunnable",
as attached.

I do not see any log or other output why testcentric 1.3.0 cannot load my tests.

Do I need to change anything on the assembly?

![Testcentric_1_3_0](https://user-images.githubusercontent.com/44475413/75369048-f5441180-58c2-11ea-877b-bf9464e6bf9a.png)

**Comment by CharliePoole** [comment]
What runtime are you targeting with your test assembly? Are you running with any non-default settings, like running in process for example? Can you load the same test with the experimental GUI (tc-next.exe)? If so, what does the XML tab show?

Strangely, I saw the same problem right before releasing. But I did a full rebuild and it disappeared, so I went ahead and pushed the release.

**Comment by CharliePoole** [comment]
@immeraufdemhund This is the sort of thing I was concerned about in our discussion on #534. Right now, the only testing of packages we have before release is manual. Something automated, right before release, which actually exercised both GUIs in some way might be useful. In fact, a simple smoke test would have caught this one...

I'm thinking I should probably set up a bare VM and install the packages on it for manual testing until we come up with something better. That runs against my desire to make releasing really easy, so we can release more often, but getting it right has priority.

@MartinZec Have you tried either the nuget or the chocolatey packages?

**Comment by MartinZec** [comment]
I used .NET 4.7.1.
tc-next.exe shows 
"Method not found: 'System.Runtime.Versioning.FrameworkName TestCentric.Engine.RuntimeFramework.get_FrameworkName()"

I used the zipped fiels, https://github.com/TestCentric/testcentric-gui/releases/download/1.3/testcentric-gui-1.3.0.zip

**Comment by CharliePoole** [comment]
It appears that this is the same as issue I identified as #537. All three packages are missing the agent for running .NET 4.0 and higher tests. This will be corrected in the 1.3.1 release, which will be available some time tomorrow.

You may be able to run the tests in-process until then, but I'm not sure.

**Comment by CharliePoole** [comment]
Fixed by #538

**Comment by CharliePoole** [comment]
@MartinZec Thanks for reporting this and sorry it took so long to fix! I kept running tests in the build directory and only realized the problem was with the packaging when I started working on CI tasks to verify correct content of the packages.
