### ISSUE TITLE
Default process model for 32 bit v1.3.1

### ISSUE THREAD

**Issue by MartinZec** [TestCentric/testcentric-gui#542]
I load a 32bit .dll with testcentric.
With v1.2 I did not need to change the Process Model and the assembly was loaded automatically. With version v1.3.1 I need to change the process model to "Run as x86" to load the assembly, the "Default" process model dos not work for me to load 32bit dlls.

**Comment by CharliePoole** [comment]
Sounds very inconvenient! If you work regularly with a project that requires it, I suggest creating a shortcut or script that uses `--x86` on the command-line as a workaround.

**Comment by CharliePoole** [comment]
Confirmed.

**Comment by CharliePoole** [comment]
Actual fix was only a change in one line. But I also added tests and discovered another unreported bug - also fixed in the PR. There's now a mock-assembly x86 build for use in testing.
