### ISSUE TITLE
Support the NUnit engine API

### ISSUE THREAD

**Issue by CharliePoole** [TestCentric/testcentric-gui#560]
Investigation related to issue #558 has made it clear that use of our own API assembly is a source of potential problems for anyone wanting to write extensions. TestCentric can have it's own engine, but it needs to support the NUnit engine API so that extensions may be used in both environments.

As of the latest release, no extensions are being loaded and it appears that this may have been the case as far back as version 1.3.0. I'm making this a critical error for immediate correction even though it will likely cause problems for other work in process.

**Comment by CharliePoole** [comment]
Here's a proposal for maintaining compatibility with the NUnit engine... I'd appreciate it if @TestCentric/gui-team and @nunit/engine-team members could take a look and comment. Since the issue is critical, sooner is better than later, immediate reaction better than long study. :smile: 

1. I know there are some small changes in the TestCentric api assembly. For example, IProjectService is exposed publicly for use by the GUI. My first step will be to identify all such differences.

2. TestCentric will reference the nunit.engine.api package from the NUnit project.

3. The testcentric api will reference the nunit api, passing through all members that are present in both apis: e.g. 

```
public interface ITestEngine : NUnit.Engine.ITestEngine { }
```

4. All TestCentric code - both the GUI itself and the engine - will continue to reference the testcentric API in order to keep any changes localized.

5. The testcentric implementation of the extension service will be modified so that extensions must use the nunit api to be recognized. This should allow all extensions to be interchanged between the two engines.

6. One outcome of all the above is that any runner must be written to use one engine or the other. Making the engines work as drop-in replacements for one another would be a lot more work and doesn't seem warranted right now.

I'm moving ahead with this plan and hoping to get something out that allows extensions to work again before or over the weekend.

**Comment by CharliePoole** [comment]
Apparently, I can no longer successfully mention @nunit/engine-team so I'll mention each of you: @ChrisMaddock @mikkelbu @jnm2 @rprouse

**Comment by CharliePoole** [comment]
This is the result of the analysis described above in step 1. It doesn't include differences in the engine itself, only in the two API assemblies. I keep meaning to get to the full documentation of differences, but... you know how that goes!

### New in the TestCentric API (not present in NUnit API)

`IProjectService` is exposed because the GUI needed it. The interface is internal to the engine in NUnit. In the short term, this will continue be exposed in the TestCentric API only. If NUnit were willing to expose it publicly, that would remove one incompatibility.

### Removed from the TestCentric API but still present in NUnit

`ISettings interface. We discussed removing both of these from NUnit as well, since it's not really the engine's job to maintain application settings. It woud be a breaking change for NUnit, so it's still there. The TestCentric API can simply continue to not pass this on, since only the GUI uses it.

`IRecentFiles` interface. Similar reasoning and resolution as `ISettings`.

### Other Differences between the Two APIs

 * The TestCentric API uses a different namespace. That will continue.
 * The TestCentric API uses a different file header for license and copyright. That will continue.
 * The implentation of `TestEngineActivator` in the TestCentric API creates a reference to the TestCentric engine rather than the NUnit engine. That obviously needs to continue. 
 * The TestCentric implementation of TestPackage includes a method to externally set the ID of the package. This can be accomplished through inheritance and adding the method in TestCentric. If NUnit wanted to consider adding this to the package in the longer term, we should discuss how it's used.

After any review and discussion of the above, I'll add this info to a file in the TestCentric api project.

**Comment by mikkelbu** [comment]
I think the plan sounds reasonable, but I fear that we at some point will - by accident - refer directly to a class from the nunit api and not the testcentric api (e.g. a class returned from a method in the testcentric api).

Ps. I don't think one can mention teams from the NUnit project from other projects, so @nunit/engine-team does not work under TestCentric.

**Comment by CharliePoole** [comment]
It's tricky. That's why I don't want any projects in the GUI to reference the NUnit API except for the TestCentric API assembly, which can choose what to expose. If possible, I wouldn't even do that. Maybe I'll do some more experiments...

Re mentioning the other teams... I was able to do it up to now but it seems to have disappeared.

**Comment by CharliePoole** [comment]
UPDATE: I did a spike using the inherited approach and I wasn't happy. The main reason to do it is to avoid the need for multiple assemblies to reference the NUnit API. But if we inherit an interface in TestCentric from one in NUnit, then code that references it needs to reference both assemblies.

The alternative is to use aggregation rather than inheritance and forward every call. I'd prefer not to do that, so I'm looking to see if there's a local fix to the extension service that will avoid all that. I'll make some updates to the plan in the earlier comment.

**Comment by ChrisMaddock** [comment]
Hmmm....

The Engine API isn't really designed to be implemented by other Engines, right? It's more an interface to be called by multiple runners. My thinking here is the way we maintain - we quite freely add new methods/properties as required, with the idea that that's a non-breaking change. In this case, that would then become a breaking change for TestCentric - which isn't a further limitation I would want to put the NUnit Engine development. Of course, it's a cost that can be managed however, changes in this area are rare.

My "immediate reaction rather that long study", is that this is a big maintenance cost being put in for a small problem. If TestCentric wants to load NUnit Extensions, why not just write an Extension loading service which can do that? Is there an issue I'm missing with extensions referencing nunit.engine.api, but being loaded and called upon by testcentric.engine.dll?

**Comment by ChrisMaddock** [comment]
> so I'm looking to see if there's a local fix to the extension service that will avoid all that.

Oh. Reading again, looks like you came to the same conclusion as me, yesterday. Cool! 😁

**Comment by CharliePoole** [comment]
I'm not an "up-front design" guy, so I generally try lots of approaches. My first ideas where... my first ideas and I'm moving on. I'll replace the initial proposal with what I'm now trying shortly.

Right now, having thought about how __little__ "my" API actually differs from NUnit's, I'm wondering whether I ever needed it in the first place. So my next experiment is putting back the NUnit API, as it was - just using the package in fact. That means a lot of changes to `using` statements - tedious, but not difficult - and figuring out what to do about each of those differences I mentioned in an earlier comment. I think they can all be dealt with.

We'll see how that goes today.

**Comment by CharliePoole** [comment]
@TestCentric/gui-team @ChrisMaddock @mikkelbu @jnm2 @rprouse

I updated the comment above listing how I propose to do this change. Whether you already commented or not, kindly look at the new "plan" and give me your thoughts.

Here's a "meta" plan, listing the approaches I have tried, am trying, will try...

1. Direct interface inheritance TC Api => NUnit Api (Tried and found too complicated)
2  Eliminating the TC API and using NUnit's (Current iteration)
3. ???

**Comment by CharliePoole** [comment]
Latest working commit removes `testcentric.engine.api` assembly and uses `nunit.engine.api`. See https://github.com/TestCentric/testcentric-gui/issues/560#issuecomment-611143044 for updated discussion of API differences that need to be dealt with.

**Comment by CharliePoole** [comment]
This is my updated plan for resolving this issue, based on removing - or substantially removing - the TestCentric API assembly and relying on the NUnit assembly.

1. Remove the `testcentric.engine.api` assembly and replace it with references to `nunit.engine.api`. Fix all using statements. Temporarily (at least) work around differences so it compiles.

2. Review all references to the API from the GUI and try to localize them in the model assembly, removing all others.

3. Remove workarounds created in step 1, either by changing the GUI model code or proposing changes to the NUnit API.

I'm moving ahead with this plan for now but still would like to see any suggestions, disagreements or general encouragement from @TestCentric/gui-team @ChrisMaddock @mikkelbu @jnm2 and @rprouse. Is there some issue I missed?

**Comment by rprouse** [comment]
It seems like a reasonable approach to me. It is hard to know for sure without being in the code. My biggest worry is future additions to the API as @ChrisMaddock said. I don't think that is a major issue though, it will be obvious when you upgrade because it won't compile.

**Comment by CharliePoole** [comment]
I have some ideas about changing TestEngineActivator to allow dealing with that. I'll post something on the engine project soon.
