### ISSUE TITLE
Carry CurrentDirectory over to agent processes

### ISSUE THREAD

**Issue by CharliePoole** [TestCentric/testcentric-gui#577]
Issue #576 started out to be about CurrentDirectory but then turned out to be something else. Nevertheless, it pointed out something I think we should probably change.

Beginning with NUnit 3, we made it a policy that we wouldn't change the user's working directory (aka CurrentdDirectory) and that we wouldn't rely on the working directory for much of anything - currently only as a default location for saving logs and result files.

We followed through with that promise by removing all NUnit code that changes the working directory and providing the `TestDirectory` property to users who need to know where the current test assembly is located.

However, from a naive user point of view, there is __one place__ where the CD is changed. When we launch an agent process, the CD of that process is the location of the agent assembly. This is true no matter what directory the user was in when the test was launched.

This is easy to fix. `TestAgency` merely has to set `Process.StartInfo.WorkingDirectory` to the value of `Environment.CurrentDirectory`. Then, tests run with `--process:Multiple` will have the same working directory as those run in process.

I don't consider this a breaking change, since it's highly unlikely that anyone is counting on the cd being set to directory where the agent is installed.

**Comment by ChrisMaddock** [comment]
Fixing the inconsistency between different test running modes makes sense. I think we can treat this as a bug fix, and not wait till v4, in my opinion.
