### ISSUE TITLE
TestCentric engine does not support UserSettings

### ISSUE THREAD

**Issue by CharliePoole** [TestCentric/testcentric-gui#580]
### NUnit Compatibility Issue

__Category:__ Services
__Visibility:__ Users
__Resolution:__ Remove from NUnit engine in V4

#### Description

ISettings interface and UserSettings service have been removed from the TestCentric engine. We discussed removing it from NUnit as well, since it's not really the engine's job to maintain application settings. It would be a breaking change for NUnit, so it's still there. Currently, the TestCentric engine returns null if this interface is requested, as it now does for any unimplemented request.

**Comment by ChrisMaddock** [comment]
Agree we should remove in NUnit Engine v4

**Comment by CharliePoole** [comment]
Marked as resolved, pending any further comments from team members. Again, @ChrisMaddock , should we do an issue for V4?

**Comment by CharliePoole** [comment]
UserSettings service has been removed from NUnit engine main branch.
