### ISSUE TITLE
TestCentric engine does not support RecentFiles

### ISSUE THREAD

**Issue by CharliePoole** [TestCentric/testcentric-gui#582]
### NUnit Compatibility Issue

__Category:__ Services
__Visibility:__ Users
__Resolution:__ Remove from the NUnit Engine for the 4.0 release

#### Description

IRecentFiles interface and RecentFiles service have been removed from the TestCentric engine. We discussed removing it from NUnit as well, since it's not really the engine's job to maintain application settings. It would be a breaking change for NUnit, so it's still there. Currently, the TestCentric engine returns null if this interface is requested, as it now does for any unimplemented request.

**Comment by ChrisMaddock** [comment]
Agree we should remove in NUnit Engine v4.

**Comment by CharliePoole** [comment]
@ChrisMaddock I edited the description with the resolution.

This is our first resolved issue. Should we create a V4 issue to remove recent files before I close this one?

**Comment by CharliePoole** [comment]
Also, before closing, any other comments from team members?

**Comment by mikkelbu** [comment]
Not from me. I agree with both of you.

**Comment by ChrisMaddock** [comment]
I think this is a good idea. Given this will be a breaking change for the NUnit Engine, I'd like the NUnit issue to properly document the motivation behind the change, and to open it up to the wider community for discussion. It might even make sense to come up with some sort of standard template.

I'll get back to that this weekend - feel free to put something together though, if you can get to this sooner that I can#1

**Comment by CharliePoole** [comment]
RecentFiles service now removed from NUnit Engine main
