### ISSUE TITLE
Engine Core Platform Support

### ISSUE THREAD

**Issue by CharliePoole** [TestCentric/testcentric-gui#584]
### NUnit Compatibility Issue

__Category:__ Platform Support
__Visibility:__ Users
__Resolution:__ Unresolved

#### Description

The NUnit engine core is built for
 * .NET 2.0
 * .NET Standard 2.0
 * .NET Standard 1.6

The TestCentric engine core is built for
 * .NET 2.0
 * .NET 4.0
 * .NET Standard 2.0
 * .NET Standard 1.6

**Comment by ChrisMaddock** [comment]
See https://github.com/nunit/nunit-console/issues/770 for NUnit Engine discussion.

@CharliePoole - is there a particular "incompatability" here, as opposed to just a difference in code? Does the TestCentric engine core assembly make use of any .NET 4.0 specfic functionality, which requires a .NET 4.0 build over .NET 2.0?

**Comment by CharliePoole** [comment]
@ChrisMaddock Maybe you're right. I don't know of any special functionality that is used, since I basically just re-targeted the 2.0 build without change. Since we added a .NET 4.0 agent for NUnit, the tests will run on that with the engine core asembly runnning under whatever version of the 4.x framework the user has installed.

I put this in because it was a difference at least but maybe not an incompatibility. The reason I did it was because some set of assemblies was going to be copied into the .NET 4.0 agent directory for distribution and I figured I might as well build for 4.0. Maybe the resolution is to do nothing.

@jnm2 @mikkelbu Do you have any thoughts on this?

**Comment by CharliePoole** [comment]
@ChrisMaddock I'm ready to close this one if you are.

**Comment by ChrisMaddock** [comment]
Sounds good 👍
