### ISSUE TITLE
Metadata Assembly

### ISSUE THREAD

**Issue by CharliePoole** [TestCentric/testcentric-gui#585]
### NUnit Compatibility Issue

__Category:__ Internal
__Visibility:__ Users
__Resolution:__ Publish the metadata assembly as a package for both projects to use. Eliminate __all__ use of Mono.Cecil (not merely in the engine core) to avoid conflict with use of Mono.Cecil by the application under test.

#### Description

The TestCentric engine includes a metadata assembly, which is used in the core instead of Mono.Cecil. The engine users version 0.10 of Mono.Cecil.

The NUnit Engine users two versions of Mono.Cecil in the core and a single version in the engine.

**Comment by ChrisMaddock** [comment]
As discussed, removing the Mono.Cecil dependency would be a goal for the NUnit Engine.

**Comment by CharliePoole** [comment]
I can see two ways to go here...

1. Publish the metadata assembly on nuget and use it.

2. Add it as source to the NUnit project and use it.

What do you think?

**Comment by ChrisMaddock** [comment]
Main difference from my point of view is that option 1 would make it a library that you maintain, unless the engine needed to fork it for any reason. Option 2 makes maintenance the responsibility of the NUnit project.

I have no strong preference either way - I have no problem taking on the dependency, if you decide that's how you'd prefer to contribute this code. 🙂

**Comment by CharliePoole** [comment]
I'll start out by publishing it separately. It has no other dependencies, so it's easy to do that way and it's also slightly easier for me to continue working on it in the testcentric project.

I think I will continue working on it. There may be a need for more features if I replace Mono.Cecil in the primary engine assembly. I think that would be advantageous when testing applications that actually use Mono.Cecil themselves.

**Comment by CharliePoole** [comment]
@ChrisMaddock, see updated Resolution in the description of this issue.

I will continue to use this issue for the TestCentric side of the work. Here are the tasks I see needed:

### TestCentric:

 - [ ] Eliminate use of Mono.Cecil in `testcentric.engine` assembly, adding any needed features to `testcentric.engine.metadata` in order to make this possible.
 - [ ] Publish the metadata assembly as a separate package. (see note)

### NUnit:

 - [ ] Reference the metadata assembly and eliminate use of Mono.Cecil in both the core and the primary engine assembly.

__Note:__ Depending on the timing of things, the package may be published initially under TestCentric or under NUnit.

**Comment by CharliePoole** [comment]
@ChrisMaddock I believe we can check off the last item and close this compatibility issue. Do you agree?
