### ISSUE TITLE
Project Service Semantics

### ISSUE THREAD

**Issue by CharliePoole** [TestCentric/testcentric-gui#587]
### NUnit Compatibility Issue

__Category:__ Services
__Visibility:__ Users
__Resolution:__ Both engines now do this

#### Description

The TestCentric implementation of ProjectService adds settings to the created package giving a list of all configs as well as the ActiveConfig.

This support has been added to the engine but is not yet released. @ChrisMaddock correct?

**Comment by ChrisMaddock** [comment]
Yep :+1:

**Comment by ChrisMaddock** [comment]
@CharliePoole - I think this is now released in NUnit Engine 3.12?

**Comment by CharliePoole** [comment]
I'll keep this issue until I'm using 3.12.
