### ISSUE TITLE
Separate test assemblies for engine and engine core

### ISSUE THREAD

**Issue by CharliePoole** [TestCentric/testcentric-gui#590]
### NUnit Compatibility Issue

__Category:__ Build
__Visibility:__ Internal
__Resolution:__ Pending

#### Description

TestCentric has separate tests for the engine core and the engine itself. NUnit has them all in one assembly, using conditional compilation to leave out tests that don't apply to the engine.

This is purely an internal build detail affecting project devs only but is listed for completeness.

**Comment by ChrisMaddock** [comment]
I have no strong feelings on this either way. I think it's simply a 'not done yet' for the NUnit engine.

**Comment by CharliePoole** [comment]
Sure. I was just trying to list everything I could think of. Maybe the resolution is "So what?" :smiling_imp: Or "no change needed." I'd be good with that.

**Comment by ChrisMaddock** [comment]
Cool, I think we're in agreement then! 🙂 Shall we close this?
