### ISSUE TITLE
GetExecutingAssembly() returns the path of appdata folder instead of actual location

### ISSUE THREAD

**Issue by MahendraChoudhary** [TestCentric/testcentric-gui#593]
We are deserializing few xmls from our tests and these xmls are placed in our output directory.
Our tests code looks like below 

namespace Nunit3POC
{
    [TestFixture]
    public class TestClass
    {

        [OneTimeSetUp]
        public void OpenBrowser()
        {
            var assemblies = ReadAssembliesFromXml();
        }

        [Test]
        public void Filter()
        {
        }

        [OneTimeTearDown]
        public void Close()
        {
        }

        private static SupportedControlAssemblies ReadAssembliesFromXml()
        {
            XmlSerializer serializer = new XmlSerializer(typeof(SupportedControlAssemblies));
            var directory = Path.GetDirectoryName(Assembly.GetExecutingAssembly()
                                                          .Location);
            StreamReader reader = new StreamReader(Path.Combine(directory, "SupportedControlAssemblies.xml"));
            var assemblies = (SupportedControlAssemblies)serializer.Deserialize(reader);
            reader.Close();
            return assemblies;
        }

    }

    /// <summary>
    /// This is used by the MatcherAnalyser. It deserializes supporteControlAssemblies.xml
    /// </summary>
    [XmlRoot("supportedControlAssemblies")]
    public sealed class SupportedControlAssemblies
    {
        [XmlElement("assembly")]
        public Collection<string> Assemblies { get; set; }
    }

}

ReadAssembliesFromXml() method throws exception because it could not find SupportedCcontrols.xml in the AppData folder.(refer attached screenshot)

But same tests are working fine with Nunit 2 GUI runner.

Note: I have unchecked "shadow copy" for both the runners(Nunit 2 GUI runner & Testcentric).

**Expected behavior**
Testcentric should provide us correct path of ExecutingAssembly.

**Screenshots**
![image](https://user-images.githubusercontent.com/16460793/85221385-192ae600-b3d1-11ea-9aed-758cad6854db.png)

**Environment (please complete the following information):**
 - TestCentric Version 1.4.0
 - OS: Windows 10
 - Target Runtime for your test assembly: .NET Framework 4.8,

**Comment by MahendraChoudhary** [comment]
Issue shows up while we disable shadow copy after assembly load. The reason after disabling shadow copy test reload gets called but doesn't no create new test package. Hence test will execute with older test package which has Shadow copy enabled. 

Workaround: Reload assembly (maybe browse) after disable/enable shadow copy from testcentric.

**Comment by CharliePoole** [comment]
In  that case, TestCentric should be asking you if you want to reload when you make the change, as it does for some other changes. I'll check that.

However, if your use of the `Location` property is the only reason you need to disable shadow copy, I suggest you just stop using it. NUnit provides the correct directory for you if you use `TestContext.CurrentContext.TestDirectory`. It works whether shadow-copy is on or off.

**Comment by MahendraChoudhary** [comment]
> In  that case, TestCentric should be asking you if you want to reload when you make the change, as it does for some other changes. I'll check that.
> _It does ask for reload, also reloadtests method gets called. But doesn't make new test package._
> However, if your use of the `Location` property is the only reason you need to disable shadow copy, I suggest you just stop using it. NUnit provides the correct directory for you if you use `TestContext.CurrentContext.TestDirectory`. It works whether shadow-copy is on or off.
> _Unfortunately I am using a third party DLL and that is using Location property._

**Comment by CharliePoole** [comment]
@MahendraChoudhary I've confirmed that this is working as you described. I'll need to investigate why that is so. Most likely, it's because the engine doesn't have reload functionality (it's not needed by the console runner) so the GUI is essentially trying to emulate a proper reload.
