### ISSUE TITLE
NUGET - Package 1.41 - testcentric.exe installation issue

### ISSUE THREAD

**Issue by JasonNewellAtAllegro** [TestCentric/testcentric-gui#604]
# Describe the bug
When trying to install the TestCentric Gui Runner through the Visual Studio 2017 Professional IDE package manager, testcentric.exe will not install though all other files seem to be ok.
 
![image](https://user-images.githubusercontent.com/72499516/95554194-ad17d080-0a07-11eb-992f-689a98ecfb87.png)

# To Reproduce
1. From within the Visual Studio IDE go to Project-> Manage Nuget Packages...
2. Search for the Test Centric GUI
3. Click on the install button
![image](https://user-images.githubusercontent.com/72499516/95555082-28c64d00-0a09-11eb-857e-c0c511fed417.png)

# Expected behavior
All the other packages install just fine, only this one has an issue.
Below is a list of the packages I have installed:
```
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="NUnit" version="3.12.0" targetFramework="net461" />
  <package id="NUnit.Analyzers" version="0.5.0" targetFramework="net461" />
  <package id="NUnit.Console" version="3.11.1" targetFramework="net461" />
  <package id="NUnit.ConsoleRunner" version="3.11.1" targetFramework="net461" />
  <package id="NUnit.Extension.NUnitProjectLoader" version="3.6.0" targetFramework="net461" />
  <package id="NUnit.Extension.NUnitV2Driver" version="3.8.0" targetFramework="net461" />
  <package id="NUnit.Extension.NUnitV2ResultWriter" version="3.6.0" targetFramework="net461" />
  <package id="NUnit.Extension.TeamCityEventListener" version="1.0.7" targetFramework="net461" />
  <package id="NUnit.Extension.VSProjectLoader" version="3.8.0" targetFramework="net461" />
  <package id="NUnit3TestAdapter" version="3.17.0" targetFramework="net461" />
</packages>
```

# Screenshots
If the bug is visual in nature, add screenshots to help explain your problem.	
![image](https://user-images.githubusercontent.com/72499516/95554415-0ed83a80-0a08-11eb-85c0-d7518959132a.png)
			
# Environment
 - TestCentric Version 1.4.1
 - Windows 10 Enterprise Version 1809
 - Target Runtime for your test assembly: .NET Framework 4.6.1

## Visual Studio
Microsoft Visual Studio Professional 2017 
Version 15.9.27
VisualStudio.15.Release/15.9.27+28307.1259
Microsoft .NET Framework
Version 4.8.03761

Installed Version: Professional

Visual C++ 2017   00370-20007-54903-AA371
Microsoft Visual C++ 2017

Application Insights Tools for Visual Studio Package   8.14.20131.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2017   15.9.04012.0
ASP.NET and Web Tools 2017

C# Tools   2.10.0-beta2-63501-03+b9fb1610c87cccc8ceb74a770dba261a58e39c4a
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

JavaScript UWP Project System   2.0
JavaScript UWP Project System

JetBrains ReSharper 2020.2.4   Build 202.0.20200925.65451
JetBrains ReSharper package for Microsoft Visual Studio. For more information about ReSharper, visit http://www.jetbrains.com/resharper. Copyright © 2020 JetBrains, Inc.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

MLGen Package Extension   1.0
MLGen Package Visual Studio Extension Detailed Info

NuGet Package Manager   4.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

TypeScript Tools   15.9.30718.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   2.10.0-beta2-63501-03+b9fb1610c87cccc8ceb74a770dba261a58e39c4a
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

Visual Studio Tools for Universal Windows Apps   15.0.28307.1259
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

xsd2code++   5.0
Advanced Code Generator From XML & JSON Schemas

**Comment by CharliePoole** [comment]
The error message indicates that nuget can't access the install path on your system. This could mean something is already installed there and can't be overwritten, possibly an earlier install of the GUI. Check it out manually.

Just a comment: it seems quite odd that you are installing four different ways to run tests in the same project: nunit3 console, testcentric gui, NUnit 3 adapter and resharper. Any conflict among the dlls used by those four runners will, of course, cause problems. However, most likely not this particular problem.

**Comment by CharliePoole** [comment]
This seems to be due to the problems we discussed in issue #603, which is now resolved.
