### ISSUE TITLE
misaligned Force Stop button

### ISSUE THREAD

**Issue by MartinZec** [TestCentric/testcentric-gui#648]
In version 1.5.3 the Force Stop button seems to be misaligned, it is printed above the run button
![force_stop](https://user-images.githubusercontent.com/44475413/103645733-ceca1a80-4f58-11eb-9be9-c9320851dce1.png)

**Comment by CharliePoole** [comment]
Fixed the layout and also increased the time delay before enabling the ForceStop button to 1000 ms to avoid accidentally clicking it.
