### ISSUE TITLE
Pluggable Agents

### ISSUE THREAD

**Issue by CharliePoole** [TestCentric/testcentric-gui#656]
Currently, the GUI engine includes the following agents:
* .NET Framework 2.0 (default for tests targeting .NET 2.0 through 3.5)
* .NET Framework 4.0 (default for tests targeting .NET 4.0 through 4.8)
* .NET Core 2.1 (default for tests targeting .NET Core 1.x or 2.x)
* .NET Core 3.1 (default for tests targeting .NET Core 3.x)
* .NET 5.0 (default for tests targeting .NET 5.0)

In addition to the defaults, the File menu may be used  to run tests under any compatible agent. For example, you may use the .NET 5.0 engine to run tests targeting any .NET Core version.

All of these agents are built-in. That is, they are included as part of the GUI package and the code for deciding which one to use is built into the TestAgency service.

A pluggable structure would simplify adding (and removing) agents and would allow users to create special-purpose agents of there own.

The general idea is to make each agent an extension, at least in form. A few agents would still be built-in, but would work like extensions internally. This is what we already do, for example, with the NUnit 3 framework driver. It's form is that of an extension, but all the code resides in the core assembly.

A pluggable agent would be an extension implementing a new interface. The interface would need to be published but might not have to be part of the nunit.engine.api assembly in order to avoid compatibility issues.

The interface would allow an agent to be passed a test package and decide whether it was able to run that package. All the current centralized code to decide what agent should be used would be replaced by a loop querying the available agents.

The above is merely the outline of a design... more work will be needed to firm it up.

This is a breaking change, so I'm assigning it to the next major release.

**Comment by CharliePoole** [comment]
@ChrisMaddock This is similar, I think, to what we have talked about for the NUnit engine.

**Comment by CharliePoole** [comment]
NOTE: I marked this breaking on the assumption that we would stop bundling some agents as a result of implementing this feature. If we continue to bundle all agents, then it's non-breaking.

**Comment by CharliePoole** [comment]
With the merging of PR #668, the code has now been reorganized so that each agent is independent and implements the `IAgentLauncher` interface. One result is that the agent launching code has a lot of repetition, which __could__ be factored out to a base class. However, I haven't done that because at least some of these will eventually be packaged separately and having them inherit implementation from the engine itself would make that more difficult.

Tentatively, I'm imagining separate packaging for the .NET Framework 2.0 and Mono launchers and leaving the .NET Framework 4.0, .NET Core 3.1 and .NET 5.0 launchers as built-ins. I could go either way on the .NET Core 2.1 launcher and would appreciate some input on how many people need it.

**Comment by ChrisMaddock** [comment]
> Tentatively, I'm imagining separate packaging for the .NET Framework 2.0 and Mono launchers and leaving the .NET Framework 4.0, .NET Core 3.1 and .NET 5.0 launchers as built-ins.

Totally agree with this - was about to post a similar issue on NUnit-side. Minor naming clarification, while we're restructuring: could we refer to them as the clrv2 and clrv4 agents, instead of .NET Framework 4.0 agent? We don't have the ability to target .NET Framework 4.0 - we're dependent on the version of the v4 CLR which is installed on the machine.

Is this something you'd be willing to port to the NUnit Engine as well, Charlie? I think it's key to being able to reduce support for the legacy platforms in a user-friendly way.

**Comment by CharliePoole** [comment]
@ChrisMaddock 

We can call them clrv2 and clrv4 if you prefer. However, I didn't name them based on how they would execute but how they are built:

Net20Agent - is built using `.NETFramework, Version=2.0` and can run under any clrv2 runtime.
Net40Agent - is built using `.NETFramework, Version=4.0` and can run under any clrv4 runtime.
Net45Agent - was (when I had one) built using `.NET Framework, Version=4.5` and could run under 4.5 through 4.8.

In the end, I decided that Net45Agent didn't add value, or at least not enough to justify maintaining it. But someone else could decide that they wanted, for example, a Net462Agent for some special reason.

As far as porting... yes... or actually more than just porting.

I consider what I'm doing as an experiment, which will eventually be implemented using the NUnit Engine. The GUI requires the nunit engine API to load an extension anyway. However, I think the engine needs a lot of modification to make this feasible and right now it's simpler to play around in the testcentric engine.

For me, the logical order of things is

1. Figure out where the NUnit engine is going, including my compatibility issues.
2. Decide whether I will eventually abandon the testcentric engine based on the outcome of (1)
3. If Yes, focus on the engine with you for a while to get it in shape for my own use
   3.1 Do the breaking release 4.
   3.2 Add the new features I need
   3.3 Go back to working on the GUI using the NUnit Engine for the 2.0 release

OR

3. If No, focus on the GUI
    3.1 Create my own API interfaces, alongside the NUnit interfaces
    3.2 Add stuff I need to the TestCentric engine
    3.3 Do the 2.0 Release of the GUI based on the testcentric engine

**Comment by ChrisMaddock** [comment]
Great! I think it's definitely going to be an advantage if we can reconcile these two engines, so I think we need to crack on with item 1. I see 4 outstanding issues in the project, I'll go comment on them now. 🙂
