### ISSUE TITLE
Create separate TestCentric API extending the NUnit API

### ISSUE THREAD

**Issue by CharliePoole** [TestCentric/testcentric-gui#672]
The _TestCentric / NUnit Engine Compatibility Project_ aims at removing some or all differences between the NUnit and TestCentric engines. As currently defined, we need to remove __all__ (or at least all significant) differences in order to stop having a separate engine.

As work progresses on the TestCentric 2.0 and NUnit 4.0 engines, it is becoming apparent - at least to me - that goal of switching back fully to the NUnit engine is not likely to be achieved in the next major releases, if ever.

So it seems like it's time to think about some kind of half measures. This idea is one of them. Other ideas are welcome.

I'm thinking we could continue to implement the NUnit engine api and add an additional api for testcentric-specific features. There are two ways to go on this: inherit our api from NUnit's or have them exist side by side... but that's really an implementation detail. However, I'm currently thinking of using inheritance unless it proves to be too limiting.

The big change would be that the GUI would use the NUnit engine package to incorporate the code of the engine. Our own implementations of a few features would live either side-by-side with NUnit's or be built on top of them. I think that choice has to be made feature-by-feature.

One key factor seems to be that all existing engine extensions using the NUnit API should continue to work correctly.

Because this is part of the Compatibility Project, I'm asking for comments from both teams. I'd appreciate your feedback on both whether you think this is possible and on specific implementation ideas.

@mikkelbu @immeraufdemhund @ChrisMaddock @jnm2 @rprouse

**Comment by CharliePoole** [comment]
I've done a preliminary spike to try to figure out what would be missed if I went back to using the nunit engine and how I could add back those features on top of it.

At the moment, it's pretty much out of the question because the NUnit engine is not really meant to be extended. The biggest feature we would lose in the GUI is the ability to run .NET Core tests.

My tentative conclusion is that it's not possible under NUnit 3.x but may be possible to do subsequent to the 4.0 release.

That said, I'd still like to hear from the @nunit/engine-team

**Comment by CharliePoole** [comment]
I've revisited this...

We really need to decouple progress in TestCentric from that of the NUnit engine. So any approach to extensibility has to allow for both the existing engine API and any future developments.

Here's an approach, which would seem to solve the problem. Comments please?

1. Continue to depend on the nunit engine api package, as we have done up to now. Some items will not work for us, as now. The GUI doesn't use them of course. If we end up publishing our engine as a package, the limitations of this API should be documented.

2. Create a testcentric api, with interfaces which may, in some cases, derive from those in the nunit API. It may not have all the same interfaces, of course, and some nunit interfaces may not be present at all. Design is needed here.

3. Create an extensibility api, containing interfaces used by those who write engine extensions. This may be packaged in a single assembly or in multiple assemblies by extension type. That's an important design decision to be made.

4. Initially continue to use our own implementations in the various `testcentric.engine.xxx` assemblies, but plan on replacing some or all of those with nunit's implementations whenever possible.

5. Plan on doing major releases whenever __either__ API has a significant change.

I'm now noting this as a planned 2.0 feature needing design. Comments from both teams are welcome before I start implementation in the next few weeks.

**Comment by ChrisMaddock** [comment]
> Create an extensibility api, containing interfaces used by those who write engine extensions. This may be packaged in a single assembly or in multiple assemblies by extension type. That's an important design decision to be made.

Not that this necessairliy needs to impact TestCentric's decision, but my spike for NUnit is separate assemblies per type, with a "core" assembly containing ITestPackage and some generic Extensibility classes.

**Comment by CharliePoole** [comment]
Yes, I knew that. :smile: I'd like to see how that turns out and I may spike the alternative myself.

**Comment by CharliePoole** [comment]
Closing this as "won't fix". The idea is possible but turns out to be much more complicated than I imagined. Two side by side APIs will be much easier to maintain and implementation classes can implement interfaces from both APIs if necessary.
