### ISSUE TITLE
Show CheckBoxes does not work

### ISSUE THREAD

**Issue by MartinZec** [TestCentric/testcentric-gui#673]
Hello,

In v1.6.1 right click -> "Show Checkboxes" does not show checkboxes. Same for 1.6.0.
With 1.5.2 it still worked.

**Comment by CharliePoole** [comment]
Confirming this as  reported.

**Comment by CharliePoole** [comment]
Decided this is "Critical" ... meaning there will be a 1.6.2 release even though I've been working on 2.0 lately.

**Comment by CharliePoole** [comment]
Closing manually - will release manually as well.
