### ISSUE TITLE
Credit for all contributors

### ISSUE THREAD

**Issue by CharliePoole** [TestCentric/testcentric-gui#7]
THis is  a placeholder for me to figure out how to ensure that all past contributors are getting properly credited.

**Comment by CharliePoole** [comment]
@Test-Centric/gui-team 
Before worrying about past contributors, I thought I should set up a page for current team members. See https://github.com/Test-Centric/test-centric-gui/wiki/Team-Members

You can send me material to add to the page or add it yourself. In either case, I may do some light editing. Keep the length down, as you would for a short bio when presenting at a conference. You can link to your blog or website or if you like create a longer personal page on the wiki itself.

**Comment by CharliePoole** [comment]
@ManfredLange @mikkelbu @immeraufdemhund @drSte I'd appreciate your input as to (1) whether you think this page is a good idea and, if it is, (2) what you'd like it to say about yourself.

**Comment by immeraufdemhund** [comment]
I do like the idea of the page. and I'll probably copy and paste my profile from linked in...

**Comment by drSte** [comment]
@CharliePoole it is a good idea for sure, I will add my info asap

**Comment by CharliePoole** [comment]
So... to wrap this up, here's the plan for crediting contributors...

1. Starting with the 1.0 final release, the release notes will list the names of everyone who contributed to the release.

2. The wiki "Team Members" page will have info about all of us. Question: Should we possibly rename it and add non-team-member contributors as well? Or should that be another page?

3. I updated my own entry for that page to include social media links. The images directory now has svg files for Twitter, GitHub, Facebook and LinkedIn. I posted my GitHub and Twitter, but feel free to use whatever you want, copying the html from my entry and editing online.

4. I'm thinking of loosening up the "Contributors" team to invite anybody who has had a PR accepted and to continue to do that as new people come along. That role has no special permissions but we can add them to the issue and their names at least show up in GitHub. What do you all think?

With the exception of the questions, I think that wraps up this issue. But for now, I'll leave it open for comments and any new ideas.

**Comment by mikkelbu** [comment]
Regarding 2 my only fear is that it is could be a lot of work to add/update all this information, but until now the number of contributors has not been that large.

Regarding 4 then I don't see a problem with this. Another approach could be to use the new github feature that enables "Assign issues to issue commenters", see https://github.blog/2019-06-25-assign-issues-to-issue-commenters/ . I guess that being part of the "Contributors" is more special than "just" being assigned to an issue, but it will also be a bit more work for us. In both cases the user will also be mentioned in the release notes.

**Comment by CharliePoole** [comment]
@mikkelbu Both good points. On 2, we can start with just what we have. On 4, I'll give that new feature a try. (I can't keep up with the features!)

**Comment by CharliePoole** [comment]
Closing this in anticipation of the actions being taken on the release- otherwise, it won't be listed!

**Comment by ManfredLange** [comment]
A bit late to the party. However, I think having a place to give credit to contributors is a great idea. Where and how is a different question. Yes, it could be in the UI itself or it could be on the wiki for this repo. And if there are contributors that are not members, perhaps we could list them as well somewhere. I've seen projects/products that have listed dozens of contributors. (Perhaps they even automated that based on commit information, e.g. when a PR is accepted?)

**Comment by immeraufdemhund** [comment]
I really liked one approach which I think it was in vscode's release notes or something similar where they would mention a new feature with a  issue number referenced and then in parens they would say something like (Thank you @CharliePoole  for your pull request). 

example:
 - issue #7 add contributors to github wiki (Thank you @CharliePoole for your hard work)

**Comment by CharliePoole** [comment]
@immeraufdemhund That's worth a try. Not sure it's workable for the initial release, but maybe for the point releases that follow. 

In any case, there are enough ideas here that I'll have you all comment on the release merge before I go with it.

**Comment by CharliePoole** [comment]
@ManfredLange Having the App itself do itis a cool idea. I've seen this as a tab or link on the About box.
