### ISSUE TITLE
Specify test run parameters on command-line

### ISSUE THREAD

**Issue by CharliePoole** [TestCentric/testcentric-gui#706]
This came up in the discussion of #703 as something that may be useful.

We should allow syntax similar to NUnit-Console...

```
--param name=value OR
-p name=value
```

Each use may only supply one parameter but the option may appear multiple times. The entire list is added  to the TestPackage on load and remains active unless the user makes changes in the GUI parameters dialog.

**Comment by CharliePoole** [comment]
@YashUoM Would you be interested in working on this?

**Comment by YashUoM** [comment]
Sounds great. But my schedule is pretty packed up till the middle of June. After that I can work on this. :)

**Comment by CharliePoole** [comment]
That would be great.

**Comment by CharliePoole** [comment]
@YashUoM Are you still interested in working on this? I'm looking at growing the team so it's not so dependent on me!

**Comment by YashUoM** [comment]
Hi Charlie, 
How is the deadline for this?

**Comment by YashUoM** [comment]
I can work 6-10 hours a week given my day job taking my week days. If that's enough I'll start on this. :-)

**Comment by CharliePoole** [comment]
Definitely! I have assigned it to you. I'll add you to the team as well, which will give you commit authority, but I want to send you some info about how we operate first. My email is charliepoole AT gmail DOT com - if you send me a note at that address, I'll reply with what you need to know to get started.

**Comment by immeraufdemhund** [comment]
nice :D
________________________________

**Comment by CharliePoole** [comment]
@immeraufdemhund Indeed! But still plenty of stuff left to do if you feel like becoming active again. :-)

**Comment by YashUoM** [comment]
Sure. Will drop a mail. And I copied your mail. You can remove it from the comment if you want. :-)

**Comment by CharliePoole** [comment]
I'm reopening this. The code I added does solve the problem, but it turns out it isn't being called in the case where options are entered on the command-line - the specific case I was trying to deal with!

Underlying this is the fact that creation of the test package resides within the model assembly as does the definition of the supported command-line options. There is a need for some serious refactoring to get these definitions to live where they belong, but that's a good thing as it will simplify the model.
