### ISSUE TITLE
Crashing Testcentric on trying to change Process Model to X86

### ISSUE THREAD

**Issue by gps7** [TestCentric/testcentric-gui#719]
**Describe the bug**
Exception shown when trying to change the Process Model to X86 after closing the test project.

**To Reproduce**
1. Go to 'File' and Open and choose a test project
2. Click on 'File' then close the test project
3. Click on 'File'  then Process Model and choose "Run as X86" option

**Expected behavior**
No exception to be shown.

**Screenshots**
![2021-06-16 Testcentric error shown for menu](https://user-images.githubusercontent.com/21167960/122225276-97737880-cebd-11eb-8ec0-b667c98f2777.JPG)
![2021-06-16 Testcentric exception](https://user-images.githubusercontent.com/21167960/122225307-9e01f000-cebd-11eb-873a-8c00c45d9a73.JPG)

**Environment (please complete the following information):**
 - TestCentric Version 1.4.1
 - OS: Windows 10
 - Target Runtime for your test assembly: .NET Framework 4.6.1

**Error stack trace:**
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at TestCentric.Gui.Presenters.TreeViewPresenter.<>c__DisplayClass10_0.<WireUpEvents>b__1(TestNodeEventArgs e) in C:\Users\charlie\dev\TestCentric\testcentric-gui\src\TestCentric\testcentric.gui\Presenters\TreeViewPresenter.cs:line 80
   at TestCentric.Gui.Model.TestNodeEventHandler.Invoke(TestNodeEventArgs args)
   at TestCentric.Gui.Model.TestModel.LoadTests(IList`1 files) in C:\Users\charlie\dev\TestCentric\testcentric-gui\src\TestModel\model\TestModel.cs:line 242
   at TestCentric.Gui.Presenters.TestCentricPresenter.ChangePackageSettingAndReload(String key, Object setting) in C:\Users\charlie\dev\TestCentric\testcentric-gui\src\TestCentric\testcentric.gui\Presenters\TestCentricPresenter.cs:line 765
   at System.Windows.Forms.MenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.MenuItem.MenuItemData.Execute()
   at System.Windows.Forms.Command.Invoke()
   at System.Windows.Forms.Control.WmCommand(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4300.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
testcentric
    Assembly Version: 1.4.1.0
    Win32 Version: 1.4.1
    CodeBase: file:///D:/_SOFTWARE/NUnit%203%20GUI/tools/testcentric.exe
----------------------------------------
TestCentric.Gui.Runner
    Assembly Version: 1.4.1.0
    Win32 Version: 1.4.1
    CodeBase: file:///D:/_SOFTWARE/NUnit%203%20GUI/tools/TestCentric.Gui.Runner.DLL
----------------------------------------
TestCentric.Common
    Assembly Version: 1.4.1.0
    Win32 Version: 1.4.1
    CodeBase: file:///D:/_SOFTWARE/NUnit%203%20GUI/tools/TestCentric.Common.DLL
----------------------------------------
nunit.engine.api
    Assembly Version: 3.0.0.0
    Win32 Version: 3.11.1
    CodeBase: file:///D:/_SOFTWARE/NUnit%203%20GUI/tools/nunit.engine.api.DLL
----------------------------------------
TestCentric.Gui.Model
    Assembly Version: 1.4.1.0
    Win32 Version: 1.4.1
    CodeBase: file:///D:/_SOFTWARE/NUnit%203%20GUI/tools/TestCentric.Gui.Model.DLL
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4270.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4300.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
testcentric.engine
    Assembly Version: 1.4.1.0
    Win32 Version: 1.4.1
    CodeBase: file:///D:/_SOFTWARE/NUnit%203%20GUI/tools/testcentric.engine.DLL
----------------------------------------
testcentric.engine.core
    Assembly Version: 1.4.1.0
    Win32 Version: 1.4.1
    CodeBase: file:///D:/_SOFTWARE/NUnit%203%20GUI/tools/testcentric.engine.core.DLL
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4320.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Web
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4330.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------
System.Runtime.Remoting
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Remoting/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Remoting.dll
----------------------------------------
TestCentric.Gui.Components
    Assembly Version: 1.4.1.0
    Win32 Version: 1.4.1
    CodeBase: file:///D:/_SOFTWARE/NUnit%203%20GUI/tools/TestCentric.Gui.Components.DLL
----------------------------------------
nunit.uiexception
    Assembly Version: 1.4.1.0
    Win32 Version: 1.4.1
    CodeBase: file:///D:/_SOFTWARE/NUnit%203%20GUI/tools/nunit.uiexception.DLL
----------------------------------------
testcentric.engine.metadata
    Assembly Version: 1.4.1.0
    Win32 Version: 1.4.1
    CodeBase: file:///D:/_SOFTWARE/NUnit%203%20GUI/tools/testcentric.engine.metadata.DLL
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by CharliePoole** [comment]
Error is present in 1.4.1 and in the latest release as well.

**Comment by CharliePoole** [comment]
Scheduling this for the 2.0 release. The menus are changing for that release, but the problem still exists and needs to be fixed.

Basically, it was not intended that the `Run as X86` menu item should be enabled when no test is loaded. Initial load for all tests uses the default platform for which the test assembly was built.

Several other menu items in addition to this one need to be disabled when no test is loaded.
