### ISSUE TITLE
Save of Process model option X86 lost after restart of app

### ISSUE THREAD

**Issue by gps7** [TestCentric/testcentric-gui#722]
**Describe the bug**
Selection of the Process model Run as X86 option is lost after close and open the test centric application. 

**To Reproduce**
1. Go to File and choose Open open any test project
2. Click on File and choose option Run as X86 under Process Model menu
3. Close test centric application
4. Launch the application. The test centric will open last project
5. Check menu File -> Process Model selection

**Expected behavior**
Selection of process model should remain after restart of testcentric application

**Environment (please complete the following information):**
 - TestCentric Version 1.4.1
 - OS: Windows 10
 - Target Runtime for your test assembly: .NET Framework 4.6.1

**Comment by CharliePoole** [comment]
This is intended behavior. When a test assembly is opened, it uses either the standard or the x86 driver depending on the platform for which it was compiled. Sometimes, when a test not compiled for x86 references an assembly requiring 32-bits, it is necessary to run it using the x86 option but this information is not saved by NUnit. In fact, NUnit does not currently save any information about settings used to run an assembly.

The workaround in this case is to use the `--x86` command-line option when running TestCentric.

A future version will include the ability to save a test run with all it's settings. See #3
