### ISSUE TITLE
Multiple loaded files have no root in tree

### ISSUE THREAD

**Issue by CharliePoole** [TestCentric/testcentric-gui#73]
When multiple test assemblies are opened, they are displayed in the tree as separate roots. That is, there is no common root as in V2. Consequently, to run all the tests using the Run button, the user must enable checkboxes and select each root.

Since this version of the gui is intended to be similar to V2, the easy solution would be to provide an artificial root in the tree, which is selected by default. That's my preference.

One alternative would be to provide a separate "Run All" button.

What do folks think?

**Comment by mikkelbu** [comment]
I'm also for the "artificial root"

**Comment by CharliePoole** [comment]
Sounds like we need the root for those who click and the shortcuts as well.

**Comment by CharliePoole** [comment]
I'll add a common root to match the root node that is already present in the test structure. It will only display when there is more than one child.
