### ISSUE TITLE
Get the Mini-Gui working fully

### ISSUE THREAD

**Issue by CharliePoole** [TestCentric/testcentric-gui#768]
The mini-gui basically works, i.e. it shows the menu, toolbar, progress bar, tree and status bar. However, there is no way to look at test properties, XML, test output, etc. - all the things shown in the right-hand pane of the full gui.

**Comment by CharliePoole** [comment]
@rowo360 Would you mind trying out the mini-gui? Is there anything you can see, which should be added to the list in the comment avove?

**Comment by rowo360** [comment]
I took a detailed look at the Mini GUI. Overall, I have the impression that no important functionality is missing. I expect that in case of a test error, the user wants to quickly identify the root cause - this will be adressed by the last point of the list.
