### ISSUE TITLE
Icon and Logo for TestCentric

### ISSUE THREAD

**Issue by CharliePoole** [TestCentric/testcentric-gui#8]
Currently using NUnit's but we should have our own.

**Comment by CharliePoole** [comment]
![testcentric_logo](https://user-images.githubusercontent.com/2678661/61446370-e9fd3080-a946-11e9-9043-8a07af7a3889.png)

@TestCentric/gui-team What do you think of the above? Any color suggestions?

**Comment by CharliePoole** [comment]
For the icon, I'm thinking of just the "T" and "C"

**Comment by immeraufdemhund** [comment]
I would like to see the colors from NUnit incorporated somehow. either the "est" and "entric", or the other way around.

**Comment by CharliePoole** [comment]
Here are some samples of both the logo and the icon image...

[TestCentric Logos and Icons.pdf](https://github.com/TestCentric/testcentric-gui/files/3410519/TestCentric.Logos.and.Icons.pdf)

I felt that the fourth logo (mixed black and green) was a bit odd looking. My favorites are the white text on green background, just like NUnit, for both the logo and the icon.

This is all text work with various fonts, by the way, I'll make an image out of the best ones.

**Comment by CharliePoole** [comment]
@immeraufdemhund @mikkelbu @drSte What do you think? I'd like to move ahead with creating bitmaps in the various forms and sizes needed...

Full logo with text... one or two sizes
Logo with just TC... various sizes, need 128x128 for about box
Icon... with multiple sizes

I'll do all of the above in black on white as well as white on NUnit green and stash them on GitHub for ease of access, probably in a subdirectory at the top level.

**Comment by immeraufdemhund** [comment]
Can we do svg so it scales well?

**Comment by immeraufdemhund** [comment]
As for logo I agree with the green on white.

**Comment by CharliePoole** [comment]
@immeraufdemhund The icons for Windows have to be ico files, of course. For he web, svg would be good if I knew how to make it. Maybe if I make a png somebody will convert. (Is that possiblle? Seems like it takes a bit of analysis to deduce vectors from a bitmap.)

**Comment by immeraufdemhund** [comment]
I know just enough to make the svg, it would be easier if I  knew font. I think it is possible to convert ico from svg but I'd have to research

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by CharliePoole** [comment]
The ico starts out as a bitmap, which I can save in any format. I'll move ahead with what I know how to do anyway.
