### ISSUE TITLE
System.ArgumentException: 'Unknown .NET Core version: 6.0 Parameter name: version'

### ISSUE THREAD

**Issue by jmecosta** [TestCentric/testcentric-gui#821]
Suppose because i have installed VS 2022 preview, might have come with some .net core version 6.0.

Probably that needs support from the tool side, but bad that the existing last version just crashes in my machine

This exception was originally thrown at this call stack:
    TestCentric.Engine.Runtime.NetCoreRuntime.GetClrVersionForFramework(System.Version) in Runtime.cs
    TestCentric.Engine.RuntimeFramework.RuntimeFramework(TestCentric.Engine.Runtime, System.Version, string) in RuntimeFramework.cs
    TestCentric.Engine.Services.RuntimeFrameworkService.GetNetCoreRuntimesFromDirectoryNames(System.Collections.Generic.IEnumerable<string>) in RuntimeFrameworkService.cs
    TestCentric.Engine.Services.RuntimeFrameworkService.FindDotNetCoreFrameworks() in RuntimeFrameworkService.cs
    TestCentric.Engine.Services.RuntimeFrameworkService.StartService() in RuntimeFrameworkService.cs
    TestCentric.Engine.Services.ServiceManager.StartServices() in ServiceManager.cs
    TestCentric.Engine.TestEngine.Initialize() in TestEngine.cs
    TestCentric.Engine.TestEngine.NUnit.Engine.ITestEngine.Services.get() in TestEngine.cs
    TestCentric.Gui.Model.TestServices.TestServices(NUnit.Engine.ITestEngine) in TestServices.cs
    TestCentric.Gui.Model.TestModel.TestModel(NUnit.Engine.ITestEngine, string) in TestModel.cs
    ...
    [Call Stack Truncated]

**Comment by CharliePoole** [comment]
I agree. I'll make this bug about eliminating the crash and create a new issue about actual support for 6.0

**Comment by CharliePoole** [comment]
This is critical so I'll do a new alpha release as soon as I get another fix I'm working on merged. Meanwhile, use this build...

https://www.myget.org/feed/testcentric/package/nuget/TestCentric.GuiRunner/2.0.0-dev00048

**Comment by jmecosta** [comment]
It's all good, I have patched the code locally 😉. Take your time. And
thanks for the quick fix

**Comment by CharliePoole** [comment]
I've actually created a branch with .NET 6.0 support... see issue #823 

For reasons stated on the issue I won't merge it yet but anyone interested can check out the branch.

**Comment by Kuinox** [comment]
Hello,
I got the same issues, but with version 7 ^^.
I have the .NET 7.0 SDK installed.

**Comment by CharliePoole** [comment]
This issue was left somewhat orphaned when the engine was separated from the gui! Transfering to testcentric-engine project.

**Comment by CharliePoole** [comment]
See PR TestCentric/testcentric-engine#40 for the 7.0 question.

**Comment by Kuinox** [comment]
Thanks, I didn't knew there was an engine repo and only searched in this repo :D
