### ISSUE TITLE
Design basic format and save info about the current package using that format

### ISSUE THREAD

**Issue by CharliePoole** [TestCentric/testcentric-gui#835]
Part of Epic #3

In the GUI, all the test files we have opened, together with their settings, constitute a test package. `TestPackage` is defined in the engine API and created and maintained by the GUI model. The model maintains the current TestPackage as a property of the same name. It also maintains private info used to regenerate the test package when necessary, but that should not be an issue in the case of this issue.

We want the model to be able to save a TestPackage. For the purposes of this initial issue, it's OK if we only save the names of the test files (assemblies and projects) because that will drive us to create a format. In designing the format, we should take into account that each package has its own settings.

TestPackage is actually a tree structure. The top-level package is anonymous and contains a sub-package for each file we have opened. Assembly files are terminal packages but projects have their own sub-packages. Every level may have settings. So the format of the file we create has to be tree-based.

Key decision is whether to use XML or JSON. I lean toward JSON because it's used more frequently these days in the dotnet world. A lot of our files use XML currently, however, and we could stick with that if it seems better.

@YashUoM I'm assigning this to you after our talk today. I'd like to see a rough design as a comment here, but it can be __very__ rough. Just an indication of how you are starting.

@TestCentric/gui-team Feel free to chime in via comments with any ideas you have about this issue or about #3 as a whole.

**Comment by YashUoM** [comment]
Hi Charlie, 

This is the json format I thought of so far. I came up with this thinking it'll be beneficial to keep both the dll and the test params packed together so we can load them without having to add the test params again. I'm not 100% clear about the settings you're talking about here. Is it same as test params?

`[
   {
      "project_01":{
         "Date":"2021-10-30",
         "TestCentric-GUI.dll":{
            "Test Parameters":{
               "Param_01":{
                  "Value":"Value_01"
               },
               "Test Parameters":{
                  "Param_02":{
                     "Value":"Value_02"
                  }
               }
            }
         },
         "TestCentric-GUI2.dll":{
            "Test Parameters":{
               "Param_01":{
                  "Value":"Value_01"
               },
               "Test Parameters":{
                  "Param_02":{
                     "Value":"Value_02"
                  }
               }
            }
         }
      },
      "project_02":{
         "Date":"2021-10-30",
         "TestCentric-GUI.dll":{
            "Test Parameters":{
               "Param_01":{
                  "Value":"Value_01"
               },
               "Test Parameters":{
                  "Param_02":{
                     "Value":"Value_02"
                  }
               }
            }
         }
      }
   }
]`

**Comment by CharliePoole** [comment]
I'm not clear what "project_01" and "project_02" represent. Are they names of files?

A package is a set of files and settings. Each file becomes a subpackage and for some kinds of files it may have it's own settings specified. Higher level settings are inherited at the lower levels. In theory, the hierarchy could be without bound but in current implementation we only have three levels...

1. The top level, which is the list of files from the command line or opened by the GUI.
2. The second level, representing each individual file, either projects or assemblies
3. For any project file, the third level, consists of the the contained assemblies.

An example...

testcentric.exe test1.dll test2.dll test3.dll --option1 --option2

Command line (unnamed) package with settings derived from the specified options
    test1.dll package (Each dll has the settings from the commandline plus any added by the engine, e.g. target framework.)
    test2.dll package
    test3.dll package

Another example...

testcentric.exe project.nunit anotherproj.csproj test.dll

Unnamed package
    project.nunit with settings pulled from the project file
        one entry for each assembly specified in the project file
    anotherproj.csproj with some settings of its own
        one or more (in case of multiple targets) assembly entries
    test.dll

It looks complicated but in fact, you only have to deal with one project at a time, recursively. Have you looked at the definition of a TestPackage? That should drive your structure.

Regarding test run parameters... They are just one of many settings...

Also, note that the naming of settings is intended to be extensible, so your format can't limit itself to certain settings only.

IIRC, there's a way to generate a json file from a class definition. Maybe that's the way to start out....

**Comment by CharliePoole** [comment]
A note to clarify what we want to save...

Currently...

* TestResult file has the results from running a test
* Visual State file has stuff pertaining purely to the GUI like which nodes are expanded and visible, what is selected, etc.
* For nunit projects, the list of assemblies is saved along with some setttings (only the permanent ones for that project)
* Other settings are not saved at all

What we want...
* Keep using TestResult file for the results
* Keep using Visual State file for the GUI stuff and improve it
* Save a list of files (both projects and assemblies) as well as all settings (set by user or created by the engine)
* As a final step, tie all three together in some way so that we can re-open a package and have access to the files and settings, the visual state and the latest result.

This issue, of course, is only about the package itself, i.e. files and settings.

Note: the package files will also be used by our console runner in the future.

**Comment by CharliePoole** [comment]
This has not been worked on for a long time, so I'm re-stating what is needed and changing direction a bit.

Epic #3 indicates that this file should contain the names of assemblies and project. That should be extended to properties. In other words, it should contain all the info needed to restore a TestPackage object in memory as it was at the time the file was saved.

Since we already have related files using XML and I'd like to complete the issue as soon as possible, I'll stick with XML for this file.
