### ISSUE TITLE
Convert command-line processing to latest version of Mono.Options

### ISSUE THREAD

**Issue by CharliePoole** [TestCentric/testcentric-gui#836]
We are currently using a slightly modified copy of the source code for an older version. Better to use the available package and modify our own code to work with it as needed.

**Comment by CharliePoole** [comment]
@TestCentric/gui-team So it comes down to a choice... Use source as we have been doing or stop using strong naming for the assembly.

In the long term, I'm pretty sure that strong naming is going to be obsolete, but in the short term many people keep using it for their .NET Framework apps and occasionally users want to call our code from their strong-named code. 

I think I'm ready to start moving away from it to some extent. I propose eliminating strong naming for the two TestCentric.Gui assemblies (the exe and the dll that has the actual code). For now at least, the model would cotinue to be strong named. That's the only one I would encourage people to reuse anyway.

Thoughts?

**Comment by mikkelbu** [comment]
I think this make sense 👍 (but this is just answered with limited knowledge about strong naming)

**Comment by CharliePoole** [comment]
@mikkelbu Will you continue with this or should I do it?
