### ISSUE TITLE
Double click test to start

### ISSUE THREAD

**Issue by MartinZec** [TestCentric/testcentric-gui#851]
version 1.6.2.0: a test was started/triggered by double clicking
version 2.0.0.-alpha4: a double click on a test does not start/trigger a test

is this behavior wanted/expected?

**Comment by gps7** [comment]
That's correct, double click on test does not work anymore.

**Comment by CharliePoole** [comment]
Noting that this is once again broken. See issue #138 and PR #167

**Comment by CharliePoole** [comment]
This appears to have been broken when we switched to using the former experimental UI and has remained so through the Alpha 2, 3 and 4 releases. There's a change in the new UI in how events are handled and this one didn't immediately fit in so it was "temporarily" removed and stayed that way until now.

I've made a quick and dirty fix, adding a new TreeNodeDoubleClick event to the view.
