### ISSUE TITLE
Assembly Reload: "Reload before each test run" does not work

### ISSUE THREAD

**Issue by MartinZec** [TestCentric/testcentric-gui#852]
version 2.0.0.-alpha4: I checked "Reload before each test" run in the settings.
In case I press CRTL+R  I see a small window with "Reloading...", so reloading works.
In case of executing one test twice consecutively, no "Reloading" window is appearing, although "Reload before each test run" is checked.

**Comment by CharliePoole** [comment]
Confirmed. The method doing the reloading is no longer called.

**Comment by CharliePoole** [comment]
Restructured code so reload is done by the model, where all calls to run tests converge.
