### ISSUE TITLE
test duration time is changing

### ISSUE THREAD

**Issue by MartinZec** [TestCentric/testcentric-gui#853]
version 2.0.0.-alpha4: I have a simple and fast test. 
In case Testcentric is idle for about 15 seconds and I start the test, the test duration is 0.1s (bottom right "Duration:").
In case I execute the test immediately again after I got the test verdict, the test duration (bottom right "Duration") is  7 seconds. 

In the test properties I can see that the Elapsed Time is always very similar in both above mentioned cases, about 0.04 seconds.

Are there some background processes delaying the next test, after the verdict of the first test is done already?

**Comment by CharliePoole** [comment]
Can you try this using the latest development release on the MyGet feed?

**Comment by MartinZec** [comment]
I did not find the MyGet feed, can you please share a link or a file?

**Comment by CharliePoole** [comment]
The testcentric feed is at https://www.myget.org/F/testcentric/api/v3/index.json

**Comment by MartinZec** [comment]
I used alpha4 and replaced the files available at MyGet feed.
By this I can still observe the issue.

**Comment by CharliePoole** [comment]
What do you mean by "replaced the files"? Normally, you  would just install the latest package rather than alpha4. Currently, that's 2.0.0-dev00094. If you're using nuget.org, just add the myget feed to your list of nuget sources.

**Comment by MartinZec** [comment]
Yes, I figured it out afterwards, I used the dev00094, there I saw the same issue.

**Comment by CharliePoole** [comment]
OK... that makes it easier for me to replicate in the latest master.

**Comment by MartinZec** [comment]
not seen anymore in dev00112

**Comment by CharliePoole** [comment]
I'll mark it fixed then!
