### ISSUE TITLE
Need a better way to run a subset of the tests

### ISSUE THREAD

**Issue by MartinZec** [TestCentric/testcentric-gui#854]
version 2.0.0.-alpha4: 
I enabled "Show checkboxes" and checked a few tests. A different test is marked, but not checked.
After executing "Run Selected F6", the only the marked test is executed and not the test which are checked in the checkbox.

**Comment by CharliePoole** [comment]
By "marked" do you mean the test is highlighted, as when you select it? 

Up to now, I have tried to maintain alternate ways of selecting tests, even when checking is enabled. Maybe we need both "run Selected" and "Run Checked".

**Comment by MartinZec** [comment]
Yes, "marked" is selected with the mouse, so it will appear with a blue background. 

In 1.X release I could use the checkbox and then the checked test were executed. This behavior changed in 2.X, so only the highlighted test (and there can be only one test highlighted, it does not work to highlight more with CTRL) is executed.
With 2.X currently, if I would like to test a specific subset of tests, there is no option to select them manually.

**Comment by gps7** [comment]
I got confused with all these settings, the previous version was more or less clear. I've checked only 1 test out of 3 and selection remained on same checked one but after clicking on toolbar run tests (green arrow) it executed all tests! Why it did when I did not asked for this?
Additionally, double click on test independently from check state was executing the double clicked tests, this does not work at all with v2. I kind of nowhere with TC since old version is often crashing, the new one is not working correctly but at least is more stable.

**Comment by gps7** [comment]
After check it turned out that this Run command on toolbar is Run All. However, switching to checkbox tests run all means run all checked. This is confusing, why should I run really all tests including unchecked ones?

**Comment by CharliePoole** [comment]
@gps7 The problem you see with the toolbar command is definitely a bug. This issue is about the Run Selected menu command. However, I think they all need to be looked at together anyway, sRo I'm changing the issue title.

So, this issue will deal with...
* Running a single selected test, fixture or other suite.
* Running a set of checked tests
* Running all tests in the assembly

Each of the above should be available from the toolbar, from the menu and as a shortcut.

**Comment by CharliePoole** [comment]
### Current Behavior (latest master as opposed to alpha 4)

#### Running All Tests

* Works with toolbar button. Tests | Run All and F5.

* All tests are run whether check boxes are enabled or not.

#### Running a single selected Test

* Works with toolbar button (dropdown: Run Selected), Tests | Run Selected and F6.

* Can also use context menu.

* Can also double-click a single test case.

* Check boxes are ignored

#### Running Checked Tests

* There is no longer any way to run checked tests.

* The code contains a Run Checked Tests command as part of the context menu but it remains hidden even when checkboxes are enabled.

**Comment by CharliePoole** [comment]
### Alternatives

1. Eliminate check boxes entirely. If we do this, we need to implement multiple selection via CTRL and SHFT.

2. Eliminate selection via clicking on the node and always use checkboxes.

3. Continue to support both selection and check boxes but only use one at a time. If checkboxes are turned on, disable selection.

4. Support both at the same time, with separate commands. This includes fixing the context menu as well.


@TestCentric/gui-team @MartinZec What do you think?

**Comment by CharliePoole** [comment]
PR #864 reinstates the context menu items for running checked tests. This will give temporary relief to anyone using the checks while we work on a longer-term solution. The fix is available from our myget feed as version 2.0.0-dev00101 or higher.

**Comment by CharliePoole** [comment]
__NOTE:__ I'll wait a few more days for comments on the alternatives I listed above as a final fix. If I don't receive any, I plan to go with the following approach, which is actually a variation of alternative 2...

### General Approach

Present selected tests in a unified way. If tests are checked, they are by definition selected. If tests are selected (by clicking) they can be shown as checked if checkboxes are displayed.

### Rationale

__Test Selection__ is a logical concept. The techniques we have used in the past are actually two ways of selecting tests, that is, by use of a check box or by use of a single click on an item, possibly combined with the CTRL or  SHIFT keys. Users tend to be confused by having two different "selections" in the form of (1) the currently selected test and (2) any checked tests. It makes sense to have only one test or group of tests selected, no matter which approach is used.

### Details

1. Check boxes will continue to be optional.

2. If check boxes are __not__ displayed, tests will be selected by clicking on them. Multiple tests may be selected via CTRL and SHFT although that enhancement may come after the initial implementation. Currently selected tests will be shown as highlighted in the tree.

3. If checkboxes __are__ displayed, tests will be selected by clicking on the check box __or__ by clicking on the item itself. In either case, the checkbox will be checked upon clicking. Once we implement use of SHIFT and CTRL, they will apply to checkboxes as well. Curretnly selected tests will be shown as checked, without highlighting.

4. If the user switches between use and non-use of checkboxes, the currently selected test or tests will not change.

Obviously, some of the details could change in the process of implementation.

**Comment by CharliePoole** [comment]
PR #865 is a refactoring step, eliminating the use of a TreeViewElement to hold the TreeView and having the view (TestTreeView) handle the control directly. The view now has additional methods and properties, so the Presenter no longer has to drill down below the view level to manipulate the tree.

**Comment by MartinZec** [comment]
As I understand it, point 2. and 3. will do the same, regardless of checkboxes enabled or disabled, the only addition is using the checkbox, which will be the same as selecting the test(s) by selecting (click-on-testname).

To your comment: "tests will be selected by clicking on the check box or by clicking on the item itself.":
I think it would be more intuitive and maybe also easier to implement: to limit the checkboxes use case to only enable the click on a check box and to not add a "check" in case the test is selected by click-on-testname.
In other words: for enabling a check box, the box need to be checked, not by click-on-testname-selection.

In general for test execution and selection:
In my point of view, it makes sense to enable test execution by double click on the test name, where checkboxes are completely ignored.
For the "Run" button:
In case of no check boxes enabled, only the selected test (or a test group) is executed, no need of SHIF+CTRL selection, since this will be covered by checkboxes. In this case it would not be possible to execute a subset of tests of several test groups (namespace).
Finally, for checkboxes, all checked tests should be executed, regardless of any selection (click-on-testname).

**Comment by CharliePoole** [comment]
@MartinZec I sent you an invitation to join the TestCentric Gui team. You've already turned up a number of useful bugs and come up with ideas for improvement, so I'd like to recognize that and encourage you to continue. If you accept, I'll be asking you to look at some specific issues regarding the UI. Depending on time available and your background, you could also work on coding some fixes for problems you find.

**Comment by MartinZec** [comment]
@CharliePoole Thank you for the invitation. I am not sure how much time I can spend, but I will for sure continue reporting my findings.

**Comment by CharliePoole** [comment]
@MartinZec Great! Send me an email to charliepoole AT gmail and I'll send you some introductory info.

**Comment by CharliePoole** [comment]
As the next step in implementing the approach above, I created a custom tree control supporting multiple selection. It works. But unfortunately it highlights a bit of a conceptual problem I hadn't considered before.

Up to now, selection in the tree by clicking has served two purposes:

1. It determines which test (now tests) will be run.
2. It determines which test will be displayed in the properties tab.

All the discussion up to now was about item 1, not item 2.

So, if we enable multiple selection, how do we handle the properties display? Here's what comes to mind for me...

* Display the single item selected by a click without CTRL or SHIFT.
* Display the topmost item in the tree - or some other logic based on tree position.
* Create an aggregated pseudo-item on the fly - a lot of work for little benefit IMO.

Another approach, different in kind, would  be to abandon multiple selection other than using checkboxes. That is...

* If checkboxes are enabled, let it continue to work as it now does, along with fixes to problems already identified. "Normal" item selection would be used to chose the "focus item" to be displayed in the tab.
* If checkboxes are not enabled, only one test at a time may be selected.

Whichever of the above we pick will clearly need refinement. What I'd like to hear is which general approach makes the mos sense to users.
* If checkoxes

**Comment by MartinZec** [comment]
For me the second approach sounds better.
By using checkboxes, a user has an interface to run multiple tests, if needed.
In case of no checkboxes are enabled, only one test can be execute, which would simplify the multiple selection (CTRL+SHIFT) topic.

**Comment by CharliePoole** [comment]
@MartinZec That's the way I'm leaning... I'm even wondering if we should just use checkboxes all the time, i.e. make them non-optional. But it's easy enough to retain the option for now and decide whether to go further in a future alpha.

**Comment by MartinZec** [comment]
For me the best solution is to have check boxes optional. 
Having them permanently opens the question if the checked checkboxes should be saved and re-loaded when the GUI is closed and re-opened. This might lead to the need of "uncheck all", an additional step, in case only one test should be executed (which is for me the most common use case).

**Comment by CharliePoole** [comment]
I made substantial changes to the GUI and merged them so that they can be more easily tested. @MartinZec could you please take that on? I'll leave this issue open until you have reviewed the changes.

### What's Changed

The portion of the UI related to selecting and running tests has been changed.

* The entire `Test` menu has been removed
* Separate buttons are provided for `Run All`, `Run Selected`, `Rerun` and `Run Failed`
* There is a new button for setting test parameters.
* The `Stop` and `Kill` buttons have been moved next to the four `Run` buttons.

### Not Yet Implemented

These will be done in separate issues which I will create.

* The `Rerun` and `Run Failed` buttons are non-functional.
* The `Group By` functionality is unchanged but needs a bit of reorganizing.
* The `Run Summary` functionality is unchanged but also needs a bit of rework.

**Comment by MartinZec** [comment]
I did a test run on dev00112:

Checkboxes enabled:
right click on test and run while other tests are checked: pass -> only the one test, which was right clicked was executed -> pass
run selected test only runs the checked tests -> pass
double click test to execute -> pass

what could be improved:
selecting one test and right clicking another test + run: the right clicked test is executed but the selection did not change, so still the previous selected test is selected and not the one which was actually executed
same for checkboxes enabled and disabled

Checkboxes disabled:
double click run -> pass
right click run -> pass
run selected tests still runs the tests which are checked although checkboxes are not shown any more -> fail; here the selected (not checked) test should be executed

Possible additional feature: "check all failed" and "uncheck all" buttons in case of checkboxes enabled

Additionally tested:
STOP - KILL:  went from STOP to KILL, but never left the KILL state in case test is looping forever.
Reload before each testrun: current tree setting is not stored, a previous tree setting is used after the reload was done

**Comment by CharliePoole** [comment]
For the first item, I see what's happening. The model needs to be told that there are no longer any checked tests whenever checkboxes are turned off. I'll fix that before worrying about the other points.

**Comment by CharliePoole** [comment]
Fixed both "run selected still runs the tests which are checked" and right click not selecting test.

Changed terminology internally and in GUI - selected test is now ActiveTestItem and SelectedTests are the tests run by the RunSelected button. Without checkboxes or when none are checked, the selected node fills both roles.

Also cleaned up the RunSummary display.

UI is present for debugging a test and for rerunning failed tests, but those are now separate issues.

I'll close this when the last PR merges and we'll go back to our normal practice of small issues / small changes for anything else that arises.
