### ISSUE TITLE
Test properties not auto resizing to the content value

### ISSUE THREAD

**Issue by gps7** [TestCentric/testcentric-gui#856]
Test description and full name might be very long. Description does not support multilines and overlaps with other rows. This information becomes clumsy and hard to read due this.

**To Reproduce**
1. Provide test full name with very long name (some our tests loaded dynamically, thus becoming very long). Provide description with multi lines or very long text.
2. Open TC and select test
3. Switch to "Test Properties" tab
4. Observe information about test

**Expected behavior**
A clear readable test information. Ability to scroll description if does not fit.

**Environment:**
 - TestCentric Version 2.0.0-alpha4
 - OS: Windows 10
 - Target Runtime for your test assembly:  .NET Framework 4.8.0

**Comment by CharliePoole** [comment]
Confirming this is a problem. The general design of the properties tab is that a popup display with the full text appears on hover. This seems to be broken for the full name and description right now.
