### ISSUE TITLE
Support use of VisualState when test assembly has changed.

### ISSUE THREAD

**Issue by CharliePoole** [TestCentric/testcentric-gui#890]
VisualState does it's job well when we save it on program close and restore it when reopening the same assembly, without changes. But it does not handle changes to the test assembly very well at all.

That's because the connection between the saved state and the loaded program is through the id of each test provided by the framework. That id is simply an integer, incremented for each test as it is discovered. Some consequences of this...

1. If a test method is removed, it's likely that some other method will be assigned the same id. Additionally, all methods whose ids are generated subsequently will now be "off." 
2. If a method is added, it will be taken as some other method.

While this may seem strange, it's actually due to the fact that the VisualState was originally only intended to allow restarting and picking up work where the programmer left off earlier. However, we'd like to keep as much of the visual state possible when changing and then reloading the program.

There is an NUnit issue, nunit/nunit#2771, which deals with this problem from the framework side. It has been around for about four years. But even if it were fixed, the GUI would still need to deal with older versions of the framework and potentially with other frameworks. So it seems that there needs to be some new identifier, created by the engine itself. We should probably take into account the hierarchy of tests at different levels and the actual name of the test as well.

I intend this issue to be an Epic, which will spawn other smaller issues to deal with individual problems such as name changes or deleted methods. This issue will be the central point for discussions of goals, design, algorithms, etc.

### Individual Issues

- [x] #891 
- [x] #892 
- [x] #895 
- [x] #906

**Comment by CharliePoole** [comment]
### Goal for Visual State Saving and Restoration - The Ideal

[@MartinZec I'd particularly like your comments on this one.]

When Visual State is restored for a file without changes, the visible tree will look the same with respect to overall shape, expansion, check marks and item selection. The topmost visible node will be the same. This should be the case even if the file has been recompiled without changes.

If any nodes (assemblies, namespaces, fixtures, methods) in the tree have been removed or if new nodes have been added, this causes the ids to change. The algorithm must not be confused by this and should not expand, check or select the wrong node. New nodes should obviously never be expanded, checked or selected.

If any nodes in the tree have been renamed, they should be recognized as representing the same test.

We may ignore some "pathological" cases, such as renaming a test and also adding a new one with the same name. :-)

### Priorities

Some goals are more important than others and some may need to be sacrificed to achieve more important goals.

1. The overall shape of the tree (what is and isn't expanded) is of the highest importance. In case of doubt, it's better to err on the side of __not__ expanding an element to avoid having extraneous nodes visible.

2. The TopNode controls which nodes are seen without scrolling, so it comes next in priority. When there is doubt, no TopNode should be selected so that it defaults to the first node in the tree. That gives the user only one direction in which to scroll.

3. Checked and Selected nodes are last in priority order but are obviously important. Again, it's preferable to avoid selecting or checking a node in case of uncertainty.

**Comment by MartinZec** [comment]
For a test rename, or a assembly change, without any change in tests/nodes, so where all previous nodes are still available, the tree should be loaded the same as in the case without changes, in my point of view, since all the integer IDs should not be changed.

In case of adding/removing nodes, I think it would be best to restore (expand) the tree as much as possible and stop at the level where the change(error) happened, and leave all following nodes collapsed. Worst case all nodes are collapsed, and only the top node is visible.

**Comment by MartinZec** [comment]
Considering #891, checking if only the name changed (for example: next name and ID still match) is maybe adding too much complexity and the easier solution is to keep the node collapsed also for renaming.

**Comment by CharliePoole** [comment]
Currently, renaming by itself works because we only use the id. You could rename every test you have, so long as you didn't add or delete any!

But most fixes I can think of for adding and removing end up breaking renaming. I think that's OK to do initially, simply not checking or expanding as you suggest. We can get fancier once the easier things work.

I also think a top-down algorithm will work better. Right now, we work top-down for each branch, so for 

A0
  B1
     C2
     D2
  E1
     F2

we follow the alphabet. It would be better to do all of level 0, 1 and 2 at one time, especially when looking for renames. For example, a class with a new name but the same methods is probably a rename. With different methods, it's probably a new class.

However... low-hanging fruit first is the best way to handle this and not expanding/checking is a safe option in most cases. It also behavior that the user can probably understand and accept.

**Comment by CharliePoole** [comment]
With the completion of #906, this issue can now be closed.
