### ISSUE TITLE
Visual state at reloading assembly

### ISSUE THREAD

**Issue by MartinZec** [TestCentric/testcentric-gui#892]
Follow-up of #887

In dev00137, "Save Visual State of each project" can be enabled or disabled.

Only the enabled option behaves as expected at an assembly reload.
In case "Save Visual State of each project" is disabled a default visual state needs to be loaded.

In my point of view, the setting "Save Visual State of each project" should be removed and the last visual state should be used all the time (option 3 from #887).

**Comment by CharliePoole** [comment]
I agree. It's always better to leave out options and wait for someone to say they need it. If you add an unnecessary option, nobody ever tells you it's not needed.

**Comment by CharliePoole** [comment]
@MartinZec Were you intending to do any work on this, or shall I take it on? FYI, if you are working on it, you should assign it to yourself.

**Comment by MartinZec** [comment]
@CharliePoole If possible, can you please do the work for this topic?
