### ISSUE TITLE
Shown tooltip is hard to hide for failed test

### ISSUE THREAD

**Issue by gps7** [TestCentric/testcentric-gui#901]
**Describe the bug**
There is a problem with failed test cases when accidentally hovering in Errors and Failures tab. It starts showing tooltip which covers all original error and it makes extremely hard to close this tooltip. Switching to another tab like Text Output or event resizing main window does not hide this window.

Additionally, executing multiple times same failing test the tooltip takes a full screen and this extremely annoying to close this it since TC window becomes hidden by tooltip. And, if TC main view becomes smaller than full screen then you can't even close this tooltip at all and only option left is to kill the TC process.

**To Reproduce**
1. Run any test which fails and results in long stack trace
2. Hover in "Errors and Failures" tab over the output result
3. The tooltip is shown with detailed results of failure
4. Click on tooltip, activate another TC tab, activate any other list or treeview control, click ESC or ENTER on tooltip - nothing hides this tooltip. Same applies to TC deactivation of main window which hides temporary the tooltip but shows once again when TC main screen is activated.

**Expected behavior**
Tooltip should be hidden once clicking on tooltip since text is not copying anyway. Activating another control also should hide the tooltip. The tooltip show window only for limited time (ideally configurable value) and option to disable the tooltip in Options would be also welcome.
Observed, that activating error list control hides the tooltip but if you can't get to this control this makes impossible to close the tooltip.

**Screenshots**
![TestCentric_shows_tooltip](https://user-images.githubusercontent.com/21167960/173305912-70801eb8-4a6d-4e52-b412-9f95f9baf683.PNG)
![TestCentric_shows_tooltip_fullscreen-small](https://user-images.githubusercontent.com/21167960/173329296-4678e694-f4f9-49d3-8c38-96fe31d621bc.png)

**Environment (please complete the following information):**
 - TestCentric Version 2.0.0-alpha4 (Release)
 - OS: Windows 10
 - Target Runtime for your test assembly:  .NET Framework 4.8.0]

**Comment by gps7** [comment]
Can anyone confirm this problem? I am getting quit annoyed with this problem.

**Comment by CharliePoole** [comment]
@gps7 I added some labels. Can this be duplicated without having a long stack trace? That is by trying to close without clicking on the underlying message?

**Comment by gps7** [comment]
Interestingly, I've tried to create a basic unit test with a long stack trace but this worked fine. After cloning and simplifying our SQA extensive structure with dynamically loaded test cases I was able to reproduce the problem again. Here is the code which results in this behavior:

```
using System;
using System.Collections.Generic;
using NUnit.Framework;

namespace My.Sqa.Scenarios
{
	internal class TestLongStackTrace
	{
		private static List<TestCaseData> Case => new List<TestCaseData>()
		{
			new TestCaseData(new TestCase(new MyTestCase())),
		};

		private class MyTestCase : EafSqaScenario
		{
			/// <inheritdoc />
			public override string Name => "My test scenario for executing test with long stack trace";

			/// <inheritdoc />
			public override void Execute() => ValidateTest(1, 50);

			private void ValidateTest(int level, int depth)
			{
				if (level < depth)
					ValidateTest(++level, depth);

				Assert.Fail($"You reached level {level}");
			}
		}

		[Test]
		[TestCaseSource(nameof(Case))]
		public void LongStackTrace(TestCase test)
		{
			var scenario = test.Scenario;
			Assert.IsNotNull(scenario, "Can't execute a null scenario.");

			ExecuteTest(scenario);
		}

		private void ExecuteTest(EafSqaScenario scenario) =>
			ExecutionHelper(() => scenario.Execute(), "execution", scenario.Name);

		private void ExecutionHelper(Action action, string phase, string scenarioName)
		{
			try
			{
				action();
			}
			catch (InconclusiveException ex)
			{
				throw new InconclusiveException($"Test marked inconclusive during test execution. {ex}", ex);
			}
			catch (SuccessException ex)
			{
				throw new SuccessException($"Test marked successful during test execution. {ex}", ex);
			}
			catch (IgnoreException ex)
			{
				throw new IgnoreException($"Test marked ignore during test execution. {ex}", ex);
			}
			catch (Exception ex)
			{
				throw new AssertionException($"Failure occurred during test execution. {ex}", ex);
			}
		}

		public class TestCase
		{
			public TestCase(EafSqaScenario scenario)
			{
				Scenario = scenario;
				TestName = scenario.Name;
			}

			public EafSqaScenario Scenario { get; }
			public string TestName { get; private set; }
			public override string ToString() => $"My.test.Instance.Name: {TestName}";
		}

		public abstract class EafSqaScenario
		{
			public abstract string Name { get; }
			public abstract void Execute();
			public override string ToString() => Name;
		}
	}
}
```

**Comment by CharliePoole** [comment]
OK, I'll experiment. I thought I remembered that the window closed on loss of focus, but apparently not.

**Comment by gps7** [comment]
This works with main window close but not when switching between view tabs. The tooltip randomly shown when hovering, when activating other window tab like output and etc. Thus it looks like uncontrolable. Setting a focus on message control removes the tooltip (if control is not hidden by tooltip message), however sometimes switching to other tab then back to same tab activates control and tooltip is shown again. I believe switching tab with active message control it considers as activated and it start showing tooltip again. That creates frustration when trying to copy the message with stack trace into clipboard by doing right click on control (you cannot access it most of time due too long stack traces) or simply just want to view the test output logs (the tooltip remains visible even control is not visible).
