### ISSUE TITLE
Testcentric 1.6.2 does not start when .Net 6.0 is installed

### ISSUE THREAD

**Issue by MichaelVFondern** [TestCentric/testcentric-gui#916]
The behaviour is the same like it was in this bug for the nunit-console runner: 

https://github.com/nunit/nunit-console/issues/1014

The Windows event log shows an `ArgumentException` message for `GetClrVersionForFramework`, and the Testcentric runner 1.6.2 does not start. As a workaround, I am now using version 1.4.0 again. 

Alternatively, the suggestion from the former bug report ( to move the 6.0* folders out of dotnet/shared/Microsoft.NETCore.App) stops the exception from being thrown as well.

**Comment by CharliePoole** [comment]
I'll fix for 7.0 at the same time

**Comment by MichaelVFondern** [comment]
Great to see you are working on it so quickly. Testcentric (as a replacement for the older Nunit 2.0 GUI) is a really helpful tool for us. Though we also use the Nunit console runner and the Visual Studio integration, both are not a real replacement.

**Comment by CharliePoole** [comment]
The ultimate fix would be to remove that code entirely, which I have done for the NUnit engine and plan to do for the 2.0 release of TestCentric. Not sure I want to go that far on what will be a legacy version, however.

On the other hand, I could put in some generic code which __might__ work when 8.0 is released. Obviously it would be untested code at this stage.

**Comment by CharliePoole** [comment]
Thinking about it I did not "pre-fix" the potential 8.0 error. As the code stands, the source of any error will be obvious if and when it occurs. If I fix it based on the "obvious" assumptions, it will probably work. However, it might not and the failure would then be some place later in the code leading to extra work to figure out the reason for the problem.

**Comment by MichaelVFondern** [comment]
Our expectation is that a unit test project created with .Net Framework 4.8 does not stop working just because a newer .Net Framework version is installed on the same machine (to which the unit test project does not have any dependencies). But maybe it is not that simple for Testcentric-GUI?

**Comment by CharliePoole** [comment]
A reasonable expectation, which is why this bug got the "Critical" label. But please bear in mind that we aren't talking here about how to fix the product in general general, but only how to fix it in the legacy version 1 code, against which you reported it.

Working on the version 1 code is currently quite difficult because both the development environment and the current code have now diverged so much. If we were doing this in the main branch, I would only have to type a command and click a few buttons and a new release would be published. Not so for version 1 fixes. In retrospect, things might be simpler if I had forked a completely new project for version 2, but unfortunately that ship has sailed. :-(

**Comment by MichaelVFondern** [comment]
Well, I could give the 2.0 alpha version a try, but I am a little bit cautious, since you described it as unstable, and 1.6.2 as stable,

**Comment by CharliePoole** [comment]
Precisely! As I'm sure you know, "unstable" in this context doesn't mean it crashes! It merely means that the feature set is subject to change. In particular, I use "alpha" to signal that features may appear temporarily and then go away, whereas "beta" means there will only be feature additions or enhancements.

You have got me thinking, however. :-)

**Comment by MichaelVFondern** [comment]
Ok, tried the 2.0. It works so far (and looks really nice!), but it seems the feature of running only tests of selected categories is missing. That one was really nice, made some use of it in our tests.

**Comment by CharliePoole** [comment]
Yeah. Both unstable and unfinished! I'm hoping to have category selection back in alpha-7.

**Comment by MichaelVFondern** [comment]
Sounds great, thanks a lot!

**Comment by CharliePoole** [comment]
Fixed by PR #918 

In addition, I changed my mind about "futuristic" fixes and added the fix we hope will work for future .NET releases.

**Comment by MichaelVFondern** [comment]
Thank you very much. I downloaded the source code of Testcentric V1.6.3, could compile it by myself (ignoring some minor warnings), and it works now again. Nice work!

**Comment by CharliePoole** [comment]
@MichaelVFondern Great! You could also have installed version 1.6.3-pre00001 from our MyGet feed. Some of the  latest `-dev` builds have the fix as well, but unfortunately they are being published as if they were 1.6.2 pre-releases, which I'll have to fix. If you look near the end of each appveyor merge build, you can see the version under which the build is published.
