### ISSUE TITLE
TestCentric-Gui 1.6.3 + NUnit IDriverFactory extension

### ISSUE THREAD

**Issue by rowo360** [TestCentric/testcentric-gui#925]
**Description:**
I observe that a [NUnit IDriverFactory](https://docs.nunit.org/articles/nunit-engine/extensions/creating-extensions/Framework-Drivers.html) extension is not invoked while executing a test with **TestCentric-Gui 1.6.3.**
The test assembly targets **.Net Framwork 4.8**

The extension shows up properly in the TestCentric-Gui (Menu -> Tools -> Extensions) with the status 'Enabled'. So the extension seems to be correctly integrated into the TestCentric system.
Nonetheless while executing the tests the extension did not get invoked.

**Expected behavior**
Simply said: the extension should be invoked identically to executing the test using NUnit console.

**Additional information:**
Here are some additional information which might be helpful. I already debugged this scenario and observed that although the TestCentric-Gui detects the extension properly, the testcentric agent will not load the extension at all. 
And looking a little deeper into the code: there's the class TestCentric.Engine.Core/Services/DriverService.cs which is responsible to load IDriverFactory extensions. It contains a method StartService() which will get all IDriverFactory extensions from the ExtensionService. Unfortunately this code part is surrounded with some conditional compiler flags
#if NET20 || NETSTANDARD2_0
So if using a test assembly targeting .Net Framwork 4.8 this code part won't be executed.
For testing purpose I changed the conditional compiler flags to 
#if NET20 || NET40 || NETSTANDARD2_0
And yes indeed, now the extension gets invoked properly and works successfully. However I have no idea about the consequences of this code change, but nonetheless I hope all this information might be helpful.

And one last comment:
Using NUnit IDriverFactory extensions with the latest TestCentric-Gui (2.0-alpha) doesn't work either. The code stack is completly different, but the bottom line is that IDriverFactory extensions are not getting loaded by the testcentric.engine.core on that version. But I want to keep these two issues separate and asking for a fix about this issue for TestCentric-Gui 1.6.X release first.

**Environment:**
 - TestCentric Version 1.6.3
 - OS: Windows 10
 - Target Runtime for your test assembly: .NET Framework 4.8

**Comment by CharliePoole** [comment]
Good catch! I added the NET40 build a long time ago but never changed this. Clearly, I'm missing a test!!! I believe your fix is correct, but I'll do some testing to be sure and do a point release.

I'm currently focused on getting out a release of the NUnit console runner before retiring as maintainer of that project. After that I'll I'll have time to look at the same issue in the 2.0 build.

**Comment by rowo360** [comment]
Perfect! Sounds greats - thanks!
