### ISSUE TITLE
TestCentric 2.0.0-alpha7:  Invalid DisplayStrategy and NullReferenceException

### ISSUE THREAD

**Issue by MartinZec** [TestCentric/testcentric-gui#945]
Hello,

Thank you for the new alpha release!

I updated to 2.0.0 alpha7, but when I open my tests I get the attached exceptions.
In event viewer I see a NullReferenceException.

Please find the logs attached.

Best regards,
Martin

[Invalid DisplayStrategy.txt](https://github.com/TestCentric/testcentric-gui/files/10673690/Invalid.DisplayStrategy.txt)
[NullReferenceException.txt](https://github.com/TestCentric/testcentric-gui/files/10673712/NullReferenceException.txt)
[NullReferenceException_text.txt](https://github.com/TestCentric/testcentric-gui/files/10673775/NullReferenceException_text.txt)

**Comment by CharliePoole** [comment]
@MartinZec

Are you running from the command-line or by clicking an icon? If from the command-line, any files or options specified?

**Comment by MartinZec** [comment]
I have a dll, which is opened with testcentric, so with dpoble clicking the dll.
I can open testcentric as admin, then the dll is not loaded. But after loading the dll, I get the errors. 

I downloaded the zip: testcentric-gui-2.0.0-alpha7.zip

**Comment by MartinZec** [comment]
I installed the nuget package via visual studio (testcentric-gui.2.0.0-dev00210), copied it to the same folder, still the same issue.
I have no additional addins installed

**Comment by CharliePoole** [comment]
Probably better to try the actual alpha release from nuget.org although it ought to be identical to dev00210. FYI the testcentric-gui package is actually intended for chocolatey installs. TestCentric.Gui is for nuget.org. But, in fact, they should work the same... it's just that lower case and dashes is a chocolatey naming standard.

I'll look into this further. What runtime does your test target? Can you give me a minimal repro?

**Comment by MartinZec** [comment]
I am using ImageRuntimeVersion = 4.0.30319, .NET Framework 4.8.

Still using dev00210.

Attached a mini project where opening ClassLibrary1.dll caused the same issue as reported. This mini project is working with testcentric 1.6.4. Expected output from 1.6.4:  

=> ClassLibrary1.Class1.test1
test

[Solution1.zip](https://github.com/TestCentric/testcentric-gui/files/10684171/Solution1.zip)

**Comment by CharliePoole** [comment]
The source of the error is in the file `ClassLibrary1.dll.VisualState.xml` It seems to disappear if I erase that file before loading and a valid VisualState file is then created. I'm still examining how the invalid file gets created. Have you used earlier alpha releases or dev builds? If so, which is the latest one that works for you?

Of course TestCentric should handle this situation better, so I'll fix that first.

**Comment by CharliePoole** [comment]
That makes sense. In Version 1, the VisualState only applied to the NUnitTree display strategy. I'll fix that by using a default value.

By the way, I wanted to mention that you have to select alpha and beta versions manually in Visual Studio, if you have both nuget.org and myget.org as sources. That's because the `2.0.0-dev` builds appear to nuget as a higher version than `2.0.0-alpha` or `2.0.0-beta`. I couldn't think of a meaningful label < `dev`. :-(

**Comment by CharliePoole** [comment]
@MartinZec Finally fixed! See version 2.0.0-dev00265.

I've been spending time working on automating the build process but I'm now back to doing bugs and features.
