### ISSUE TITLE
TestCentric 2.0.0-alpha7: InvalidOperationException while VisualState gets generated for deep namespaces

### ISSUE THREAD

**Issue by MartinZec** [TestCentric/testcentric-gui#946]
Hello,

In case of too deep namespaces, the attached test.VisualState.xml is generated and the attached exception is thrown.
Changed test.VisualState.xml.xml to test.VisualState.xml.txt to be able to upload

Best regards,
Martin
[InvalidOperationException.txt](https://github.com/TestCentric/testcentric-gui/files/10697341/InvalidOperationException.txt)
[test.VisualState.xml.txt](https://github.com/TestCentric/testcentric-gui/files/10697346/test.VisualState.xml.txt)

**Comment by CharliePoole** [comment]
Can you attach the source file, which resulted in that exception? The exception message refers to a circular reference and I can't figure out how that could happen in a tree display.

**Comment by MartinZec** [comment]
It took me a while to find it, same class name as namespace.
Please find a new Solution1.zip attached for reproducing.
[Solution1.zip](https://github.com/TestCentric/testcentric-gui/files/10699345/Solution1.zip)

**Comment by CharliePoole** [comment]
For now, I wrapped the exception in another one with an explanatory message. This will, as I thought, take a bit more work to fix correctly.

**Comment by CharliePoole** [comment]
This was fixed in PR #969 and is available from myget as version 2.0.0-dev00272.

In order to fix this problem, I had to entirely re-implement serialization and deserialization of VisualState using the IXmlSerializable interface. As a result, we may find some new issues going forward.

@MartinZec Will you give this release a test drive?

**Comment by MartinZec** [comment]
@CharliePoole Thank you for the new version, I tested dev00276. This issue is solved.
Side observation: I used "Reload before each test run". The test group, where the executed test belongs to, is not expanded after the reload. In other words I do not see the executed test after the reload, only one level above.
