### ISSUE TITLE
TestCentric.GuiRunner 2.0.0-alpha8: testcentric.extensibility.dll is missing in net462 agent

### ISSUE THREAD

**Issue by MartinZec** [TestCentric/testcentric-gui#974]
Hello,

I was not able to load my test assembly with alpha8, so I compared testcentric-gui.2.0.0-dev00276 with alpha8 release.
testcentric.extensibility.dll was missing in net462 agent folder.
I added it to alpha8 folder structure, now I can load my assembly.

Best regards,
Martin

**Comment by CharliePoole** [comment]
@MartinZec Which download did you use? i.e. GitHub, Chocolatey, etc.

**Comment by CharliePoole** [comment]
I looked at TestCentric.GuiRunner.zip and it does contain the dll in the 462 agent folder. I'm not sure but if you were really quick off the mark, it's possible you got a bad copy, which I then corrected.

**Comment by MartinZec** [comment]
@CharliePoole yes you are right, I downloaded it 16:53 CEST, the current available version has the *.dll included. Thank you for fixing it.
